package net.hollowcube.luau.engineapi.task;

import net.hollowcube.luau.engineapi.resolve.Aggregator;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/// CLI entrypoint for the `buildLuauDeclarations` Gradle task. Stub implementation: reads the
/// engine-api schema (to validate it parses) and writes an empty `.d.luau` placeholder. The
/// actual emitter is future work.
///
/// Usage:
/// ```
/// DeclMain --schema path/to/engine-api.json --output path/to/engine.d.luau
/// ```
public final class DeclMain {

    public static void main(String[] args) {
        Path schemaPath = null;
        Path outputPath = null;
        for (int i = 0; i < args.length; i++) {
            switch (args[i]) {
                case "--schema" -> schemaPath = Path.of(args[++i]);
                case "--output" -> outputPath = Path.of(args[++i]);
                default -> {
                    System.err.println("Unknown arg: " + args[i]);
                    System.exit(2);
                }
            }
        }
        if (schemaPath == null || outputPath == null) {
            System.err.println("--schema and --output are both required");
            System.exit(2);
        }

        var schema = Aggregator.readSchema(schemaPath);
        try {
            if (outputPath.getParent() != null) Files.createDirectories(outputPath.getParent());
            // Stub — write a header comment and an empty body. A future task fills this in from
            // the resolved Model + LuauType AST.
            var header = "-- Generated by lua-slopgen engine-api. DO NOT EDIT.\n"
                         + "-- libraries: " + schema.libraries().size() + "\n";
            Files.writeString(outputPath, header, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to write declarations: " + outputPath, e);
        }
        System.out.println("Wrote .d.luau stub: " + outputPath);
    }
}
