version: "3.0"

networks:
  mapmaker:
    driver: bridge

services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ../../build/local/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: test
    networks:
      - mapmaker
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../../build/local/minio:/data
    environment:
      MINIO_ROOT_USER: mapmaker
      MINIO_ROOT_PASSWORD: mapmaker
    command: server --console-address ":9001" /data
    networks:
      - mapmaker
  spicedb:
    image: "authzed/spicedb"
    command: "serve"
    restart: "always"
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50051:50051"
    environment:
      - "SPICEDB_GRPC_PRESHARED_KEY=foobar"
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://mapmaker:mapmaker@postgres:5432/spicedb?sslmode=disable"
    depends_on:
      - "migrate"
    networks:
      - mapmaker
  migrate:
    image: "authzed/spicedb"
    command: "migrate head"
    restart: "on-failure"
    environment:
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://mapmaker:mapmaker@postgres:5432/spicedb?sslmode=disable"
    depends_on:
      - "postgres"
    networks:
      - mapmaker
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=mapmaker"
      - "POSTGRES_PASSWORD=mapmaker"
      - "POSTGRES_DB=spicedb"
    networks:
      - mapmaker
