http:
  host: 0.0.0.0
  port: 9124

minestom:
  host: 0.0.0.0
  port: 25565
  # Translation mode: server,proxy
  translation: server

velocity:
  secret: ""

global:
  noop: false

kafka:
  bootstrap_servers: localhost:9092

unleash:
  enabled: false
  address: ""
  token: ""
  default_action: false

announcements:
  interval: 1800
  messages:
    - key: "announcement.global.omega_parkour"
    - key: "announcement.global.lobby"
    - key: "announcement.global.find"
    - key: "announcement.play.leaderboards"
      filters:
        session_type: "mapmaker:map"
        session_state: "playing"
    - key: "announcement.play.spectator_mode"
      filters:
        session_type: "mapmaker:map"
        session_state: "playing"
    - key: "announcement.play.savestate"
      filters:
        session_type: "mapmaker:map"
        session_state: "playing"
    - key: "announcement.build.map_tags"
      filters:
        session_type: "mapmaker:map"
        session_state: "editing"
    - key: "announcement.build.invite"
      filters:
        session_type: "mapmaker:map"
        session_state: "editing"
    - key: "announcement.build.give"
      filters:
        session_type: "mapmaker:map"
        session_state: "editing"
    - key: "announcement.build.test"
      filters:
        session_type: "mapmaker:map"
        session_state: "editing"
    - key: "announcement.build.setspawn"
      filters:
        session_type: "mapmaker:map"
        session_state: "editing"
    - key: "announcement.build.schematic"
      filters:
        session_type: "mapmaker:map"
        session_state: "editing"