http:
  host: 0.0.0.0
  port: 9124
metrics:
  password: ""

minestom:
  host: 0.0.0.0
  port: 25565
  # Translation mode: server,proxy
  translation: server

tracing:
  otlp_endpoint: ""

velocity:
  secret: ""

global:
  noop: false

kafka:
  bootstrap_servers: localhost:9093

unleash:
  enabled: false
  use_posthog: false
  address: ""
  token: ""
  default_action: false

announcements:
  interval: 1800
  messages:
    - key: "announcement.global.omega_parkour"
    - key: "announcement.global.find"
    - key: "announcement.global.bugs_and_suggestions"
    - key: "announcement.global.cosmetics"
    - key: "announcement.play.leaderboards"
    - key: "announcement.play.spectator_mode"
    - key: "announcement.play.savestate"
    - key: "announcement.build.map_tags"
    - key: "announcement.build.invite"
    - key: "announcement.build.give"
    - key: "announcement.build.test"
    - key: "announcement.build.setspawn"
    - key: "announcement.build.schematic"