name: mapmaker
version: '3.8'
services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mapmaker
      MINIO_ROOT_PASSWORD: mapmaker
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console UI
    volumes:
      - minio-data:/data
  redis:
    image: redis:7.4
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  nats:
    image: nats:2.12.4
    restart: unless-stopped
    command: "--jetstream --store_dir /data"
    ports:
      - "4222:4222"
    volumes:
      - nats-data:/data

  api-server:
    build:
      context: ../api-server
      dockerfile: deploy/Dockerfile
    restart: unless-stopped
    depends_on: [ postgres, nats, redis ]
    environment:
      SESSION_ENV: "tilt"
      SESSION_HTTP_ADDRESS: "0.0.0.0"
      SESSION_HTTP_PORT: "9124"
      SESSION_REDIS_ADDRESS: "redis:6379"

      SESSION_POSTGRES_PLAYERS_URI: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      SESSION_POSTGRES_MAPS_URI: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      SESSION_POSTGRES_URI: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"

      SESSION_NATS_SERVERS: "nats://nats:4222"

      SESSION_S3_ENDPOINT: "http://minio:9000"
      SESSION_S3_ACCESS_KEY: "mapmaker"
      SESSION_S3_SECRET_KEY: "mapmaker"

      SESSION_TEBEX_SECRET: "explicit_ignore"

      SESSION_KUBERNETES_NAMESPACE: "disabled"
    ports:
      - "9127:9124"

volumes:
  postgres-data:
  minio-data:
  redis-data:
  nats-data:
