name: mapmaker
version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  spicedb-migrate:
    image: ghcr.io/authzed/spicedb:v1.35.3
    restart: no
    depends_on:
      - postgres
    environment:
      SPICEDB_DATASTORE_ENGINE: postgres
      SPICEDB_DATASTORE_CONN_URI: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    entrypoint: [ "spicedb", "migrate", "head" ]
  spicedb:
    image: ghcr.io/authzed/spicedb:v1.35.3
    restart: unless-stopped
    depends_on:
      - postgres
      - spicedb-migrate
    environment:
      SPICEDB_DATASTORE_ENGINE: postgres
      SPICEDB_DATASTORE_CONN_URI: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      SPICEDB_GRPC_PRESHARED_KEY: supersecretkey
      SPICEDB_HTTP_ENABLED: "true"
    command: "serve"
    ports:
      - "50051:50051"
      - "8443:8443"
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mapmaker
      MINIO_ROOT_PASSWORD: mapmaker
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console UI
    volumes:
      - minio-data:/data
  redis:
    image: redis:7.4
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  redpanda:
    image: redpandadata/redpanda:v23.3.10
    container_name: redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr=INSIDE://redpanda:9092,OUTSIDE://localhost:9093
      - --set auto_create_topics_enabled=true
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - redpanda-data:/var/lib/redpanda/data

  player-service:
    build:
      context: ../player-service
      dockerfile: ../player-service/deploy/Dockerfile
    restart: unless-stopped
    depends_on: [ postgres, spicedb, redpanda ]
    environment:
      PLAYERS_ENV: "tilt"
      PLAYERS_HTTP_ADDRESS: "0.0.0.0"
      PLAYERS_HTTP_PORT: "9124"
      PLAYERS_POSTGRES_URI: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      PLAYERS_SPICEDB_ENDPOINT: "spicedb:50051"
      PLAYERS_SPICEDB_TOKEN: "supersecretkey"
      PLAYERS_KAFKA_BROKERS: "redpanda:9092"
      PLAYERS_TEBEX_SECRET: "explicit_ignore"
    ports:
      - "9126:9124"
  map-service:
    build:
      context: ../map-service
      dockerfile: ../map-service/deploy/Dockerfile
    restart: unless-stopped
    depends_on: [ postgres, spicedb, minio, redis, redpanda, player-service ]
    environment:
      MAPS_ENV: "tilt"
      MAPS_HTTP_ADDRESS: "0.0.0.0"
      MAPS_HTTP_PORT: "9124"
      MAPS_POSTGRES_URI: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      MAPS_SPICEDB_ENDPOINT: "spicedb:50051"
      MAPS_SPICEDB_TOKEN: "supersecretkey"
      MAPS_S3_ENDPOINT: "http://minio:9000"
      MAPS_S3_ACCESS_KEY: "mapmaker"
      MAPS_S3_SECRET_KEY: "mapmaker"
      MAPS_REDIS_ADDRESS: "redis:6379"
      MAPS_KAFKA_BROKERS: "redpanda:9092"
      MAPS_PLAYER_SERVICE_URL: "http://player-service:9124"
    ports:
      - "9125:9124"
  session-service:
    build:
      context: ../session-service
      dockerfile: ../session-service/deploy/Dockerfile
    restart: unless-stopped
    depends_on: [ postgres, spicedb, redis, redpanda, player-service ]
    environment:
      SESSION_ENV: "tilt"
      SESSION_HTTP_ADDRESS: "0.0.0.0"
      SESSION_HTTP_PORT: "9124"
      SESSION_REDIS_ADDRESS: "redis:6379"
      SESSION_PLAYER_SERVICE_URL: "http://player-service:9124"
      SESSION_POSTGRES_URI: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      SESSION_KAFKA_BROKERS: "redpanda:9092"
      SESSION_SPICEDB_ENDPOINT: "spicedb:50051"
      SESSION_SPICEDB_TOKEN: "supersecretkey"
      SESSION_KUBERNETES_NAMESPACE: "disabled"
    ports:
      - "9127:9124"

volumes:
  postgres-data:
  minio-data:
  redis-data:
  redpanda-data:
