apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mapmaker.fullname" . }}
  labels:
    {{- include "mapmaker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mapmaker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        mapmaker.hollowcube.net/role: {{ .Values.mapmaker.role }}
        {{- include "mapmaker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mapmaker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      terminationGracePeriodSeconds: {{ .Values.mapmaker.terminationSeconds }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.prefix }}{{ .Values.mapmaker.role }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: minecraft
              containerPort: {{ .Values.service.minecraftPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /observe/health/live
              port: http
          readinessProbe:
            httpGet:
              path: /observe/health/ready
              port: http
          lifecycle:
            preStop:
              httpGet:
                port: http
                path: shutdown
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MAPMAKER_TERMINATION_SECONDS
              value: "{{ .Values.mapmaker.terminationSeconds }}"
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
