apiVersion: v1
kind: Service
metadata:
  name: {{ include "mapmaker.fullname" . }}
  labels:
    {{- include "mapmaker.labels" . | nindent 4 }}
    mapmaker_role: {{ .Values.mapmaker.role }} # For ServiceMonitor
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.minecraftPort }}
      targetPort: minecraft
      protocol: TCP
      name: minecraft
  selector:
    {{- include "mapmaker.selectorLabels" . | nindent 4 }}
