package net.hollowcube.luau.slopgen;

import com.google.auto.service.AutoService;
import com.palantir.javapoet.*;
import com.sun.source.util.DocTrees;
import net.hollowcube.luau.gen.LuaLibrary;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedOptions;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import java.io.IOException;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

@AutoService(Processor.class)
@SupportedOptions({"org.gradle.annotation.processing.aggregating"})
public class LuaSlopgenProcessor extends AbstractProcessor {
    // This has to be an aggregating processor currently because we need to create
    // the string atom table, however it could be possible to instead run two processors
    // one which is isolating for each file and reference atoms like `LuaStringAtoms.MyString`
    // which will be inlined during compiltion
    //
    // However, an aggregating processor is still needed to generate LuaStringAtoms, and
    // its not obvious how to communicate the strings from the first step.
    // It also isnt a performance issue currently, so dont care.

    private final StringAtomizer atomizer = new StringAtomizer();

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        var messager = processingEnv.getMessager();
        var elementUtils = processingEnv.getElementUtils();
        var filer = processingEnv.getFiler();
        var docTrees = DocTrees.instance(processingEnv);

        for (var annotatedElement : roundEnv.getElementsAnnotatedWith(LuaLibrary.class)) {
            if (!(annotatedElement instanceof TypeElement typeElement)) continue;

            if (!typeElement.getModifiers().contains(Modifier.FINAL))
                messager.printError("LuaLibrary classes must be final", annotatedElement);

            var luaLibraryMirror = typeElement.getAnnotationMirrors().stream()
                .filter(mirror -> mirror.getAnnotationType().toString().equals(LuaLibrary.class.getName()))
                .findFirst().orElseThrow();
            var luaLibraryValues = luaLibraryMirror.getElementValues().entrySet().stream().collect(Collectors.toMap(
                e -> e.getKey().getSimpleName().toString(),
                Map.Entry::getValue));

            var packageName = elementUtils.getPackageOf(typeElement).getQualifiedName().toString();
            var glueTypeName = ClassName.get(packageName, typeElement.getSimpleName() + "$luau");
            var glueTypeBuilder = TypeSpec.classBuilder(glueTypeName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addOriginatingElement(annotatedElement);

            var libNameString = luaLibraryValues.get("name").getValue().toString();
            glueTypeBuilder.addField(FieldSpec.builder(String.class, "LIB_NAME")
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
                .initializer("$S", libNameString)
                .build());

            boolean isGlobal = "GLOBAL".equals(String.valueOf(luaLibraryValues.get("scope")));
            if (isGlobal && !libNameString.matches("^[a-zA-Z_][a-zA-Z0-9_]*$"))
                messager.printError("Global-scoped LuaLibrary name must be a valid global identifier", annotatedElement);
            if (!isGlobal && !libNameString.startsWith("@"))
                messager.printError("Require-scoped LuaLibrary name must start with @", annotatedElement);

            var builder = new LuaLibraryClassBuildingVisitor(
                processingEnv, atomizer,
                TypeName.get(typeElement.asType()),
                glueTypeName, glueTypeBuilder,
                isGlobal
            );
            builder.visit(typeElement);
            builder.finish();

            try {
                JavaFile.builder(packageName, glueTypeBuilder.build())
                    .addFileComment("Generated by Lua Slopgen. DO NOT EDIT!")
                    .indent("    ")
                    .build()
                    .writeTo(filer);
            } catch (IOException e) {
                messager.printError("Failed to write generated file for " + annotatedElement.getSimpleName(), annotatedElement);
            }
        }

        if (roundEnv.processingOver()) {
            try {
                atomizer.build().writeTo(filer);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }

        return true;
    }

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return Set.of(LuaLibrary.class.getName());
    }

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.RELEASE_25;
    }
}
