package net.hollowcube.luau.slopgen;

import com.palantir.javapoet.*;
import it.unimi.dsi.fastutil.objects.Object2ShortMap;
import it.unimi.dsi.fastutil.objects.Object2ShortMaps;
import it.unimi.dsi.fastutil.objects.Object2ShortOpenHashMap;
import net.hollowcube.luau.LuaCallbacks;
import net.hollowcube.luau.LuaState;

import javax.lang.model.element.Modifier;
import java.lang.foreign.Arena;
import java.util.concurrent.atomic.AtomicInteger;

// Manages a cache of string to its string atom.
//todo rename since this also holds the tag cache
public final class StringAtomizer {

    private final AtomicInteger nextUserDataTag = new AtomicInteger(1);

    private final AtomicInteger nextAtom = new AtomicInteger(1);
    private final Object2ShortMap<String> known = new Object2ShortOpenHashMap<>();

    public short atomize(String string) {
        return known.computeIfAbsent(string, _ -> {
            int next = nextAtom.getAndIncrement();
            if (next > Short.MAX_VALUE) {
                throw new IllegalStateException("Too many atoms!");
            }
            return (short) next;
        });
    }

    public int userDataTag() {
        int nextTag = nextUserDataTag.getAndIncrement();
        if (nextTag >= 255)
            throw new IllegalStateException("Too many userdata tags!");
        return nextTag;
    }

    public boolean isEmpty() {
        return known.isEmpty();
    }

    public ClassName generatedTypeName() {
        return ClassName.get(LuaNames.RUNTIME_PACKAGE_NAME, "GeneratedStringAtoms");
    }

    public JavaFile build() {
        var typeName = generatedTypeName();
        var typeBuilder = TypeSpec.classBuilder(typeName)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL);

        // UserAtom function reference initializer
        typeBuilder.addField(FieldSpec.builder(LuaCallbacks.UserAtom.class, "USER_ATOM")
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer("$T.allocate($T::$L, $T.global())",
                LuaCallbacks.UserAtom.class, typeName, "userAtom", Arena.class)
            .build());

        var mapType = ParameterizedTypeName.get(Object2ShortMap.class, String.class);
        typeBuilder.addField(FieldSpec.builder(mapType, "HOLDER")
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .build());

        // register function setting useratom callback
        typeBuilder.addMethod(MethodSpec.methodBuilder("register")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addParameter(LuaState.class, "state")
            .addStatement("state.callbacks().userAtom(USER_ATOM)")
            .build());

        // Map lookup function
        // We could do something more fun here like compute a perfect hash function
        // based on our inputs, or generate a prefix trie matcher. But this is fine for now.
        typeBuilder.addMethod(MethodSpec.methodBuilder("userAtom")
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
            .addParameter(String.class, "string")
            .returns(TypeName.SHORT)
            .addStatement("return HOLDER.getOrDefault(string, $T.NO_ATOM)", LuaState.class)
            .build());

        var initBlock = CodeBlock.builder();
        initBlock.addStatement("$T holder = new $T<>()", mapType, Object2ShortOpenHashMap.class);
        for (var entry : known.object2ShortEntrySet())
            initBlock.addStatement("holder.put($S, (short) $L)", entry.getKey(), entry.getShortValue());
        initBlock.addStatement("HOLDER = $T.unmodifiable(holder)", Object2ShortMaps.class);
        typeBuilder.addStaticBlock(initBlock.build());

        return JavaFile.builder(LuaNames.RUNTIME_PACKAGE_NAME, typeBuilder.build())
            .addFileComment("Generated by Lua Slopgen. DO NOT EDIT!")
            .indent("    ")
            .build();
    }
}
