mapmaker:
  role: hub

  terminationSeconds: 30

image:
  prefix: ""

env:
  MAPMAKER_COMMIT_SHA: "ᴛɪʟᴛ"
  MAPMAKER_RESOURCE_PACK_HASH: "dev"
  MAPMAKER_VELOCITY_SECRET: "abcdef"
  MAPMAKER_SHUTDOWN_MAX_WAIT_MILLIS: "15000" # 15 seconds

  MAPMAKER_MAP_SERVICE_URL: "http://api-server:9124"
  MAPMAKER_PLAYER_SERVICE_URL: "http://api-server:9124"
  MAPMAKER_SESSION_SERVICE_URL: "http://api-server:9124"
  MAPMAKER_PLAYER_INVITE_SERVICE_URL: "http://api-server:9124"

  MAPMAKER_NATS_SERVERS: "nats://nats:4222"

replicaCount: 1
