fullnameOverride: mapmaker-hub

mapmaker:
  role: hub

  terminationSeconds: 30

image:
  prefix: "mworzala/mapmaker-"
  pullSecrets:
    - name: dockerio

serviceMonitor:
  enabled: true

env:
  MAPMAKER_COMMIT_SHA: "$COMMIT_SHA"
  MAPMAKER_RESOURCE_PACK_HASH: "$RESOURCE_PACK_HASH"

  MAPMAKER_METRICS_PASSWORD: "${METRICS_PASSWORD}"
  MAPMAKER_TRACING_OTLP_ENDPOINT: "http://grafana-k8s-monitoring-grafana-agent.mapmaker.svc.cluster.local:4318/v1/traces"

  MAPMAKER_VELOCITY_SECRET: "AsmMzWkjyrNvu5DprZWupQXy79mKFHK7d5Aj662YmVq4zEQns3RWb7NFpxvcTzgV"

  MAPMAKER_MAP_SERVICE_URL: "http://map-service.mapmaker.svc.cluster.local:9124"
  MAPMAKER_PLAYER_SERVICE_URL: "http://player-service.mapmaker.svc.cluster.local:9124"
  MAPMAKER_SESSION_SERVICE_URL: "http://session-service.mapmaker.svc.cluster.local:9124"
  MAPMAKER_PLAYER_INVITE_SERVICE_URL: "http://session-service.mapmaker.svc.cluster.local:9124"

  MAPMAKER_SPICEDB_URL: "spicedb:50051"
  MAPMAKER_SPICEDB_TOKEN: "${SPICEDB_SECRET_KEY}"
  MAPMAKER_KAFKA_BOOTSTRAP_SERVERS: "kafka:9093"

  MAPMAKER_UNLEASH_ENABLED: "true"
  MAPMAKER_UNLEASH_ADDRESS: "http://unleash.mgmt.svc.cluster.local:4242/api"
  MAPMAKER_UNLEASH_TOKEN: "${UNLEASH_TOKEN}"

  MAPMAKER_SPAWN_MAP_ID: "b210fa07-d64c-4100-a2db-1426c35b7533"

replicaCount: 1
