http:
  host: 0.0.0.0
  port: 9124

minestom:
  host: 0.0.0.0
  port: 25565
  # Translation mode: server,proxy
  translation: server

mongo:
  uri: mongodb://localhost:27017
  database: mapmaker
  useTransactions: false

s3:
  uri: s3://mapmaker:mapmaker@localhost:9000/mapmaker?insecure=true

spicedb:
  address: localhost:50051
  secretKey: foobar
  tls: false

kafka:
  bootstrap_servers: localhost:29092
