image:
  repository: mworzala/mapmaker-map-isolate
  pullSecrets:
    - name: dockerio

mapmaker:
  resourcePackHash: ${RESOURCE_PACK_HASH}

env:
  MAPMAKER_NATS_SERVERS: "nats://nats:4222"
  MAPMAKER_MAP_SERVICE_URL: "http://session-service.mapmaker.svc.cluster.local:9124"
  MAPMAKER_PLAYER_INVITE_SERVICE_URL: "http://session-service.mapmaker.svc.cluster.local:9124"
  MAPMAKER_PLAYER_SERVICE_URL: "http://session-service.mapmaker.svc.cluster.local:9124"
  MAPMAKER_SESSION_SERVICE_URL: "http://session-service.mapmaker.svc.cluster.local:9124"
  MAPMAKER_UNLEASH_ENABLED: false
  MAPMAKER_UNLEASH_USE_POSTHOG: true
  MAPMAKER_UNLEASH_POSTHOG_PERSONAL_API_KEY: ${MAPMAKER_UNLEASH_POSTHOG_PERSONAL_API_KEY}
  MAPMAKER_UNLEASH_POSTHOG_PROJECT_API_KEY: ${MAPMAKER_UNLEASH_POSTHOG_PROJECT_API_KEY}
  MAPMAKER_VELOCITY_SECRET: ${MAPMAKER_VELOCITY_SECRET}

  MAPMAKER_TRACING_OTLP_ENDPOINT: "http://tempo.monitoring.svc.cluster.local:4318/v1/traces"
