image:
  repository: mworzala/mapmaker-map-isolate

mapmaker:
  resourcePackHash: ${RESOURCE_PACK_HASH}

env:
  MAPMAKER_KAFKA_BOOTSTRAP_SERVERS: ${MAPMAKER_KAFKA_BOOTSTRAP_SERVERS}
  MAPMAKER_MAP_SERVICE_URL: ${MAPMAKER_MAP_SERVICE_URL}
  MAPMAKER_PLAYER_INVITE_SERVICE_URL: ${MAPMAKER_PLAYER_INVITE_SERVICE_URL}
  MAPMAKER_PLAYER_SERVICE_URL: ${MAPMAKER_PLAYER_SERVICE_URL}
  MAPMAKER_SESSION_SERVICE_URL: ${MAPMAKER_SESSION_SERVICE_URL}
  MAPMAKER_SPICEDB_TOKEN: ${MAPMAKER_SPICEDB_TOKEN}
  MAPMAKER_SPICEDB_URL: ${MAPMAKER_SPICEDB_URL}
  MAPMAKER_UNLEASH_ENABLED: ${MAPMAKER_UNLEASH_ENABLED}
  MAPMAKER_UNLEASH_POSTHOG_PERSONAL_API_KEY: ${MAPMAKER_UNLEASH_POSTHOG_PERSONAL_API_KEY}
  MAPMAKER_UNLEASH_POSTHOG_PROJECT_API_KEY: ${MAPMAKER_UNLEASH_POSTHOG_PROJECT_API_KEY}
  MAPMAKER_UNLEASH_USE_POSTHOG: ${MAPMAKER_UNLEASH_USE_POSTHOG}
  MAPMAKER_VELOCITY_SECRET: ${MAPMAKER_VELOCITY_SECRET}
