package net.hollowcube.scripting.emit;

import com.palantir.javapoet.ClassName;
import net.hollowcube.scripting.Model;
import net.hollowcube.scripting.gen.LuaLibrary;
import net.hollowcube.scripting.types.LuauType;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class GlobalDeclEmitterTest {

    private static LuauType t(String name) {
        return new LuauType.Named(null, name, List.of());
    }

    private static Model.Library global(String module, List<Model.Export> exports,
                                        List<Model.Method> statics) {
        return new Model.Library(ClassName.get("p", "G"), ClassName.get("p", "G$luau"),
            module, LuaLibrary.Scope.GLOBAL, exports, statics, List.of(), "");
    }

    @Test
    void classWithMembersAndLibTable() {
        var widget = new Model.Export(
            ClassName.get("p", "Widget"), "Widget", null, false, List.of(),
            List.of(new Model.Property("name",
                new Model.Accessor("getName", ClassName.get("p", "Widget"), "", null, t("string")), null)),
            List.of(new Model.Method("tick", "tick", false, ClassName.get("p", "Widget"), "",
                List.of(), List.of(new Model.Param("dt", false, t("number"), "")), List.of())),
            List.of(new Model.MetaMethod("__tostring", "ts", false, "", List.of(), List.of(),
                List.of(new Model.Return(t("string"), "")))),
            1, false, Model.Export.Kind.STRUCT, List.of(), null, "");
        var create = new Model.Method("create", "create", false, ClassName.get("p", "G"), "",
            List.of(), List.of(new Model.Param("raw", false, t("string"), "")),
            List.of(new Model.Return(t("Widget"), "")));

        String out = new GlobalDeclEmitter(Map.of()).emit(List.of(global("UI", List.of(widget), List.of(create))));
        assertEquals("""
            -- Generated by lua-slopgen. DO NOT EDIT.
            
            declare class Widget
            \tname: string
            \tfunction tick(self, dt: number): ()
            \tfunction __tostring(self): string
            end
            
            declare UI: {
            \tcreate: (raw: string) -> Widget,
            }
            """, out);
    }

    @Test
    void superClassDeclaredBeforeSubclass() {
        var base = new Model.Export(ClassName.get("p", "Base"), "Base", null, false,
            List.of(), List.of(), List.of(), List.of(), 1, false,
            Model.Export.Kind.STRUCT, List.of(), null, "");
        var sub = new Model.Export(ClassName.get("p", "Sub"), "Sub", ClassName.get("p", "Base"),
            true, List.of(), List.of(), List.of(), List.of(), 2, false,
            Model.Export.Kind.STRUCT, List.of(), null, "");
        var refs = Map.of(
            "p.Base", new LibraryModuleEmitter.ExportRef("G", "Base"),
            "p.Sub", new LibraryModuleEmitter.ExportRef("G", "Sub"));

        // Source order puts Sub first to prove the topo sort reorders it after Base.
        String out = new GlobalDeclEmitter(refs).emit(List.of(global("G", List.of(sub, base), List.of())));
        assertTrue(out.indexOf("declare class Base end") < out.indexOf("declare class Sub extends Base end"), out);
    }

    @Test
    void requireScopeReferenceFailsHard() {
        var ex = new Model.Export(
            ClassName.get("p", "Bad"), "Bad", null, false, List.of(),
            List.of(new Model.Property("x",
                new Model.Accessor("g", ClassName.get("p", "Bad"), "", null,
                    new LuauType.Named("@mapmaker/world", "World", List.of())), null)),
            List.of(), List.of(), 1, false, Model.Export.Kind.STRUCT, List.of(), null, "");

        var ex2 = assertThrows(GlobalDeclEmitter.UnrepresentableGlobalException.class,
            () -> new GlobalDeclEmitter(Map.of()).emit(List.of(global("G", List.of(ex), List.of()))));
        assertTrue(ex2.getMessage().contains("@mapmaker/world.World"), ex2.getMessage());
        assertTrue(ex2.getMessage().contains("'G'"), ex2.getMessage());
    }

    @Test
    void shortFormGlobalReferenceRendersBare() {
        // `runtime.Hot` from inside a global lib is an ambient class — bare `Hot`, no failure.
        var ex = new Model.Export(
            ClassName.get("p", "R"), "R", null, false, List.of(),
            List.of(new Model.Property("hot",
                new Model.Accessor("g", ClassName.get("p", "R"), "", null,
                    new LuauType.Named("runtime", "Hot", List.of())), null)),
            List.of(), List.of(), 1, false, Model.Export.Kind.STRUCT, List.of(), null, "");
        String out = new GlobalDeclEmitter(Map.of()).emit(List.of(global("runtime", List.of(ex), List.of())));
        assertTrue(out.contains("hot: Hot"), out);
    }
}
