command.link.success=$CONFIRM<$light_gray>Your Discord account was <$white>successfully linked</$white>!</$light_gray>
command.link.already_linked=$INFO<$light_gray>Your Discord account is <$white>already linked</$white>!</$light_gray>
command.link.invalid_secret=$DENY<$light_gray>Your <$white>code was invalid</$white>! Please make sure you copied it correctly from Discord.</$light_gray>
command.link.expired_secret=$DENY<$light_gray>Your <$white>code expired</$white>, please try again.</$light_gray>
command.link.help=\
  $INFO<$white_gray>How to link your Discord account</$white_gray>\n\
  <$light_gray>1. Go to <$azure><click:open_url:'https://discord.hollowcube.net'>discord.hollowcube.net</click></$azure>.</$light_gray>\n\
  <$light_gray>2. Run the <$white>/link</$white> command.</$light_gray>

gui.2fa.qr.information.name=<$yellow>Information</$yellow>
gui.2fa.qr.information.lore=\
  <$light_gray>2FA adds an extra layer of security to your account.</$light_gray>\n\n\
  <$light_gray>1. Download a <$white>2FA app</$white> on your <$white>phone</$white>.</$light_gray>\n\
  <$light_gray>2. Open the app and <$white>scan the QR code</$white>.</$light_gray>\n\
  <$light_gray>4. Click confirm on the right.</$light_gray>

gui.2fa.qr.confirm.name=<$lime>Confirm</$lime>
gui.2fa.qr.confirm.lore=\
  <$light_gray>Click to confirm that you have scanned</$light_gray>\n\
  <$light_gray>the QR code and are ready to enter the 6-digit code</$light_gray>\n\
  <$light_gray>from your two-factor authentication app.</$light_gray>
