command.link.success=$CONFIRM<$light_gray>Your Minecraft account was <$white>successfully linked</$white> to your Discord account!</$light_gray>
command.link.already_linked=$INFO<$light_gray>Your Minecraft and Discord accounts are <$white>already linked</$white>!</$light_gray>
command.link.invalid_secret=$DENY<$light_gray>Your <$white>secret code was invalid</$white>! Please make sure you copied it correctly from Discord.</$light_gray>
command.link.expired_secret=$DENY<$light_gray>Your <$white>secret code expired</$white>! Please type /new-link again on our Discord to get a new one.</$light_gray>
command.link.internal_error=$DENY<$light_gray>An <$white>internal error</$white> occurred while <$white>linking your account</$white>! Please contact an <$red>Administrator</$red>!</$light_gray>
command.link.help=\
  $INFO<$white_gray>HOW TO LINK YOUR MINECRAFT AND DISCORD ACCOUNTS TOGETHER:</$white_gray>\n\
  <$light_gray>Go to <$azure>discord.hollowcube.net</$azure>. In any channel, run the <$white>/new-link</$white> command from the Hollow Cube Bot. It will give you a code. Copy it, and return to the server, then type <$white>/link</$white>, followed by the code you were given on Discord. Your accounts should now be linked, enjoy!</$light_gray>

gui.2fa.qr.information.name=<$yellow>Information</$yellow>
gui.2fa.qr.information.lore=\
  <$light_gray>2FA adds an extra layer of security to your account.</$light_gray>\n\n\
  <$light_gray>1. Download a <$white>2FA app</$white> on your <$white>phone</$white>.</$light_gray>\n\
  <$light_gray>2. Open the app and <$white>scan the QR code</$white>.</$light_gray>\n\
  <$light_gray>4. Click confirm on the right.</$light_gray>

gui.2fa.qr.confirm.name=<$lime>Confirm</$lime>
gui.2fa.qr.confirm.lore=\
  <$light_gray>Click to confirm that you have scanned</$light_gray>\n\
  <$light_gray>the QR code and are ready to enter the 6-digit code</$light_gray>\n\
  <$light_gray>from your two-factor authentication app.</$light_gray>