announcement.test1=<#3895FF><bold>Hollow Cube</bold></#3895FF> <#696969>|</#696969> <#CCCCCC>This is a test announcement. #1</#CCCCCC>
announcement.test2=<#3895FF><bold>Hollow Cube</bold></#3895FF> <#696969>|</#696969> <#CCCCCC>This is a test announcement. #2</#CCCCCC>
announcement.test3=<#3895FF><bold>Hollow Cube</bold></#3895FF> <#696969>|</#696969> <#CCCCCC>This is a test announcement. #3</#CCCCCC>
announcement.test4=<#3895FF><bold>Hollow Cube</bold></#3895FF> <#696969>|</#696969> <#CCCCCC>This is a test announcement. #4</#CCCCCC>
announcement.filter.type=You should only see this if you are in a map
announcement.filter.type_and_state=You should only see this if you are in a map and editing
