#
# GLOBAL ANNOUNCEMENTS
#

announcement.global.omega_parkour=$MEGAPHONE\
  <$white_gray>Did you ever build on Omega Parkour or Tapple's 1.8 Map Maker? You can view your works with <$white>/map legacy list</$white> and import them to an empty map slot.</$white_gray>

announcement.global.lobby=$MEGAPHONE\
  <$white_gray>There's more than meets the eye in the lobby: interactive elements, hidden references, and more. So, what are you waiting for? Go explore!</$white_gray>

announcement.global.find=$MEGAPHONE\
  <$white_gray>Interested in what someone is doing? Simple, <$white>/find</$white> them!</$white_gray>

announcement.global.bugs_and_suggestions=$MEGAPHONE\
  <$white_gray>Found a <$white>bug</$white>? Have a <$white>suggestion</$white> for the server? Share it with us in our <$white>/discord!</$white></$white_gray>

announcement.global.cosmetics=$MEGAPHONE\
  <$white_gray>Want to support the server? Consider buying our donor rank <$gold>Hypercube</$gold>, available in our <$white>/store</$white>!</$white_gray>

announcement.global.map_list=$MEGAPHONE\
  <$white_gray>Want to see someone's published maps? Use <$white>/map list <player></$white>!</$white_gray>

announcement.global.map_history=$MEGAPHONE\
  <$white_gray>Want to see your recently played maps? Use <$white>/map history</$white>!</$white_gray>

announcement.global.staff=$MEGAPHONE\
  <$white_gray>Have a question or need something from staff? Look for players with a shield, wrench, or art palette icon in front of their names!</$white_gray>

announcement.global.axiom=TODO
announcement.global.actions=TODO
announcement.global.settings=TODO
announcement.global.friends=TODO
announcement.global.blocks=TODO

announcement.global.notifications=$MEGAPHONE\
  <$white_gray>Wondering if you missed anything when you were offline? Check friend requests and such with <$white>/notifications</$white>!</$white_gray>
# TODO add after notifications are released

announcement.global.emojis=$MEGAPHONE\
  <$white_gray>Did you know we have <$white>/emojis</$white>? You can use them in chat and even on signs when building!</$white_gray>

announcement.global.chat_channels=$MEGAPHONE\
  <$white_gray>Want to chat only in the map you're in? Use <$white>/chat local</$white> to change chat channels or type <$white>/lc <message></$white> to send a singular message in local chat!</$white_gray>

announcement.global.flyspeed=$MEGAPHONE\
  <$white_gray>Did you know? You can change your <$white>/flyspeed</$white> while spectating or building!</$white_gray>

announcement.global.rules=$MEGAPHONE\
  <$white_gray>You're only allowed to upload content that is yours! Make sure to read our /rules.</$white_gray>
# TODO make this better

announcement.global.help=$MEGAPHONE\
 <$white_gray>Unsure of all the commands you can use and what they do? Use <$white>/help</$white>! There will be different options, too, depending on if you're playing or building.</$white_gray>

announcement.global.tp=$MEGAPHONE\
  <$white_gray>Did you know? You <$white>/teleport</$white> to people while <$white>spectating</$white> or <$white>building</$white>.</$white_gray>

#
# PLAYING ANNOUNCEMENTS
#

announcement.play.leaderboards=$MEGAPHONE\
  <$white_gray>Want to know the fastest times in a parkour map? Use <$white>/toptimes</$white>, or <$white>/tt</$white> for short.</$white_gray>

announcement.play.spectator_mode=$MEGAPHONE\
  <$white_gray>If you ever want to fly around and practice jumps in a parkour map, enter Spectator Mode via the TV item in your hotbar!</$white_gray>

announcement.play.savestate=$MEGAPHONE\
  <$white_gray>If you ever have to go, don't worry! Your progress is saved on every map you play, so you can always come back later and continue from where you left off.</$white_gray>

announcement.play.showheight=$MEGAPHONE\
  <$white_gray>Want to see the reset height of a map? Use <$white>/showheight</$white> when playing! Falling below the red line will return you to your last checkpoint.</$white_gray>

announcement.play.hide=$MEGAPHONE\
  <$white_gray>Tired of other people blocking your view while playing? Use <$white>/hide</$white>!</$white_gray>

announcement.play.map_hyperlink=$MEGAPHONE\
  <$white_gray>Did you know? You can <$white>hyperlink</$white> the <$white>map</$white> you're <$white>playing</$white> by typing <$white>[map]</$white> in chat!</$white_gray>

announcement.play.versioned_maps=$MEGAPHONE\
  <$white_gray>Whatever version a map is published on, you can only play it on that version or later! For the <$white>best experience</$white>, and to be able to <$white>play all maps</$white>, make sure to use the <$white>latest Minecraft version</$white>!</$white_gray>

#
# BUILDING ANNOUNCEMENTS
#

announcement.build.map_tags=$MEGAPHONE\
  <$white_gray>Consider adding Map Tags to your works! They highlight interesting visual and/or gameplay elements and make what you publish more discoverable.</$white_gray>

announcement.build.invite=$MEGAPHONE\
  <$white_gray>Want help building your map? A player can <$white>/request</$white> to join you, or you can <$white>/invite</$white> them. \
  However, they will be kicked out when you leave your map. As the owner of the map, you can also <$white>/remove</$white> them.</$white_gray>

announcement.build.reverify=$MEGAPHONE\
  <$white_gray>Before verifying your parkour map, make sure your build is finalized! If you have to edit it after verifying, your verification progress will be reset.</$white_gray>

announcement.build.give=$MEGAPHONE\
  <$white_gray>Lost your Builder Menu? Need a specific block? Use <$white>/give</$white>!</$white_gray>

announcement.build.test=$MEGAPHONE\
  <$white_gray>It can be hard to try out your parkour in creative mode, so enter <$white>/test</$white> mode for a more authentic experience.</$white_gray>

announcement.build.setspawn=$MEGAPHONE\
  <$white_gray>Use <$white>/setspawn</$white> to choose where players spawn in your map.</$white_gray>

announcement.build.setspawn.actions=$MEGAPHONE\
  <$white_gray>Did you know? You can right-click the spawn point NPC in your map to configure what happens to players when they join your map!</$white_gray>
# TODO make better

announcement.build.schematic=$MEGAPHONE\
  <$white_gray>Did you know? You can add existing builds to your maps by using <$white>/schematic upload</$white> in our <$white><click:open_url:https://discord.hollowcube.net>/discord</click></$white>.</$white_gray>

announcement.build.banner=$MEGAPHONE\
  <$white_gray>Want a specific banner pattern? Use <$white>/banner</$white> while <$white>building</$white>!</$white_gray>

announcement.build.hdb=$MEGAPHONE\
  <$white_gray>Want to get a specific player head for decoration? Use <$white>/skull</$white> or browse <$white>/hdb</$white> while building!</$white_gray>

#
# STORE ANNOUNCEMENTS
#

# 0: display name of person who bought it, 1: count
store.broadcast.hypercube=$MEGAPHONE<0> <$light_gray>bought <$gold>Hypercube</$gold>! Thanks for supporting the server!</$light_gray>
store.broadcast.cubits=$MEGAPHONE<0> <$light_gray>bought <$pink>Cubits</$pink>! Thanks for supporting the server!</$light_gray>