#
# GLOBAL ANNOUNCEMENTS
#

announcement.global.omega_parkour=$MEGAPHONE\
  <$white_gray>Did you ever build on Omega Parkour or Tapple's 1.8 Map Maker? You can view your works with <$white>/map legacy list</$white> and import them to an empty map slot.</$white_gray>

announcement.global.lobby=$MEGAPHONE\
  <$white_gray>There's more than meets the eye in the lobby: interactive elements, hidden references, and more. So, what are you waiting for? Go explore!</$white_gray>

announcement.global.find=$MEGAPHONE\
  <$white_gray>Interested in what someone is doing? Simple, <$white>/find</$white> them!</$white_gray>

announcement.global.bugs_and_suggestions=$MEGAPHONE\
  <$white_gray>Found a <$white>bug</$white>? Have a <$white>suggestion</$white> for the server? Share it with us in our <$white>/discord!</$white></$white_gray>

announcement.global.cosmetics=$MEGAPHONE\
  <$white_gray>Want to support our server? Consider buying some of our <$white>/cosmetics</$white>!</$white_gray>

#
# PLAYING ANNOUNCEMENTS
#

announcement.play.leaderboards=$MEGAPHONE\
  <$white_gray>Want to know the fastest times in a parkour map? Use <$white>/toptimes</$white>, or <$white>/tt</$white> for short.</$white_gray>

announcement.play.spectator_mode=$MEGAPHONE\
  <$white_gray>If you ever want to fly around and practice jumps in a parkour map, enter Spectator Mode via the TV item in your hotbar!</$white_gray>

announcement.play.savestate=$MEGAPHONE\
  <$white_gray>If you ever have to go, don't worry! Your progress is saved on every map you play, so you can always come back later and continue from where you left off.</$white_gray>

#
# BUILDING ANNOUNCEMENTS
#

announcement.build.map_tags=$MEGAPHONE\
  <$white_gray>Consider adding Map Tags to your works! They highlight interesting visual and/or gameplay elements and make what you publish more discoverable.</$white_gray>

announcement.build.invite=$MEGAPHONE\
  <$white_gray>Want help building your map? A player can <$white>/request</$white> to join you, or you can <$white>/invite</$white> them. \
  However, they will be kicked out when you leave your map. As the owner of the map, you can also <$white>/remove</$white> them.</$white_gray>

announcement.build.reverify=$MEGAPHONE\
  <$white_gray>Before verifying your parkour map, make sure your build is finalized! If you have to edit it after verifying, your verification progress will be reset.</$white_gray>

announcement.build.give=$MEGAPHONE\
  <$white_gray>Lost your Builder Menu? Need a specific block? Use <$white>/give</$white>!</$white_gray>

announcement.build.test=$MEGAPHONE\
  <$white_gray>It can be hard to try out your parkour in creative mode, so enter <$white>/test</$white> mode for a more authentic experience.</$white_gray>

announcement.build.setspawn=$MEGAPHONE\
  <$white_gray>Use <$white>/setspawn</$white> to choose where players spawn in your map.</$white_gray>

announcement.build.schematic=$MEGAPHONE\
  <$white_gray>Did you know? You can add existing builds to your maps by using <$white>/schematic upload</$white> in our <$white><click:open_url:https://discord.hollowcube.net>/discord</click></$white>.</$white_gray>
