#
# LEGENDARY MATERIALS
#

item.mapmaker.nightmare_fuel.name=<$gold>Nightmare Fuel</$gold>
item.mapmaker.nightmare_fuel.lore=\
  <$light_gray>Only death-defying challenges can give form to this living nightmare.</$light_gray>
item.mapmaker.stardust.name=<$gold>Stardust</$gold>
item.mapmaker.stardust.lore=\
  <$light_gray>A fragment of the cosmos, guided to the best creations. It radiates an ethereal glow.</$light_gray>
item.mapmaker.dragon_scale.name=<$gold>Dragon Scale</$gold>
item.mapmaker.dragon_scale.lore=\
  <$light_gray>TODO</$light_gray>

#
# EPIC MATERIALS
#

item.mapmaker.gold_chunk.name=<$purple>Gold Chunk</$purple>
item.mapmaker.gold_chunk.lore=\
  <$light_gray>TODO</$light_gray>
item.mapmaker.infernal_flame.name=<$purple>Infernal Flame</$purple>
item.mapmaker.infernal_flame.lore=\
  <$light_gray>A bright flame, signifying the conquering of many challenges.</$light_gray>
item.mapmaker.firework_dust.name=<$purple>Firework Dust</$purple>
item.mapmaker.firework_dust.lore=\
  <$light_gray>TODO</$light_gray>

#
# RARE MATERIALS
#

item.mapmaker.sugar_cube.name=<$azure>Sugar Cube</$azure>
item.mapmaker.sugar_cube.lore=\
  <$light_gray>A perfectly sweet cube of sugar. Just don't eat it...</$light_gray>
item.mapmaker.flower_petal.name=<$azure>Flower Petal</$azure>
item.mapmaker.flower_petal.lore=\
  <$light_gray>TODO</$light_gray>
item.mapmaker.controller.name=<$azure>Controller</$azure>
item.mapmaker.controller.lore=\
  <$light_gray>TODO</$light_gray>
item.mapmaker.bone_fragment.name=<$azure>Bone Fragment</$azure>
item.mapmaker.bone_fragment.lore=\
  <$light_gray>A jagged piece of bone, broken off from a larger part.</$light_gray>

#
# NORMAL MATERIALS
#

item.mapmaker.string.name=<$white>String</$white>
item.mapmaker.string.lore=\
  <$light_gray>A tightly wound spool of string.</$light_gray>
item.mapmaker.metal.name=<$white>Metal</$white>
item.mapmaker.metal.lore=\
  <$light_gray>A gray ore, hard and unrefined.</$light_gray>
item.mapmaker.goo.name=<$white>Goo</$white>
item.mapmaker.goo.lore=\
  <$light_gray>TODO</$light_gray>
item.mapmaker.gem.name=<$white>Gem</$white>
item.mapmaker.gem.lore=\
  <$light_gray>TODO</$light_gray>
item.mapmaker.cloth.name=<$white>Cloth</$white>
item.mapmaker.cloth.lore=\
  <$light_gray>A roll of soft, woven fabric.</$light_gray>
item.mapmaker.bricks.name=<$white>Bricks</$white>
item.mapmaker.bricks.lore=\
  <$light_gray>TODO</$light_gray>