#
# LEGENDARY MATERIALS
#

item.mapmaker.nightmare_fuel.name=<$gold>Nightmare Fuel</$gold>
item.mapmaker.nightmare_fuel.lore=\
  <$light_gray>Only death-defying challenges can</$light_gray>\n\
  <$light_gray>give form to this living nightmare.</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating a</$white_gray>\n\
  <$white_gray>Nightmare difficulty parkour map.</$white_gray>
item.mapmaker.stardust.name=<$gold>Stardust</$gold>
item.mapmaker.stardust.lore=\
  <$light_gray>A fragment of the cosmos, guided to the best</$light_gray>\n\
  <$light_gray>creations. It radiates an ethereal glow.</$light_gray>\n\n\
  <$white_gray>Obtained by getting a staff member to rate</$white_gray>\n\
  <$white_gray>your map Outstanding or Masterpiece.</$white_gray>
item.mapmaker.dragon_scale.name=<$gold>Dragon Scale</$gold>
item.mapmaker.dragon_scale.lore=\
  <$light_gray><italic>???</italic></$light_gray>\n\n\
  <$white_gray>Not obtainable in the beta.</$white_gray>

#
# EPIC MATERIALS
#

item.mapmaker.gold_chunk.name=<$purple>Gold Chunk</$purple>
item.mapmaker.gold_chunk.lore=\
  <$light_gray><italic>???</italic></$light_gray>\n\n\
  <$white_gray>Not obtainable in the beta.</$white_gray>
item.mapmaker.infernal_flame.name=<$purple>Infernal Flame</$purple>
item.mapmaker.infernal_flame.lore=\
  <$light_gray>A bright flame, signifying the</$light_gray>\n\
  <$light_gray>conquering of many challenges.</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating</$white_gray>\n\
  <$white_gray>an Expert difficulty parkour map.</$white_gray>
item.mapmaker.firework_dust.name=<$purple>Firework Dust</$purple>
item.mapmaker.firework_dust.lore=\
  <$light_gray><italic>???</italic></$light_gray>\n\n\
  <$white_gray>Not obtainable in the beta.</$white_gray>

#
# RARE MATERIALS
#

item.mapmaker.sugar_cube.name=<$azure>Sugar Cube</$azure>
item.mapmaker.sugar_cube.lore=\
  <$light_gray>A perfectly sweet cube of sugar.</$light_gray>\n\
  <$light_gray>Just don't eat it...</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating</$white_gray>\n\
  <$white_gray>an Only Sprint parkour map.</$white_gray>
item.mapmaker.flower_petal.name=<$azure>Flower Petal</$azure>
item.mapmaker.flower_petal.lore=\
  <$light_gray>A delicate and vibrant piece of flora.</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating</$white_gray>\n\
  <$white_gray>an Easy difficulty parkour map.</$white_gray>
item.mapmaker.controller.name=<$azure>Controller</$azure>
item.mapmaker.controller.lore=\
  <$light_gray><italic>???</italic></$light_gray>\n\n\
  <$white_gray>Not obtainable in the beta.</$white_gray>
item.mapmaker.bone_fragment.name=<$azure>Bone Fragment</$azure>
item.mapmaker.bone_fragment.lore=\
  <$light_gray>A jagged piece of bone, broken</$light_gray>\n\
  <$light_gray>off from a larger part.</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating</$white_gray>\n\
  <$white_gray>a Dropper parkour map.</$white_gray>

#
# NORMAL MATERIALS
#

item.mapmaker.string.name=<$titanium>String</$titanium>
item.mapmaker.string.lore=\
  <$light_gray>A tightly wound spool of string.</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating any map.</$white_gray>
item.mapmaker.metal.name=<$titanium>Metal</$titanium>
item.mapmaker.metal.lore=\
  <$light_gray>A gray ore, hard and unrefined.</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating any map.</$white_gray>
item.mapmaker.goo.name=<$titanium>Goo</$titanium>
item.mapmaker.goo.lore=\
  <$light_gray>A slimy substance with sticky properties.</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating any map.</$white_gray>
item.mapmaker.gem.name=<$titanium>Gem</$titanium>
item.mapmaker.gem.lore=\
  <$light_gray>A small, colorful crystal that refracts light.</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating any map.</$white_gray>
item.mapmaker.cloth.name=<$titanium>Cloth</$titanium>
item.mapmaker.cloth.lore=\
  <$light_gray>A roll of soft, woven fabric.</$light_gray>\n\n\
  <$white_gray>Obtained sometimes from beating any map.</$white_gray>
item.mapmaker.bricks.name=<$titanium>Bricks</$titanium>
item.mapmaker.bricks.lore=\
  <$light_gray><italic>???</italic></$light_gray>\n\n\
  <$white_gray>Not obtainable in the beta.</$white_gray>