# Invitee Kicked From Owner Leaving
map.kicked=$DENY<$light_gray>The owner of the map left, so you were <$white>kicked</$white> out!</$light_gray>

# Build World Loaded
build.world.load.first=$CONFIRM<$light_gray>Now <$white>editing</$white> your world <$white><0></$white>.</$light_gray>

# Build World Saved
build.world.save.success=$INFO<$light_gray><$white>Saved</$white> your world.</$light_gray>

# Build World Save Failure
build.world.save.failure=$DENY<$light_gray>Your world <$white>failed to save</$white> and is in an <$white>inconsistent state</$white>! Any further changes <$white>might not be saved</$white>. If this happens again, leave and rejoin your map. If the issue still persists after that, contact an <$red>Administrator</$red>.</$light_gray>

# Enter Finish Plate/Region In Testing Mode
testing_mode.finish=$INFO<$light_gray>Now exiting testing mode. Finished with <$white><0></$white>.</$light_gray>

#
# Value Checks
#

# Reset Height
# 0: Entered number in command argument
# 1: Checkpoint plate's Y level coordinate
create_maps.checkpoint.reset_height.too_high=$DENY<$light_gray>The <$white>reset height</$white> you have entered (<$white_gray><0></$white_gray>) can't be higher than the checkpoint plate's (or teleport location's) <$white>Y level</$white> (<$white_gray><1></$white_gray>)!</$light_gray>
create_maps.checkpoint.reset_height.too_low=$DENY<$light_gray>The <$white>reset height</$white> you have entered can't be below <$white>-64</$white>!</$light_gray>
create_maps.checkpoint.reset_height.nan=$DENY<$light_gray>The <$white>reset height</$white> you have entered must be a number!</$light_gray>

# Teleport
create_maps.checkpoint.teleport.too_low=$DENY<$light_gray>You cannot teleport the player below the reset height!</$light_gray>

# Progress Index
create_maps.checkpoint.progress_index.nan=$DENY<$light_gray>The <$white>progress index</$white> you have entered must be a number!</$light_gray>

#
# Commands
#

# Clear Inventory
command.clear_inventory.success=$INFO<$light_gray>Your <$white>inventory</$white> has been <$white>cleared</$white>.</$light_gray>

# Fly
command.fly.enabled=$INFO<$light_gray>Your <$white>flight</$white> has been toggled <$white>on</$white>.</$light_gray>
command.fly.disabled=$INFO<$light_gray>Your <$white>flight</$white> has been toggled <$white>off</$white>.</$light_gray>

# Flyspeed
# 0: The int argument
command.flyspeed.changed=$INFO<$light_gray>Your <$white>flight speed</$white> has been changed to <$white><0></$white>.</$light_gray>

# Give
command.give.not_enough_space=$WARNING<$light_gray>You don't have enough <$white>inventory space</$white>!</$light_gray>
command.give.success=$INFO<$light_gray>Successfully gave you a <$white><0></$white> item!</$light_gray>

# Set Spawn
# 0, 1, 2, 3, 4 = x, y, z, pitch, yaw
command.set_spawn.success=$CONFIRM<$light_gray>Set map spawn to X: <$white><0></$white>, Y: <$white><1></$white>, Z: <$white><2></$white>, Yaw: <$white><3></$white>, Pitch: <$white><4></$white>.</$light_gray>

# Schematics
map.schematic.upload.success=$CONFIRM<$light_gray>Successfully <$white>uploaded your schematic!</$light_gray>

# Teleport
command.set_precise_coords.begin=$INFO<$light_gray>Started editing teleport coordinates, use <$white>/setprecisecoords</$white> (<$white>/spc</$white>) to update the coordinates.</$light_gray>
command.set_precise_coords.no_target=$DENY<$light_gray>You must begin editing precise coordinates from a checkpoint or status plate gui.</$light_gray>
command.set_precise_coords.success=$CONFIRM<$light_gray>Set precise coordinates to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>, Pitch: <$white><3></$white>, Yaw: <$white><4></$white>.</$light_gray>

# Jumpto
command.jumpto.no_space=$DENY<$light_gray>There is <$white>not enough space</$white> in front of you to use this command!</$light_gray>
command.jumpto.too_far=$DENY<$light_gray>There is <$white>nothing within 100 blocks</$white> to jump to!</$light_gray>
command.jumpto.success=$CONFIRM<$light_gray>Jumped to your <$white>cursor</$white>!</$light_gray>

# Up
command.up.success=$CONFIRM<$light_gray>You have been moved to <$white>Y <0></$white>!</$light_gray>

#
# Static
#

# Debug Stick
item.minecraft.debug_stick.name=<light_purple>Debug Stick</light_purple>

# Spawn Point Title
map.spawn_point.title=$RMB <$white_gray>Right Click to Edit</$white_gray>