map.kicked=$DENY<$light_gray>The owner of the map left, so you were <$white>kicked</$white> out!</$light_gray>
map.closed=$DENY<$light_gray>The map was closed, so you were <$white>kicked</$white> out!</$light_gray>
# Edit Slot Information
# 0: Map name
create_maps.verify=$CONFIRM <$light_gray>You have <$white>verified</$white> your map <$white><0></$white>. You may now <$white>publish</$white> it!</$light_gray>
# 1: Map ID
create_maps.publish=$CONFIRM <$light_gray>Your map <$white><0> was published</$white> with an ID of <$white><1></$white>.</$light_gray>
# 0: Old map name
# 1: New map name
create_maps.change_name=$INFO<$light_gray><$white>Renamed</$white> your map from <0> to <1>.</$light_gray>
# 0: Old display item
# 1: New display item
create_maps.set_display_item=$INFO<$light_gray>Changed the display item of your map from <0> to <1>.</$light_gray>
# 0: Map tag
# 1: Map name
# TODO most of these don't even need to exist tbh, gotta figure out which
create_maps.add_tag=Added the <0> tag to your map <1>.
create_maps.remove_tag=Removed the <0> tag to your map <1>.
create_maps.set_tags=You need to set at least 1 tag for your map before you can publish it!
create_maps.set_difficulty=You need to set the difficulty of your map before you can publish it!
# 0: Map name
# 1: Initial slot
# 2: Target slot
create_maps.copy=Copied your map <0> from slot number <1> to slot number <2>.
create_maps.move=Moved your map <0> from slot number <1> to slot number <2>.
create_maps.delete=Deleted your map <0>. If this was an accident contact a staff member within 7 days or else your map will be permanently deleted!
# 0: Owner of the map in question
create_maps.only_owner.settings=Only <0>, the map owner, can edit map settings!
create_maps.only_owner.display_item=Only <0>, the map owner, can edit the map display item!
create_maps.only_owner.map_name=Only <0>, the map owner, can edit the map name!
create_maps.cannot_publish_while_editing=Cannot publish the world while its being edited!
# 0: Map setting
# 1: On or off
builder_menu.map_setting.toggle=Map setting <0> toggled <1>!
# Future ones to replace the above with?
# Pasted your selected region of <0> blocks.
# Pasted your selected region of <0> blocks without air.
# Checkpoints, Finish Plates, and Executors
# 0: Entered number in command argument
# 1: Checkpoint plate's Y level coordinate
create_maps.checkpoint.reset_height.too_high=The reset height you have entered (<0>) can't be higher than the checkpoint plate's (or teleport location's) Y level (<1>)!
create_maps.checkpoint.reset_height.too_low=The reset height you have entered is below the world!
create_maps.checkpoint.teleport.too_low=You cannot teleport the player below the reset height.

# 0: Entered number in command argument
# 1: Lowest possible enterable value
# 2: Highest possible enterable value
create_maps.checkpoint.reset_height.not_in_range=The number you have entered (<0>) must be between <1> and <2>.
# 0: Maximum amount of checkpoints allowed
create_maps.checkpoint.max_allowed=You have reached the maximum amount of checkpoints allowed on your map (<0>)! If you want, you can Click Here to buy more.
#//TODO make the click here work
# 0: The XYZ coordinates where the plate was placed
create_maps.checkpoint.placed=A checkpoint plate has been placed at <0>.
create_maps.finish.placed=A finish plate has been placed at <0>.
create_maps.checkpoint.removed=The checkpoint plate at <0> has been removed.
create_maps.finish.removed=The finish plate at <0> has been removed.
#//TODO add potion effects



# Map Status
# 0, 1, 2, 3, 4 = x, y, z, pitch, yaw
command.set_spawn.success=$CONFIRM<$light_gray>Set map spawn to X: <$white><0></$white>, Y: <$white><1></$white>, Z: <$white><2></$white>, Pitch: <$white><3></$white>, Yaw: <$white><4></$white>.</$light_gray>
map.schematic.upload.success=$CONFIRM<$light_gray>Successfully <$white>uploaded your schematic!</$light_gray>
command.map.create.no_slots_available=$DENY<$light_gray>You have <$white>no slots</$white> available!</$light_gray>
# 0: The map slot
command.map.create.slot_not_available=$DENY<$light_gray>Slot <$white><0></$white> is already full.</$light_gray>
command.map.alter.success=changed map thing blah fixme
command.map.alter.no_change=changed nothing map thing blah fixme
command.map.delete.success=$CONFIRM<$light_gray>You have <$white>PERMANENTLY deleted</$white> your map. I hope it wasn't on accident...</$light_gray>
command.map.delete.failure=$DENY<$light_gray><$white>Couldn't delete</$white> your map! If this issue persists, please contact an <$red>Administrator</$red>.</$light_gray>
command.map.info.not_found=idk what this is lol (fix me)
# Building Commands
command.clear_inventory.success=$INFO<$light_gray>Your <$white>inventory</$white> has been <$white>cleared</$white>.</$light_gray>
command.fly.enabled=$INFO<$light_gray>Your <$white>flight</$white> has been toggled <$white>on</$white>.</$light_gray>
command.fly.disabled=$INFO<$light_gray>Your <$white>flight</$white> has been toggled <$white>off</$white>.</$light_gray>
# 0: The int argument
command.flyspeed.changed=$INFO<$light_gray>Your <$white>flight speed</$white> has been changed to <$white><0></$white>.</$light_gray>
# 0: The item being given
command.give.unknown_item=$DENY<$light_gray><0> is not a <$white>valid item</$white>!</$light_gray>
command.give.not_enough_space=$WARNING<$light_gray>You don't have enough <$white>inventory space</$white>!</$light_gray>
command.give.success=$INFO<$light_gray>Successfully gave you a <$white><0></$white> item!</$light_gray>
command.help.unknown_command=$DENY<$light_gray>Unknown command <$white><0></$white>.</$light_gray>
command.test.gameplay_only=$DENY<$light_gray>Testing mode can only be used in maps with <$white>gameplay</$white>! Building map types are not allowed.</$light_gray>

build.world.save.success=$INFO<$light_gray><$white>Saved</$white> your world.</$light_gray>
build.world.save.failure=$DENY<$light_gray>Your world <$white>failed to save</$white> and is in an <$white>inconsistent state</$white>! Any changes made <$white>might not be saved</$white>. If this happens again, leave and rejoin your map. If the issue still persists after that, contact an <$red>Administrator</$red>.</$light_gray>
build.world.load.first=$CONFIRM<$light_gray>Now <$white>editing</$white> your world <$white><0></$white>.</$light_gray>

item.minecraft.debug_stick.name=<light_purple>Debug Stick</light_purple>
testing_mode.finish=$INFO<$light_gray>Now exiting testing mode.</$light_gray>

map.spawn_point.not_parkour=$DENY<$light_gray>You can only <$white>edit spawn settings</$white> on <$white>parkour maps</$white>. If you want to move the spawn location, use /setspawn.</$light_gray>

command.set_precise_coords.begin=$INFO<$light_gray>Started editing teleport coordinates, use <$white>/setprecisecoords</$white> (<$white>/spc</$white>) to update the coordinates.</$light_gray>
command.set_precise_coords.no_target=$DENY<$light_gray>You must begin editing precise coordinates from a checkpoint or status plate gui.
command.set_precise_coords.success=$CONFIRM<$light_gray>Set precise coordinates to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>, Pitch: <$white><3></$white>, Yaw: <$white><4></$white>.</$light_gray>
command.jumpto.no_space=$DENY<$light_gray>There is not enough space in front of you to use this command!</$light_gray>
command.jumpto.success=$CONFIRM<$light_gray>You jumped to your target block!</$light_gray>