# Constant
mapmaker.welcome_message=<#696969>[<#3490C9>?</#3490C9></#696969>] <#B0B0B0>Welcome to</#B0B0B0> <#3895FF>Map Maker</#3895FF><#B0B0B0>!</#B0B0B0>
command.discord=Discord: TBD
command.store=Store: §bhttps://store.hollowcube.net
command.kyroh=Praise the lord!

# Generic (reused between many commands)

generic.player_only=<$dark_gray>[<$light_gray>?</$light_gray>]</$dark_gray> <$light_gray>This command is only executable as a player!</$light_gray>
generic.no_permission=<#696969>[<#FF2D2D>?</#FF2D2D></#696969>] <#B0B0B0>You don't have permission for that command!</#B0B0B0>
generic.sanity_check_failed=<#696969>[<#FF2D2D>?</#FF2D2D></#696969>] <#B0B0B0>An unknown error occurred, please try again later! If this issue persists, please contact an</#B0B0B0> <#FF2D2D>Administrator</#FF2D2D> or <#AC4BFF>Developer</#AC4BFF><#B0B0B0>.</#B0B0B0>
# 0: Player name
generic.player_offline=<#696969>[<#FF2D2D>?</#FF2D2D></#696969>] <#B0B0B0>{0} is not online!
# 0: Error string
generic.unknown_error=<#696969>[<#FF2D2D>?</#FF2D2D></#696969>] <#B0B0B0>An unknown error occurred, please try again later! If this issue persists, please contact an</#B0B0B0> <#FF2D2D>Administrator</#FF2D2D> or <#AC4BFF>Developer</#AC4BFF><#B0B0B0>.</#B0B0B0>
generic.disabled_command=This command is disabled for now.
# 0: Proper command argument syntax
generic.wrong_syntax=Wrong syntax! Use {0}
# 0: Entered number in command argument
# 1: Lowest possible enterable value
# 2: Highest possible enterable value
generic.number.not_in_range=The number you have entered ({0}) must be between {1} and {2}!
generic.number.only_int=You can only enter numbers!
# 0: Player's ping
generic.command.ping=Your ping is {0}ms.

# Join/leave

# 0: Player name
chat.player.join=<$dark_gray>[</$dark_gray><$lime><bold>+</bold><$lime><$dark_gray>]</$dark_gray> <$light_gray>{0}</$light_gray>
chat.player.leave=<$dark_gray>[</$dark_gray><$red><bold>-</bold><$red><$dark_gray>]</$dark_gray> <$light_gray>{0}</$light_gray>

# Chat-Related

# 0: The player you are sending a message to or a receiving a message from
# 1: The message being sent
chat.msg.send=You -> {0} » {1}
chat.msg.receive={0} -> You » {1}
chat.msg.no_text=You need to type something in your message!
chat.msg.no_reply=You do not have anyone to reply to!
chat.msg.cant_message_yourself=You cannot message yourself!
chat.msg.already_in_channel.staff=You are already talking in staff chat!
chat.msg.channel_changed.staff=You are now talking in staff chat.
chat.msg.channel_wrong_syntax=That channel doesn't exist!
# 0: The player sending a message in staff chat
chat.msg.channel_single_message.staff=[SC] {0} » {1}

# Enter Map (/enter or /e <MapID>)
# 0: The map ID the user is trying to enter a course with
command.enter_map.wrong_syntax=[?] The map ID {0} doesn't exist. Did you type it out wrong?

# Map Status Updates

map.status.new_checkpoint=[?] You have reached a new Checkpoint.
# 0: Map name
# 1: Savestate time
map.status.finish=[?] You finished the map {0} in {1}.
map.status.reset_confirmation=[?] Are you sure you want to restart this map? Right-click again within 2 seconds to confirm.
map.status.reset_confirmation.timed_out=[?] Reset confirmation timed out.
# 0: Map name
# 1: Report reason
map.status.reset_confirmation.affirm=[?] Successfully reset your progress on map {0}!
map.status.reported=[?] You reported the map {0} for {1}!
map.status.boosted=[?] You Boosted the map {0}!
play_maps.loading=We are still loading the world data! Please wait a few seconds.

# Build World Invites

# 0: The player invited
# 1: Map name
create_maps.your_invite.sent=[?] You invited {0} to help build for your map {1}.
create_maps.your_invite.accepted=[?] Your build invite to {0} for your map {1} was accepted.
create_maps.your_invite.timed_out=[?] Your build invite to {0} for your map {1} timed out.
create_maps.your_invite.denied=[?] Your build invite to {0} for your map {1} was denied.
create_maps.no_invite=You don't have a build invite from this player!

# 0: The player who sent the invite
# 1: Map slot name
create_maps.invite.sent=[?] {0} has invited you to help build on their map {1}. Click to accept!
create_maps.invite.accepted=[?] You accepted {0}'s build invite to their map {1}.
create_maps.invite.timed_out=[?] You didn't respond in time to {0}'s build invite for their map {1}.
create_maps.invite.denied=[?] You denied {0}'s build invite for their map {1}.
# 0: The player to check a build invite from
create_maps.invite.none=[?] You have no pending build invite from {0}!
create_maps.invite.expired=That request has expired!

# Edit Slot Information
# 0: Map name
# 1: Map ID
create_maps.verify=You have verified your map {0} with an ID of {1}. You may now publish it.
create_maps.publish=You have published your map {0} with an ID of {1}.
# 0: Old map name
# 1: Old map name
create_maps.change_name=Changed the name of your map from {0} to {1}.
# 0: Old display item
# 1: New display item
create_maps.set_display_item=Changed the display item of your map from {0} to {1}.
# 0: Map tag
# 1: Map name
create_maps.add_tag=Added the {0} tag to your map {1}.
create_maps.remove_tag=Removed the {0} tag to your map {1}.
create_maps.set_tags=You need to set at least 1 tag for your map before you can publish it!
create_maps.set_difficulty=You need to set the difficulty of your map before you can publish it!
# 0: Map name
# 1: Initial slot
# 2: Target slot
create_maps.copy=Copied your map {0} from slot number {1} to slot number {2}.
create_maps.move=Moved your map {0} from slot number {1} to slot number {2}.
create_maps.delete=Deleted your map {0}. If this was an accident contact a staff member within 7 days or else your map will be permanently deleted!
# 0: Owner of the map in question
create_maps.only_owner.settings=Only {0}, the map owner, can edit map settings!
create_maps.only_owner.display_item=Only {0}, the map owner, can edit the map display item!
create_maps.only_owner.map_name=Only {0}, the map owner, can edit the map name!
create_maps.cannot_publish_while_editing=Cannot publish the world while its being edited!

# Builder Menu
# 0: Map setting
# 1: On or off
builder_menu.map_setting.toggle=[?] Map setting {0} toggled {1}!

# Builder Utilities
#[?] Obtained a world edit wand. Left click to set position 1, right click to set position 2.
#[?] Set your selected region of {0} blocks to {1}.
#[?] Cut your selected region of {0} blocks.
#[?] Copied your selected region of {0} blocks.
#[?] Pasted your selected region of {0} blocks.
#[?] Pasted your selected region of {0} blocks without air.
#Undid your most recent world edit command.
#Redid your most recent world edit command.
#//TODO proper world edit messages

# Checkpoints, Finish Plates, and Executors
# 0: Entered number in command argument
# 1: Checkpoint plate's Y level coordinate
create_maps.checkpoint.reset_height.too_high=The reset height you have entered ({0}) can't be higher than the checkpoint plate's Y level ({1})!
# 0: Entered number in command argument
# 1: Lowest possible enterable value
# 2: Highest possible enterable value
create_maps.checkpoint.reset_height.not_in_range=The number you have entered ({0}) must be between {1} and {2}.
# 0: Maximum amount of checkpoints allowed
create_maps.checkpoint.max_allowed=You have reached the maximum amount of checkpoints allowed on your map ({0})! If you want, you can Click Here to buy more.
#//TODO make the click here work
# 0: The XYZ coordinates where the plate was placed
create_maps.checkpoint.placed=A checkpoint plate has been placed at {0}.
create_maps.finish.placed=A finish plate has been placed at {0}.
create_maps.checkpoint.removed=The checkpoint plate at {0} has been removed.
create_maps.finish.removed=The finish plate at {0} has been removed.
#//TODO add potion effects

# Moderation
# 0: The staff member that cleared the chat
command.moderation.clear_chat=The chat was cleared by {0}!
command.moderation.vanish_enabled=Vanish enabled. You are now hidden from all normal players.
command.moderation.vanish_disabled=Vanish disabled. You are now shown for all players again.

# Currency

# 0: Cubits purchase amount
currency.store.success=[?] Your store transaction of {0} Cubits has successfully been processed, enjoy!
# 0: The package purchased
# 1: Cubits purchase amount
currency.cubits.purchase.successful_transaction=[?] You successfully purchased {0} for {1} Cubits.
# 0: Cubits balance
# 1: Amount of missing Cubits need to purchase package
# 2: The package trying to be purchased
currency.cubits.purchase.insufficient_funds=[?] You only have {0} Cubits; you are short {1} Cubits to purchase {2}!



# OLD STUFF (will update/change soon) - Seth

# /map create
# 0: slot number
command.map.create.slot_in_use=[?] <red>Slot {0} is already in use.
# 0: name
command.map.create.name_in_use=[?] <red>Cannot create map named '{0}' because it is already in use.
# 0: slot number, 1: map name
command.map.create.success=<$dark_gray>[<$light_gray>?</$light_gray>]</$dark_gray> <$light_gray>Created new map in slot <$light_blue>{1}</$light_blue></$light_gray>. \
  <click:suggest_command:/map edit {0}><$lime>Click to Edit</$lime></click>

# /map publish
# 0: slot number
command.map.public.slot_not_in_use=[?] <red>Slot {0} is empty.
# 0: slot number
command.map.publish.success=[?] <white>Published map in slot <aqua>{0}</aqua>.

# /map admin

# /map admin list
# 0=player
command.map.admin.list.empty.player=[?] <red>No maps found for {0}</red>
command.map.admin.list.empty=[?] <red>No maps found for {0}</red>
# 0=player
command.map.admin.list.header.player=[?] <gold>Maps for {0}</gold>
command.map.admin.list.header=[?] <gold>All maps</gold>
# 0=map id, 1=map name
command.map.admin.list.entry=[?] <gold>{0}</gold> - <aqua>{1}</aqua>

# /map admin info
# 0=id, 1=name, 2=owner(uuid)
command.map.admin.info.map=Map: <aqua>{1}</aqua>\n\
  ID: <aqua>{0}</aqua>\n\
  Owner: <aqua>{2}</aqua>
# 0=map id
command.map.admin.info.not_found=<red>Map {0} does not exist.</red>
# 0=error, 1=map id
command.map.admin.info.unknown_error=<red>Failed to load map {1}</red><gray>:</gray> {0}

# Map status
# 0, 1, 2, 3, 4 = x, y, z, pitch, yaw
command.map.setspawn=<white>Set map spawn to X: <aqua>{0}</aqua>, Y: <aqua>{1}</aqua>, Z: <aqua>{2}</aqua>, Pitch: <aqua>{3}</aqua>, Yaw: <aqua>{4}</aqua>.