# Chat-Related
# 0: The player you are sending a message to or a receiving a message from
# 1: The message being sent
chat.msg.send=<$white_gray>You</$light_blue> <$white_gray>-></$dark_gray> <0> <$dark_gray>»</$dark_gray> <$white><1></$white>
chat.msg.receive=<0> <$dark_gray>-></$dark_gray> <$white_gray>You</$white_gray> <$dark_gray>»</$dark_gray> <$white><1></$white>
chat.msg.no_text=$WARNING<$light_gray>You need a <$white>message</$white> to send!</$light_gray>
chat.msg.no_reply=$WARNING<$light_gray>You have <$white>nobody</$white> to reply to!</$light_gray>
chat.msg.cant_message_yourself=$DENY<$light_gray>You can only message other <$white>players</$white>!</$light_gray>
# 0: The chat channel the player is already in or switching to
chat.channel.already_in=$WARNING<$light_gray>You are already in <$white><0></$white>!</$light_gray>
chat.channel.changed=$CONFIRM<$light_gray>You are now talking in <$white><0></$white>.</$light_gray>
chat.channel.invalid=$DENY<$light_gray>That channel <$white>doesn't exist</$white>!</$light_gray>
# 0: Player username
# 1: Chat message
chat.channel.global=<0> <$dark_gray>»</$dark_gray> <$light_gray><1></$light_gray>
chat.channel.local=<hover:show_text:'Local Chat'>$LOCAL_CHANNEL</hover><0> <$dark_gray>»</$dark_gray> <$light_gray><1></$light_gray>
chat.channel.staff=<hover:show_text:'Staff Chat'>$STAFF_CHANNEL</hover><0> <$dark_gray>»</$dark_gray> <$light_gray><1></$light_gray>
# DMs are all the same args
# 0: sender display name
# 1: receiver display name
# 2: message<0> <$dark_gray>-></$dark_gray> <1><$white_gray>:</$white_gray> <2>
chat.channel.dm.send=<$white_gray>You</$white_gray> <$dark_gray>-></$dark_gray> <1><$light_gray>:</$light_gray> <2>
chat.channel.dm.receive=<0> <$dark_gray>-></$dark_gray> <$white_gray>You:</$white_gray> <2>
chat.channel.dm.spy=<0> <$dark_gray>-></$dark_gray> <1><$white_gray>:</$white_gray> <2>
chat.channel.dm.disabled.self=$DENY<$light_gray>You have direct messages disabled!</$light_gray>
chat.channel.dm.disabled=$DENY<$light_gray><0> has direct messages disabled!</$light_gray>
badge.ct_1.lore=<$lime>Creative Team</$lime>
badge.ct_2.lore=<$light_blue>Creative Team</$light_blue>
badge.ct_3.lore=<$red>Creative Team</$red>
badge.dev_1.lore=<$lime>Developer</$lime>
badge.dev_2.lore=<$light_blue>Developer</$light_blue>
badge.dev_3.lore=<$red>Developer</$red>
badge.mod_1.lore=<$lime>Moderator</$lime>
badge.mod_2.lore=<$light_blue>Moderator</$light_blue>
badge.mod_3.lore=<$red>Administrator</$red>
badge.media.lore=<#cc39e9>Media</#cc39e9>
badge.hypercube/gold.lore=<$gold>Hypercube Donor Rank</$gold>
badge.emc.lore=<$yellow>Friend</$yellow> <$dark_gray>(<gradient:gold:light_purple>EmortalMC</gradient>)</$dark_gray>
command.emojis.header=$INFO<$light_gray>Hover over an icon to see how to type it in chat.</$light_gray>
command.emojis.header.public=<$light_gray>Default Emojis:</$light_gray>
command.emojis.header.hypercube=<$light_gray>Hypercube Rank Emojis:</$light_gray>
chat.emoji.no_hypercube=$INFO<$light_gray>You need the <$white>Hypercube Rank</$white> to <$white>use</$white> this <$white>emoji</$white>!</$light_gray>
chat.map.invalid=$DENY<$light_gray>You can only share a published map in chat!</$light_gray>
minestom.info=\
  $INFO<$white_gray><click:open_url:https://minestom.net><hover:show_text:'<$lime>Click here to learn more!'>We don't have plugins! Everything is custom-made using <$white>Minestom</$white>. <$lime>Click here to learn more!</$lime></hover></click></$white_gray>
chat.reply.no_target=$DENY<$light_gray>You don't have anyone to reply to!</$light_gray>
map_join.wrongversion=$DENY <$white><0></$white> <$red>was made for version <$white><1></$white> or higher, you must change version to play it!</$red>
join.unsupported_mods=$DENY <$red>You are using supported mods, but they are only supported on the latest version. \
  Please switch to <$white><0></$white> to use them: <$white><1></$white></$red>