# Top Times [/toptimes, /tt]

commands.top_times.no_map_found=$DENY <$light_gray>Map with ID <$white><0></$white> doesn't exist!</$light_gray>
commands.top_times.no_maps_played=$DENY <$light_gray>You haven't played any maps recently to find a map to get top times for!</$light_gray>
commands.top_times.no_times_found=$DENY <$light_gray>No times found for map with ID <$white><0></$white>!</$light_gray>
commands.top_times.map_cant_have_top_times=$DENY <$light_gray>Map with ID <$white><0></$white> can't have top times as it is not a parkour map!</$light_gray>

# Back [/back]

commands.back.no_previous_location=$DENY <$light_gray>You don't have a previous location to return to!</$light_gray>
commands.back.success=$CONFIRM <$light_gray>Returned to previous location!</$light_gray>
