# suppress inspection "UnusedMessageFormatParameter" for whole file
generic.sanity_check_failed=<#696969>[<#FF2D2D>?</#FF2D2D></#696969>] <#B0B0B0>An unknown error occurred, please try again later! If this issue persists, please contact an</#B0B0B0> <#FF2D2D>Administrator</#FF2D2D> or <#AC4BFF>Developer</#AC4BFF><#B0B0B0>.</#B0B0B0>
forced.input.name=<0>
command.generic.unknown_error=<$red>An unknown error has occurred. Please contact an administrator.</$red>