# Top Times [/toptimes, /tt]

commands.top_times.no_map_found=$DENY <$light_gray>Map with ID <$white><0></$white> doesn't exist!</$light_gray>
commands.top_times.no_maps_played=$DENY <$light_gray>You haven't played any maps recently to find a map to get top times for!</$light_gray>
commands.top_times.no_times_found=$DENY <$light_gray>No times found for map with ID <$white><0></$white>!</$light_gray>
commands.top_times.map_cant_have_top_times=$DENY <$light_gray>Map with ID <$white><0></$white> can't have top times as it is not a parkour map!</$light_gray>

# Back [/back]

commands.back.no_previous_location=$DENY <$light_gray>You don't have a previous location to return to!</$light_gray>
commands.back.success=$CONFIRM <$light_gray>Returned to previous location!</$light_gray>

# Set Spawn Point [/setspawn, /setstart]

command.set_spawn.out_of_world=$DENY <$light_gray>You can't set the spawn point too close to the world border!</$light_gray>

# Biome Info [//biomeinfo]

commands.biome_info.no_biome_found=$DENY <$light_gray>No biome found!</$light_gray>
commands.biome_info.success=\
  $INFO <$light_gray>Biome: <$white><0> (<1>)</$white></$light_gray>\n\
  <$light_gray> Precipitation: <$white><2></$white></$light_gray>\n\
  <$light_gray> Water Color: <$white><3></$white></$light_gray>\n\
  <$light_gray> Grass Color: <$white><4></$white></$light_gray>\n\
  <$light_gray> Foilage Color: <$white><5></$white></$light_gray>

# Biome List [//biomelist, //biomels]

commands.biome_list.header=$INFO <$white>Biomes</$white>
commands.biome_list.footer.no_left=<$light_gray>⬅</$light_gray> <$azure>Page (<0>/<1>)</$azure> <hover:show_text:'<$light_gray>Next page.</$light_gray>'><click:run_command:'//biomelist <2>'>➡</click></hover>
commands.biome_list.footer.no_right=<hover:show_text:'<$light_gray>Previous page.</$light_gray>'><click:run_command:'//biomelist <0>'>⬅</click></hover> <$azure>Page (<1>/<2>)</$azure> <$light_gray>➡</$light_gray>
commands.biome_list.footer=<hover:show_text:'<$light_gray>Previous page.</$light_gray>'><click:run_command:'//biomelist <0>'>⬅</click></hover> <$azure>Page (<1>/<2>)</$azure> <hover:show_text:'<$light_gray>Next page.</$light_gray>'><click:run_command:'//biomelist <3>'>➡</click></hover>
commands.biome_list.invalid_page=$DENY <$light_gray>Invalid page number <$white><0></$white>, max page number is <$white><1></$white>!</$light_gray>
commands.biome_list.entry=<$dark_gray> - </$dark_gray><hover:show_text:'<2>'><$light_gray><0> (<1>)</$light_gray></hover>
commands.biome_info.tooltip=\
  <$light_gray> Precipitation: <$white><2></$white></$light_gray>\n\
  <$light_gray> Water Color: <$white><3></$white></$light_gray>\n\
  <$light_gray> Grass Color: <$white><4></$white></$light_gray>\n\
  <$light_gray> Foilage Color: <$white><5></$white></$light_gray>

# Set Biome [//setbiome]

commands.set_biome.success=$CONFIRM <$light_gray>Set biome to <$white><0> (<1>)</$white>!</$light_gray>

# Change Channel [/chat]

commands.chat.switching.global=$CONFIRM <$light_gray>Switched to chat channel <$white>Global</$white>!</$light_gray>
commands.chat.switching.local=$CONFIRM <$light_gray>Switched to chat channel <$white>Local</$white>!</$light_gray>
commands.chat.switching.staff=$CONFIRM <$light_gray>Switched to chat channel <$white>Staff</$white>!</$light_gray>

# /debug poi and /debug boundingbox
commands.debug.needs_mt=$DENY <$light_gray>This command requires the <$white>Moulberry's Tweaks</$white> mod to be installed.</$light_gray> <$lime><click:open_url:"https://modrinth.com/mod/moulberrystweaks">Click here for more info!</click></$lime>

# /banner
commands.banner.no_url=\
  $INFO <$light_gray>You need to provide a minecraft.wiki link to a banner pattern!</$light_gray>\n\
  <$light_gray>Example: <$white>https://minecraft.wiki/w/Calculators/Banner#?activePatterns=[]&baseColor=white</$white></$light_gray>\n\
  <click:open_url:"https://minecraft.wiki/w/Calculators/Banner"><$yellow>Click here to open the banner editor!</$yellow></click>
commands.banner.invalid_url=$DENY <$light_gray>The provided URL is not a valid minecraft.wiki banner link!</$light_gray>
commands.banner.malformed_url=$DENY <$light_gray>The provided URL is a malformed minecraft.wiki banner link!</$light_gray>

# /friend

# /friend add
#command.friend.add.self= TODO no args
#command.friend.add.request_sent= TODO 0: targetUsername
# added is when they were added as a friend
#command.friend.add.added= TODO 0: targetUsername
#command.friend.add.already_friends= TODO 0: targetUsername
#command.friend.add.blocked_by_self= TODO 0: targetUsername
#command.friend.add.blocked_by_target= TODO 0: targetUsername
#command.friend.add.already_requested= TODO 0: targetUsername
#command.friend.add.limit_reached= TODO 0: limit, 1: friendCount, 2: outgoingRequestCount

# /friend remove
#command.friend.remove.self= TODO no args
#command.friend.remove.success= TODO 0: targetUsername
#command.friend.remove.not_friends= TODO 0: targetUsername

# /friend request list <incoming/outgoing>
#command.friend.request.list.header= TODO 0: page, 1: pageCount
#command.friend.request.list.line= TODO 0: friendUsername (can add timestamp if wanted), can add a var to give incoming/outgoing to add a linked /friend request <deny/remove> if wanted

# /friend request remove - player removes a request bidirectionally (so either they sent, or they received)
#command.friend.request.remove.self= TODO no args
#command.friend.request.remove.success= TODO 0: targetUsername, can add a var for the direction the deleted request was if wanted
#command.friend.request.remove.not_requested= TODO 0: targetUsername

# /friend list
#command.friend.list.header= TODO 0: pageNumber, 1: maxPageNumber/pageCount
#command.friend.list.line= TODO 0: friendUsername, can hyperlink with /friend remove <friendUsername>

# /block
#command.block.self= TODO no args
#command.block.success= TODO 0: targetUsername
#command.block.already_blocked= TODO 0: targetUsername
#command.block.cannot_target_staff= TODO 0: targetUsername

# /block list
#command.block.list.header= TODO 0: pageNumber, 1: pageCount
#command.block.list.line= TODO 0: blockedUsername, can hyperlink with /unblock <blockedUsername>

# /unblock
#command.unblock.self= TODO no args
#command.unblock.success= TODO 0: targetUsername
#command.unblock.not_blocked= TODO 0: targetUsername
