#
# GENERIC
#
cosmetic.head.lore=<0>\n\n<1>

cosmetic.select=$LMB to select
cosmetic.deselect=$LMB to deselect
cosmetic.locked=LOCKED

#
# Headwear
#

cosmetic.hat.top_hat.name=
cosmetic.hat.top_hat.lore=

cosmetic.head.crown.name=Crown
cosmetic.head.crown.lore=<$light_gray>I am crown lore</$light_gray>
cosmetic.head.hard_hat.name=Hard Hat
cosmetic.head.hard_hat.lore=<$light_gray>I am hard hat lore</$light_gray>
cosmetic.head.pirate_hat.name=Pirate Hat
cosmetic.head.pirate_hat.lore=<$light_gray>I am pirate hat lore</$light_gray>

#
# Backwear
#

#
# Accessories
#

#
# Companions
#

#
# Emotes
#

#
# Particles
#

#
# Victory Effects
#