#
# GENERIC
#
cosmetic.head.lore=<0>\n\n<1>

cosmetic.select=$LMB <$white_gray>Click to Equip</$white_gray>
cosmetic.deselect=$LMB <$white_gray>Click to Unequip</$white_gray>
cosmetic.locked=<$red>Locked</$red>

#
# Headwear
#

cosmetic.hat.top_hat.name=<$titanium>Top Hat</$titanium>
cosmetic.hat.top_hat.lore=\
  <$light_gray>Fancy, and big enough to hide a rabbit.</$light_gray>

cosmetic.hat.sunglasses.name=<$titanium>Sunglasses</$titanium>
cosmetic.hat.sunglasses.lore=\
  <$light_gray>Stylish shades for a stylish person.</$light_gray>

cosmetic.hat.hard_hat.name=<$titanium>Hard Hat</$titanium>
cosmetic.hat.hard_hat.lore=\
  <$light_gray>Safety first!</$light_gray>

cosmetic.hat.flower_head.name=<$titanium>Flower Head</$titanium>
cosmetic.hat.flower_head.lore=\
  <$light_gray>So... is this growing from the pot, or my brain?</$light_gray>

cosmetic.hat.crown.name=<$titanium>Gold Crown</$titanium>
cosmetic.hat.crown.lore=\
  <$light_gray>A symbol of royalty, prestige, and<$light_gray>\n\
  <$light_gray>probably abuse of power.</$light_gray>

cosmetic.hat.clown_mask.name=<$azure>Clown Mask</$azure>
cosmetic.hat.clown_mask.lore=\
  <$light_gray>Juggling balls not included.</$light_gray>

cosmetic.hat.miners_hat.name=<$azure>Miner's Hat</$azure>
cosmetic.hat.miners_hat.lore=\
  <$light_gray>Diggy diggy hole~</$light_gray>

cosmetic.hat.knight_helmet.name=<$azure>Knight's Helmet</$azure>
cosmetic.hat.knight_helmet.lore=\
  <$light_gray>For justice! For glory! For the honorable<$light_gray>\n\
  <$light_gray>quest of finding matching armor!</$light_gray>

cosmetic.hat.apprentice_hat.name=<$azure>Apprentice's Cap</$azure>
cosmetic.hat.apprentice_hat.lore=\
  <$light_gray>A standard hat for those starting to practice magic.</$light_gray>

cosmetic.hat.samurai_helmet.name=<$azure>Samurai Helmet</$azure>
cosmetic.hat.samurai_helmet.lore=\
  <$light_gray>A striking red helm adorned with golden horns.</$light_gray>

cosmetic.hat.shark_hat.name=<$azure>Shark Hat</$azure>
cosmetic.hat.shark_hat.lore=\
  <$light_gray>CHOMP, CHOMP, CHOMP! Sorry, sometimes</$light_gray>\n\
  <$light_gray>I get a little carried away...</$light_gray>

cosmetic.hat.kitsune_mask.name=<$azure>Kitsune Mask</$azure>
cosmetic.hat.kitsune_mask.lore=\
  <$light_gray>Channel the agile and cunning fox spirits</$light_gray>\n\
  <$light_gray>to guide you on your journey.</$light_gray>

cosmetic.hat.wizard_hat.name=<$purple>Wizard's Cap</$purple>
cosmetic.hat.wizard_hat.lore=\
  <$light_gray>A long, pointy hat embroidered with intricate mystical</$light_gray>\n\
  <$light_gray>symbols,perfect for those who embrace the arcane arts.</$light_gray>

cosmetic.hat.oni_mask.name=<$purple>Oni Helmet</$purple>
cosmetic.hat.oni_mask.lore=\
  <$light_gray>A fierce mask carved in the shape of a demon.</$light_gray>\n\
  <$light_gray>You feel an ominous presence inside.</$light_gray>

cosmetic.hat.bikers_helmet.name=<$purple>Biker's Helmet</$purple>
cosmetic.hat.bikers_helmet.lore=\
  <$light_gray>Look cool <italic>AND</italic> avoid brain injury at the same time!</$light_gray>

cosmetic.hat.evil_clown_mask.name=<$purple>Evil Clown Mask</$purple>
cosmetic.hat.evil_clown_mask.lore=\
  <$light_gray>Not your usual friendly neighborhood clown...</$light_gray>\n\
  <$light_gray>unless you live in a nightmare.</$light_gray>



#
# Backwear
#

#
# Accessories
#

#
# Companions
#

#
# Emotes
#

#
# Particles
#

#
# Victory Effects
#