#
# GENERIC
#
cosmetic.head.lore=<0>\n\n<1>
cosmetic.select=$LMB <$white_gray>Click to Equip</$white_gray>
cosmetic.deselect=$LMB <$white_gray>Click to Unequip</$white_gray>
cosmetic.locked=<$red>Locked</$red>
cosmetic.preview=$RMB <$white_gray>Right-Click to Preview</$white_gray>
cosmetic.type.hat.blank.name=<$white>Equipped Headwear</$white>
cosmetic.type.hat.blank.lore=\
  <$light_gray>Current: </$light_gray><$red>None</$red>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>
cosmetic.type.backwear.blank.name=<$white>Equipped Backwear</$white>
cosmetic.type.backwear.blank.lore=\
  <$light_gray>Current: </$light_gray><$red>None</$red>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>
cosmetic.type.pet.blank.name=<$white>Equipped Companion</$white>
cosmetic.type.pet.blank.lore=\
  <$light_gray>Current: </$light_gray><$red>None</$red>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>
cosmetic.type.particle.blank.name=<$white>Equipped Particles</$white>
cosmetic.type.particle.blank.lore=\
  <$light_gray>Current: </$light_gray><$red>None</$red>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>
cosmetic.type.emote.blank.name=<$white>Equipped Emotes</$white>
cosmetic.type.emote.blank.lore=\
  <$light_gray>Current: </$light_gray><$red>None</$red>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>
cosmetic.type.victory_effect.blank.name=<$white>Equipped Victory Effect</$white>
cosmetic.type.victory_effect.blank.lore=\
  <$light_gray>Current: </$light_gray><$red>None</$red>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>
#
# Headwear
#
cosmetic.hat.top_hat.name=<$titanium>Top Hat</$titanium>
cosmetic.hat.top_hat.lore=\
  <$light_gray>Fancy, and big enough to hide a rabbit.</$light_gray>
cosmetic.hat.sunglasses.name=<$titanium>Sunglasses</$titanium>
cosmetic.hat.sunglasses.lore=\
  <$light_gray>Stylish shades for a stylish person.</$light_gray>
cosmetic.hat.hard_hat.name=<$titanium>Hard Hat</$titanium>
cosmetic.hat.hard_hat.lore=\
  <$light_gray>Safety first!</$light_gray>
cosmetic.hat.flower_head.name=<$titanium>Flower Head</$titanium>
cosmetic.hat.flower_head.lore=\
  <$light_gray>So... is this growing from the pot, or my brain?</$light_gray>
cosmetic.hat.crown.name=<$titanium>Gold Crown</$titanium>
cosmetic.hat.crown.lore=\
  <$light_gray>A symbol of royalty, prestige...<$light_gray>\n\
  <$light_gray>and probably abuse of power!</$light_gray>
cosmetic.hat.straw_hat.name=<$titanium>Straw Hat</$titanium>
cosmetic.hat.straw_hat.lore=\
  <$light_gray>A simple, straw hat. For some reason,<$light_gray>\n\
  <$light_gray>it reminds you of a pirate.</$light_gray>
cosmetic.hat.dog_ears.name=<$titanium>Dog Ears</$titanium>
cosmetic.hat.dog_ears.lore=\
  <$light_gray>Woof, woof!</$light_gray>
cosmetic.hat.cat_ears.name=<$titanium>Cat Ears</$titanium>
cosmetic.hat.cat_ears.lore=\
  <$light_gray>:3</$light_gray>
cosmetic.hat.pirate_hat.name=<$azure>Pirate Hat</$azure>
cosmetic.hat.pirate_hat.lore=\
  <$light_gray>Yar be sailing the seven seas!</$light_gray>
cosmetic.hat.clown_mask.name=<$azure>Clown Mask</$azure>
cosmetic.hat.clown_mask.lore=\
  <$light_gray>Juggling balls not included.</$light_gray>
cosmetic.hat.cake_hat.name=<$azure>Cake Hat</$azure>
cosmetic.hat.cake_hat.lore=\
  <$light_gray>Baked to perfection.</$light_gray>
cosmetic.hat.miners_hat.name=<$azure>Miner's Hat</$azure>
cosmetic.hat.miners_hat.lore=\
  <$light_gray>Diggy diggy hole~</$light_gray>
cosmetic.hat.knight_helmet.name=<$azure>Knight's Helmet</$azure>
cosmetic.hat.knight_helmet.lore=\
  <$light_gray>For justice! For glory! For the honorable<$light_gray>\n\
  <$light_gray>quest of finding matching armor!</$light_gray>
cosmetic.hat.apprentice_hat.name=<$azure>Apprentice's Cap</$azure>
cosmetic.hat.apprentice_hat.lore=\
  <$light_gray>A standard hat for those starting to practice magic.</$light_gray>
cosmetic.hat.samurai_helmet.name=<$azure>Samurai Helmet</$azure>
cosmetic.hat.samurai_helmet.lore=\
  <$light_gray>A striking red helm adorned with golden horns.</$light_gray>
cosmetic.hat.kitsune_mask.name=<$azure>Kitsune Mask</$azure>
cosmetic.hat.kitsune_mask.lore=\
  <$light_gray>Channel the agile and cunning fox</$light_gray>\n\
  <$light_gray>spirits to guide you on your journey.</$light_gray>
cosmetic.hat.bikers_helmet.name=<$azure>Biker's Helmet</$azure>
cosmetic.hat.bikers_helmet.lore=\
  <$light_gray>Look cool <italic>AND</italic> avoid brain injury at the same time!</$light_gray>
cosmetic.hat.wizard_hat.name=<$azure>Wizard's Cap</$azure>
cosmetic.hat.wizard_hat.lore=\
  <$light_gray>A long, pointy hat embroidered with mystical symbols,</$light_gray>\n\
  <$light_gray>perfect for those who embrace the arcane arts.</$light_gray>
cosmetic.hat.oni_mask.name=<$purple>Oni Helmet</$purple>
cosmetic.hat.oni_mask.lore=\
  <$light_gray>A fierce mask carved in the shape of a demon.</$light_gray>\n\
  <$light_gray>You feel an ominous presence inside.</$light_gray>
cosmetic.hat.shark_hat.name=<$purple>Shark Hat</$purple>
cosmetic.hat.shark_hat.lore=\
  <$light_gray>CHOMP, CHOMP, CHOMP! Sorry, sometimes</$light_gray>\n\
  <$light_gray>I get a little carried away...</$light_gray>
cosmetic.hat.evil_clown_mask.name=<$purple>Evil Clown Mask</$purple>
cosmetic.hat.evil_clown_mask.lore=\
  <$light_gray>Not your usual friendly neighborhood clown...</$light_gray>\n\
  <$light_gray>Unless you live in a nightmare.</$light_gray>
cosmetic.hat.elf_hat.name=<$titanium>Elf Hat</$titanium>
cosmetic.hat.elf_hat.lore=\
  <$light_gray>Official North Pole Workshop gear.</$light_gray>\n\
  <$light_gray>Pointy ears not included!</$light_gray>
cosmetic.hat.snowman_head.name=<$azure>Snowman Head</$azure>
cosmetic.hat.snowman_head.lore=\
  <$light_gray>Day 45: The other snowmen still suspect nothing.<$light_gray>\n\
  <$light_gray>I have almost gained their trust.<$light_gray>
cosmetic.hat.santa_hat.name=<$purple>Santa Hat</$purple>
cosmetic.hat.santa_hat.lore=\
  <$light_gray>100% more jolly than a normal hat!</$light_gray>
#
# Backwear
#
#
# Accessories
#
cosmetic.accessory.training_sword.name=<$titanium>Training Sword</$titanium>
cosmetic.accessory.training_sword.lore=\
  <$light_gray>A non-lethal, wooden sword, perfect for practice bouts.</$light_gray>
cosmetic.accessory.wrench.name=<$titanium>Wrench</$titanium>
cosmetic.accessory.wrench.lore=\
  <$light_gray>A trusty tool for tightening up your game.</$light_gray>
cosmetic.accessory.donut.name=<$titanium>Donut</$titanium>
cosmetic.accessory.donut.lore=\
  <$light_gray>The prerequisite to becoming a police officer.</$light_gray>
cosmetic.accessory.burger.name=<$azure>Burger</$azure>
cosmetic.accessory.burger.lore=\
  <$light_gray>This is almost too much to eat! Almost...</$light_gray>
cosmetic.accessory.dynamite.name=<$azure>Dynamite</$azure>
cosmetic.accessory.dynamite.lore=\
  <$light_gray>IT'S GONNA BLOW!!!</$light_gray>
cosmetic.accessory.knights_sword.name=<$azure>Knight's Sword</$azure>
cosmetic.accessory.knights_sword.lore=\
  <$light_gray>Standard equipment for a soldier. It has a sharp edge.</$light_gray>
cosmetic.accessory.cyberfist.name=<$purple>Cyberfist</$purple>
cosmetic.accessory.cyberfist.lore=\
  <$light_gray>A high-tech prosthetic, powered by a mysterious energy source.</$light_gray>
cosmetic.accessory.coffee_cup.name=<$purple>Coffee Cup</$purple>
cosmetic.accessory.coffee_cup.lore=\
  <$light_gray>I only have one every morning, I swear I'm not addicted!</$light_gray>
cosmetic.accessory.drill.name=<$gold>Drill</$gold>
cosmetic.accessory.drill.lore=\
  <$light_gray>Rock and stone!</$light_gray>
cosmetic.accessory.excalibur.name=<$gold>Excalibur</$gold>
cosmetic.accessory.excalibur.lore=\
  <$light_gray>It is believed that only a true knight who possesses honor,</$light_gray>\n\
  <$light_gray>courage, and purity of heart can wield this mythical weapon.</$light_gray>
cosmetic.accessory.shrinking_device.name=<$gold>Shrinking Device</$gold>
cosmetic.accessory.shrinking_device.lore=\
  <$light_gray>Honey, I shrunk the kids!</$light_gray>
cosmetic.accessory.shrinking_device.cooldown=\
  $WARNING<$light_gray>You must wait to use your <$gold>Shrinking Device</$gold>.</$light_gray>
cosmetic.accessory.shonk.name=<$azure>Shonk</$azure>
cosmetic.accessory.shonk.lore=\
  <$light_gray>#1 Swedish plushie, perfect for cuddling.</$light_gray>
cosmetic.accessory.candy_cane.name=<$azure>Candy Cane</$azure>
cosmetic.accessory.candy_cane.lore=\
  <$light_gray>Eat it, or swing it!</$light_gray>
#
# Companions
#
#
# Emotes
#
#
# Particles
#
cosmetic.particle.cloud.name=<$white>Cloud</$white>
cosmetic.particle.cloud.lore=\
  <$light_gray>Is this what heaven feels like?</$light_gray>
cosmetic.particle.note.name=<$white>Notes</$white>
cosmetic.particle.note.lore=\
  <$light_gray>Bounce to the beat!</$light_gray>
cosmetic.particle.bubble.name=<$white>Bubbles</$white>
cosmetic.particle.bubble.lore=\
  <$light_gray>Must... resist... THE URGE... TO POP THEM!</$light_gray>
cosmetic.particle.cherry_leaves.name=<$white>Cherry Leaves</$white>
cosmetic.particle.cherry_leaves.lore=\
  <$light_gray>Let the wind carry you away...</$light_gray>
cosmetic.particle.snowfall.name=<$purple>Snowfall</$purple>
cosmetic.particle.snowfall.lore=\
  <$light_gray>Is it just me, or is it a bit chilly in here?</$light_gray>

#
# Victory Effects
#
cosmetic.victory_effect.explosion.name=<$titanium>Explosion</$titanium>
cosmetic.victory_effect.explosion.lore=\
  <$light_gray>Celebrate your victory with a bang!</$light_gray>
cosmetic.victory_effect.firework.name=<$titanium>Fireworks</$titanium>
cosmetic.victory_effect.firework.lore=\
  <$light_gray>Enjoy the show!</$light_gray>
cosmetic.victory_effect.lightning.name=<$titanium>Lightning</$titanium>
cosmetic.victory_effect.lightning.lore=\
  <$light_gray>Electrifying!</$light_gray>
cosmetic.victory_effect.omega.name=<$azure>Omega Jingle</$azure>
cosmetic.victory_effect.omega.lore=\
  <$light_gray>The classic victory tune from Omega Parkour.</$light_gray>
cosmetic.victory_effect.train.name=<$purple>Train</$purple>
cosmetic.victory_effect.train.lore=\
  <$light_gray>Why can't public transportation be as good as this?!</$light_gray>
cosmetic.victory_effect.jolly.name=<$purple>Jolly Explosion</$purple>
cosmetic.victory_effect.jolly.lore=\
  <$light_gray><$yellow>WARNING:</$yellow> You will be finding glitter in your</$light_gray>\n\
  <$light_gray>inventory for the next three years.</$light_gray>