# Generic stuff
cosmetic.head.lore=Generic head cosmetic lore\nRarity: <0>\n\n"<1>"

cosmetic.select=$LMB to select
cosmetic.deselect=$LMB to deselect
cosmetic.locked=LOCKED

# Rarities
cosmetic.rarity.common=Common
cosmetic.rarity.rare=Rare
cosmetic.rarity.epic=Epic
cosmetic.rarity.legendary=Legendary

# Head cosmetics
cosmetic.head.crown.name=Crown
cosmetic.head.crown.lore=Crown lore
cosmetic.head.pirate_hat.name=Pirate Hat
cosmetic.head.pirate_hat.lore=Pirate Hat lore
