gui.checkpoint.custom_blocks.name=<$white>Custom Blocks Menu</$white>
gui.checkpoint.custom_blocks.lore=\
  <$light_gray>View all Custom Blocks placed anywhere on the map.</$light_gray>\n\
  <$light_gray>Useful for if you want to edit their properties from</$light_gray>\n\
  <$light_gray>afar or teleport to one in case you forgot its location.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.checkpoint.pick_up.name=<$white>Pick Up Checkpoint</$white>
gui.checkpoint.pick_up.lore=\
  <$light_gray>Pick up this Checkpoint as an item</$light_gray>\n\
  <$light_gray>to place it elsewhere in your map.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.checkpoint.tab.settings.name=<$white>Checkpoint Settings</$white>
gui.checkpoint.tab.actions.name=<$white>Checkpoint Actions</$white>
gui.checkpoint.tab.coordinates.name=<$white>Checkpoint Coordinates</$white>
gui.checkpoint.tab.coordinates.lore=<$red>Coming Later!</$red>

gui.status.tab.settings.name=<$white>Status Plate Settings</$white>
gui.status.tab.actions.name=<$white>Status Plate Actions</$white>

gui.checkpoint.information.name=<$yellow>Information</$yellow>
gui.checkpoint.information.lore=\
  <$light_gray>View information related to this</$light_gray>\n\
  <$light_gray>Checkpoint, modify its settings, and</$light_gray>\n\
  <$light_gray>add effects that happen on its activation.</$light_gray>

gui.status.information.name=<$yellow>Information</$yellow>
gui.status.information.lore=\
  <$light_gray>View information related to this</$light_gray>\n\
  <$light_gray>Status Plate, modify its settings, and</$light_gray>\n\
  <$light_gray>add effects that happen on its activation.</$light_gray>

# Name
gui.effect.name.name=<$white>Checkpoint Name</$white>
gui.effect.name.lore=\
  <$light_gray>Current:</$light_gray> <0>\n\n\
  <$light_gray>The name of this Checkpoint, used to help</$light_gray>\n\
  <$light_gray>you more easily remember its purpose.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.name.none=<$red>None</$red>

# Progress Index
gui.effect.progress_index.name=<$white>Progress Index</$white>
gui.effect.progress_index.lore=\
  <$light_gray>Current:</$light_gray> <0>\n\n\
  <$light_gray>To activate this Checkpoint, the player's</$light_gray>\n\
  <$light_gray>Progress Index must be one less than</$light_gray>\n\
  <$light_gray>or equal to the defined number.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.progress_index.none=<$red>None</$red>  

# Lives
gui.checkpoint.lives.name=<$white>Checkpoint Lives</$white>
gui.checkpoint.lives.lore=\
  <$light_gray>Current:<$light_gray> <0>\n\n\
  <$light_gray>How many times a player can fail or manually</$light_gray>\n\
  <$light_gray>return to this Checkpoint before they get</$light_gray>\n\
  <$light_gray>reset to their previous Checkpoint.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.checkpoint.lives.none=<$red>None</$red>

# Time Limit
gui.effect.time_limit.name=<$white>Time Limit</$white>
gui.effect.time_limit.lore=\
  <$light_gray>Current:<$light_gray> <0>\n\n\
  <$light_gray>Set how long a player has upon activating or</$light_gray>\n\
  <$light_gray>returning to this Checkpoint to reach another,</$light_gray>\n\
  <$light_gray>get extra time through a Status, or finish the map,</$light_gray>\n\
  <$light_gray>otherwise they'll be reset back to this Checkpoint.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.time_limit.none=<$red>None</$red>

# Reset Height
gui.effect.reset_height.name=<$white>Reset Height</$white>
gui.effect.reset_height.lore=\
  <$light_gray>Current: <0></$light_gray>\n\n\
  <$light_gray>Falling under this defined Y-level will</$light_gray>\n\
  <$light_gray>return the player to this checkpoint.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.reset_height.none=<$red>Inherited</$red>

# Add Effects
gui.effect.actions.potion_effects.name=<$white>Potion Effects</$white>
gui.effect.actions.potion_effects.lore=\
  <$light_gray>Gives permanent or timed potion effects when</$light_gray>\n\
  <$light_gray>a player activates or returns to this Checkpoint.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.actions.potion_effects.header=<$light_gray>Current: </$light_gray>
gui.effect.actions.potion_effects.entry=<$dark_gray> �</$dark_gray> <0> <1> <$light_gray>for</$light_gray> <2>
gui.effect.actions.potion_effects.footer=\n\
  <$light_gray>Gives permanent or timed potion effects when</$light_gray>\n\
  <$light_gray>a player activates or returns to this Checkpoint.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.actions.potion_effects.none=<$red>None</$red>

# Clear Effects
gui.effect.actions.clear_effects.name=<$white>Clear Potion Effects</$white>
gui.effect.actions.clear_effects.lore=\
  <$light_gray>Current:</$light_gray> <0>\n\n\
  <$light_gray>Toggle if previous potion effects will be</$light_gray>\n\
  <$light_gray>cleared before adding new ones (if any).</$light_gray>\n\n\
  $LMB <$white_gray>Click to Toggle</$white_gray>
gui.effect.actions.clear_effects.enabled=<$lime>Enabled</$lime>
gui.effect.actions.clear_effects.disabled=<$red>Disabled</$red>

# Teleport
gui.effect.actions.teleport.name=<$white>Teleport to Coordinates</$white>
gui.effect.actions.teleport.lore=\
  <$light_gray>Current:</$light_gray> <0>\n\n\
  <$light_gray>Move the player to a set position.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.actions.teleport.none=<$red>Disabled</$red>
gui.effect.actions.teleport.pos=<$light_gray><$light_blue><0></$light_blue>, <$light_blue><1></$light_blue>, <$light_blue><2></$light_blue> [<$light_blue><3></$light_blue>, <$light_blue><4></$light_blue>]</$light_gray>

# Settings
gui.effect.actions.settings.name=<$white>Toggle Map Settings</$white>
gui.effect.actions.settings.lore=\
  <$light_gray>Temporarily turn a map setting on or off.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
gui.effect.actions.settings.header=<$light_gray>Current: </$light_gray>
gui.effect.actions.settings.entry=<$dark_gray> �</$dark_gray> <0> <$dark_gray>?</$dark_gray> <1> 
gui.effect.actions.settings.footer=\n\
  <$light_gray>Temporarily turn a map setting on or off.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.actions.settings.none=<red>None</$red>

# Add Item
gui.effect.actions.add_item.name=<$white>Give Item</$white>
gui.effect.actions.add_item.lore=\
  <$light_gray>Add an item to the player's inventory.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
gui.effect.actions.add_item.header=<$light_gray>Current: </$light_gray>
gui.effect.actions.add_item.entry=<$dark_gray> �</$dark_gray> <0>
gui.effect.actions.add_item.footer=\n\
  <$light_gray>Add an item to the player's inventory.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.actions.add_item.none=<$red>None</$red>

# Items
item.minecraft.elytra.name=<$white>Elytra</$white>
item.minecraft.trident.name=<$white>Trident</$white>

# Remove Item
gui.effect.actions.remove_item.name=<$white>Remove Item</$white>
gui.effect.actions.remove_item.lore=\
  <$light_gray>Remove an item to the player's inventory.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
gui.effect.actions.remove_item.header=<$light_gray>Current: </$light_gray>
gui.effect.actions.remove_item.entry=<$dark_gray> �</$dark_gray> <0>
gui.effect.actions.remove_item.footer=\n\
  <$light_gray>Remove an item to the player's inventory.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.actions.remove_item.none=<$red>None</$red>

# Repeatable (Status Only)
gui.status.repeatable.name=<$white>Repeatable</$white>
gui.status.repeatable.lore=<$light_gray>Current:</$light_gray> <0>\n\n\
  <$light_gray>Decides if this Status Plate can be activated</$light_gray>\n\
  <$light_gray>more than once on someone's current Checkpoint.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Toggle</$white_gray>
gui.status.repeatable.enabled=<$lime>Enabled</$lime>
gui.status.repeatable.disabled=<$red>Disabled</$red>

# Add/Extra Time (Status Only)
gui.effect.actions.add_time.name=<$white>Add Time</$white>
gui.effect.actions.add_time.lore=\
  <$light_gray>Current:</$light_gray> <0>\n\
  <$light_gray>Adds extra time (in seconds) to the Checkpoint time limit.</$light_gray>\n\n\
  $NOTE<$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>Does not count more than once per Checkpoint fail.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effects.actions.add_time.none=<$red>None</$red>

# Potion Effects
gui.effect.potion.list.information.name=<$yellow>Information</$yellow>
gui.effect.potion.list.information.lore=\
  <$light_gray>Shows all potions that you have on this plate.</$light_gray>

gui.effect.potion.editor.information.name=<$yellow>Information</$yellow>
gui.effect.potion.editor.information.lore=\
  <$light_gray>Edit the strength and length of a potion effect.</$light_gray>

gui.effect.potion.selector.information.name=<$yellow>Information</$yellow>
gui.effect.potion.selector.information.lore=\
  <$light_gray>Choose a new potion to add on this plate.</$light_gray>

gui.effect.potion.editor.header.name=<0>

gui.effect.potion.type.speed.name=Speed
gui.effect.potion.type.jump_boost.name=Jump Boost
gui.effect.potion.type.depth_strider.name=Depth Strider
gui.effect.potion.type.levitation.name=Levitation
gui.effect.potion.type.slow_fall.name=Slow Fall
gui.effect.potion.type.slowness.name=Slowness
gui.effect.potion.type.blindness.name=Blindness
gui.effect.potion.type.darkness.name=Darkness
gui.effect.potion.type.nausea.name=Nausea
gui.effect.potion.type.dolphins_grace.name=Dolphin's Grace

gui.effect.potion.entry.add=Add Effect
gui.effect.potion.edit.lore=\
  <$light_gray>Level:</$light_gray> <$white><0></$white>\n\
  <$light_gray>Duration:</$light_gray> <$white><1></$white>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Remove</$white_gray>
gui.effect.potion.duration.infinite=Infinite
gui.effect.potion.entry.add.name=Add Potion
gui.effect.potion.entry.add.lore=\
  $LMB <$white_gray>Click to View</$white_gray>

gui.effect.potion.time.current.name=Time
gui.effect.potion.time.current.lore=Current: <0>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>

gui.effect.potion.time.inc1_on.name=+1 Second
gui.effect.potion.time.inc5_on.name=+5 Seconds
gui.effect.potion.time.dec1_off.name=-1 Second
gui.effect.potion.time.dec5_off.name=-5 Seconds

gui.effect.potion.level.current.name=<0>
gui.effect.potion.duration.current.name=<0>
gui.effect.potion.duration.current.lore=\
  $LMB <$white_gray>Click to Edit</$white_gray>

gui.effect.potion.level.inc_on.name=+1
gui.effect.potion.level.inc_off.name=Can't Go Higher
gui.effect.potion.level.dec_on.name=-1
gui.effect.potion.level.dec_off.name=Can't Go Lower

gui.effect.potion.level.1.name=Level I
gui.effect.potion.level.1.lore=$LMB <$white_gray>Click to Select</$white_gray>
gui.effect.potion.level.2.name=Level II
gui.effect.potion.level.2.lore=$LMB <$white_gray>Click to Select</$white_gray>
gui.effect.potion.level.3.name=Level III
gui.effect.potion.level.3.lore=$LMB <$white_gray>Click to Select</$white_gray>
gui.effect.potion.level.4.name=Level IV
gui.effect.potion.level.4.lore=$LMB <$white_gray>Click to Select</$white_gray>
gui.effect.potion.level.5.name=Level V
gui.effect.potion.level.5.lore=$LMB <$white_gray>Click to Select</$white_gray>
gui.effect.potion.level.1.selected.name=Level I
gui.effect.potion.level.2.selected.name=Level II
gui.effect.potion.level.3.selected.name=Level III
gui.effect.potion.level.4.selected.name=Level IV
gui.effect.potion.level.5.selected.name=Level V
gui.effect.potion.level.custom.name=Custom Level
gui.effect.potion.level.custom.lore=$LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.potion.level.custom.selected.name=Custom Level
gui.effect.potion.level.custom.selected.lore=Current: <0>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>

#
# Items
#

item.mapmaker.finish_plate.name=<$gold>Finish Plate</$gold> $RMB_ITEM
item.mapmaker.finish_plate.lore=\
  <$light_gray>When a player steps on this,</$light_gray>\n\
  <$light_gray>they will complete the map.</$light_gray>

item.mapmaker.checkpoint_plate.name=<$white>Checkpoint Plate</$white> $RMB_ITEM
item.mapmaker.checkpoint_plate.lore=\
  <$light_gray>A checkpoint that players can return to.</$light_gray>\n\
  <$light_gray>Right click once placed to edit its properties.</$light_gray>

item.mapmaker.status_plate.name=<$orange>Status Plate</$orange> $RMB_ITEM
item.mapmaker.status_plate.lore=\
  <$light_gray>Modify player attributes and enhance map gameplay.</$light_gray>\n\
  <$light_gray>Right click once placed to edit its properties.</$light_gray>