dialog.generic.close=Close
dialog.generic.save=Save
dialog.generic.submit=Submit

dialog.settings.title=Server Options
dialog.settings.close=Close
dialog.settings.unsupported=$DENY<$light_gray>Setting options screen is only available on 1.21.6 or later.</$light_gray>

dialog.settings.option.cui=Terraform CUI
dialog.settings.option.chat=Chat Channel
dialog.settings.option.visibility=Player Visibility
dialog.settings.option.auto_reject_friend_requests=Auto-Reject Friend Requests
dialog.settings.option.allow_direct_messages=Allow Direct Messages (/msg)
dialog.settings.option.enable_ping_sounds=Enable Ping Sounds

dialog.interaction_entity.unsupported=$DENY<$light_gray>You can only edit interaction entities on 1.21.6 or later.</$light_gray>
dialog.bugreport.title=Report a Server Bug
dialog.bugreport.prompt=Please describe the issue in as much detail as possible
dialog.bugreport.no_message=$DENY<$light_gray>You must provide a message with your report.</$light_gray>
dialog.bugreport.success=$CONFIRM<$light_gray>We've received your report. Thank you for helping improve the server!</$light_gray>
dialog.bugreport.unsupported=$DENY<$light_gray>Usage: /bugreport <message></$light_gray>
