dialog.generic.close=Close
dialog.generic.save=Save


dialog.settings.title=Server Options
dialog.settings.close=Close
dialog.settings.unsupported=$DENY<$light_gray>Setting options screen is only available on 1.21.6 or later.</$light_gray>

dialog.settings.option.cui=Terraform CUI
dialog.settings.option.chat=Chat Channel
dialog.settings.option.visibility=Player Visibility

dialog.interaction_entity.unsupported=$DENY<$light_gray>You can only edit interaction entities on 1.21.6 or later.</$light_gray>