sidebar.display_entity.title=<$white>Selected Display Entity</$white>
sidebar.display_entity.type.title=<$yellow> Type:</$yellow>
sidebar.display_entity.type=<$light_gray>  <0></$light_gray>
sidebar.display_entity.position.title=<$yellow> Position:</$yellow>
sidebar.display_entity.x=<$red>  [X]</$red><$dark_gray>:</$dark_gray> <$light_gray><0:0.00></$light_gray>
sidebar.display_entity.y=<$lime>  [Y]</$lime><$dark_gray>:</$dark_gray> <$light_gray><0:0.00></$light_gray>
sidebar.display_entity.z=<$azure>  [Z]</$azure><$dark_gray>:</$dark_gray> <$light_gray><0:0.00></$light_gray>

sidebar.display_entity.rotation.title=<$yellow> Rotation:</$yellow>
sidebar.display_entity.rotation=<$red>  <0:0.00></$red><$light_gray> / </$light_gray><$lime><1:0.00></$lime><$light_gray> / </$light_gray><$azure><2:0.00></$azure><$light_gray>

sidebar.display_entity.scale.title=<$yellow> Scale:</$yellow>
sidebar.display_entity.scale=<$red>  <0:0.000></$red><$light_gray> / </$light_gray><$lime><1:0.000></$lime><$light_gray> / </$light_gray><$azure><2:0.000></$azure><$light_gray>

# Generic Display GUI

gui.display_entity.delete.name=<$red>Delete Display</$red>
gui.display_entity.delete.lore=\
  <$light_gray>Delete the Display Entity</$light_gray>\n\n\
  $NOTE<$yellow>NOTE</$yellow> $NOTE\n\
   <$light_gray>This action is irreversible</$light_gray>\n\n\
  $LMB <$white_gray>Click to Delete</$white_gray>


gui.display_entity.duplicate.name=<$yellow>Duplicate Display</$yellow>
gui.display_entity.duplicate.lore=\
  <$light_gray>Duplicate the Display Entity</$light_gray>\n\n\
  $LMB <$white_gray>Click to Duplicate</$white_gray>

gui.display_entity.deselect.name=<$yellow>Deslect Display</$yellow>
gui.display_entity.deselect.lore=\
  <$light_gray>Deselect the Display Entity</$light_gray>\n\n\
  $LMB <$white_gray>Click to Deselect</$white_gray>

gui.display_entity.teleport.name=<$yellow>Teleport to Display</$yellow>
gui.display_entity.teleport.lore=\
  <$light_gray>Teleport to the Display Entity</$light_gray>\n\n\
  $LMB <$white_gray>Click to Teleport</$white_gray>

gui.display_entity.no_results=<$red>No Results</$red>
gui.display_entity.invalid_number=$DENY<$light_gray>Invalid Number Inputted</$light_gray>

gui.display_entity.properties.billboard.fixed.name=<$white>Set Billboard</$white>
gui.display_entity.properties.billboard.fixed.lore=\
  <$dark_gray> »</$dark_gray> <$lime>Fixed</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Vertical</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Horizontal</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Center</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.billboard.vertical.name=<$white>Set Billboard</$white>
gui.display_entity.properties.billboard.vertical.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Vertical</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Horizontal</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Center</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.billboard.horizontal.name=<$white>Set Billboard</$white>
gui.display_entity.properties.billboard.horizontal.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Vertical</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Horizontal</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Center</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.billboard.center.name=<$white>Set Billboard</$white>
gui.display_entity.properties.billboard.center.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Vertical</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Horizontal</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Center</$lime>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

# Block Display GUI

gui.display_entity.properties.block.name=<$white>Set Display Block</$white>
gui.display_entity.properties.block.lore=\
  <$light_gray>Current: </$light_gray><$light_blue><0></$light_blue>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>

gui.display_entity.properties.block_properties.entry=<$dark_gray> »</$dark_gray> <$light_gray><0></$light_gray>
gui.display_entity.properties.block_properties.entry.selected=<$dark_gray> »</$dark_gray> <$lime><0></$lime>
gui.display_entity.properties.block_properties.entry.cycle=$LMB <$white_gray>Click to Cycle</$white_gray>
gui.display_entity.properties.block_properties.entry.reset=$SHIFT_LMB <$white_gray>Shift + Click to Reset</$white_gray>

# Item Display GUI

gui.display_entity.properties.item.name=<$white>Set Display Item</$white>
gui.display_entity.properties.item.lore=\
  <$light_gray>Current: </$light_gray><$light_blue><0></$light_blue>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>

gui.display_entity.properties.item.context.none.name=<$white>Set Display Context</$white>
gui.display_entity.properties.item.context.none.lore=\
  <$dark_gray> »</$dark_gray> <$lime>None</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Head</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>GUI</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Ground</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.item.context.third_person_left_hand.name=<$white>Set Display Context</$white>
gui.display_entity.properties.item.context.third_person_left_hand.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>None</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Third Person Left Hand</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Head</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>GUI</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Ground</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.item.context.third_person_right_hand.name=<$white>Set Display Context</$white>
gui.display_entity.properties.item.context.third_person_right_hand.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>None</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Third Person Right Hand</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Head</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>GUI</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Ground</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.item.context.first_person_left_hand.name=<$white>Set Display Context</$white>
gui.display_entity.properties.item.context.first_person_left_hand.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>None</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>First Person Left Hand</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Head</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>GUI</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Ground</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.item.context.first_person_right_hand.name=<$white>Set Display Context</$white>
gui.display_entity.properties.item.context.first_person_right_hand.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>None</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>First Person Right Hand</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Head</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>GUI</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Ground</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.item.context.head.name=<$white>Set Display Context</$white>
gui.display_entity.properties.item.context.head.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>None</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Head</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>GUI</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Ground</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.item.context.gui.name=<$white>Set Display Context</$white>
gui.display_entity.properties.item.context.gui.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>None</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Head</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>GUI</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Ground</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.item.context.ground.name=<$white>Set Display Context</$white>
gui.display_entity.properties.item.context.ground.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>None</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Head</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>GUI</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Ground</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Fixed</$light_gray>\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.item.context.fixed.name=<$white>Set Display Context</$white>
gui.display_entity.properties.item.context.fixed.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>None</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Third Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Left Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>First Person Right Hand</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Head</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>GUI</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Ground</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Fixed</$lime>\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.item_components.entry=<$dark_gray> »</$dark_gray> <$light_gray><0></$light_gray>
gui.display_entity.properties.item_components.entry.selected=<$dark_gray> »</$dark_gray> <$lime><0></$lime>
gui.display_entity.properties.item_components.entry.cycle=$LMB <$white_gray>Click to Cycle</$white_gray>
gui.display_entity.properties.item_components.entry.reset=$SHIFT_LMB <$white_gray>Shift + Click to Reset</$white_gray>

gui.display_entity.properties.item_components.type.minecraft.enchantment_glint_override.name=<$white>Enchantment Glint</$white>

# Text Display GUI

gui.display_entity.properties.text.name=<$white>Set Display Text</$white>
gui.display_entity.properties.text.lore=\
  <$light_gray>Current: </$light_gray><$light_blue>"<0>"</$light_blue>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Remove Line</$white_gray>

gui.display_entity.properties.text.alignment.centered.name=<$white>Set Text Alignment</$white>
gui.display_entity.properties.text.alignment.centered.lore=\
  <$dark_gray> »</$dark_gray> <$lime>Centered</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Left</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Right</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.text.alignment.left.name=<$white>Set Text Alignment</$white>
gui.display_entity.properties.text.alignment.left.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>Centered</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Left</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Right</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.text.alignment.right.name=<$white>Set Text Alignment</$white>
gui.display_entity.properties.text.alignment.right.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>Centered</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Left</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Right</$lime>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.text.shadow.true.name=<$white>Set Text Shadow</$white>
gui.display_entity.properties.text.shadow.true.lore=\
  <$dark_gray> »</$dark_gray> <$lime>True</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>False</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.text.shadow.false.name=<$white>Set Text Shadow</$white>
gui.display_entity.properties.text.shadow.false.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>True</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>False</$lime>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.text.background.true.name=<$white>Set Text Background</$white>
gui.display_entity.properties.text.background.true.lore=\
  <$dark_gray> »</$dark_gray> <$lime>True</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>False</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.text.background.false.name=<$white>Set Text Background</$white>
gui.display_entity.properties.text.background.false.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>True</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>False</$lime>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.text.see_through.true.name=<$white>Set Text See-Through</$white>
gui.display_entity.properties.text.see_through.true.lore=\
  <$dark_gray> »</$dark_gray> <$lime>True</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>False</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.text.see_through.false.name=<$white>Set Text See-Through</$white>
gui.display_entity.properties.text.see_through.false.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>True</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>False</$lime>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.display_entity.properties.text.header=<$white>Editing line <0> of <1></$white>
gui.display_entity.properties.text.entry=<$dark_gray> »</$dark_gray> <$light_gray>"<0>"</$light_gray>
gui.display_entity.properties.text.entry.selected=<$dark_gray> »</$dark_gray> <$lime>"<0>"</$lime>
gui.display_entity.properties.text.entry.cycle=$LMB <$white_gray>Click to Cycle</$white_gray>
gui.display_entity.properties.text.entry.add=$SHIFT_LMB <$white_gray>Shift + Click to Add Line</$white_gray>

# Searching Display GUI

gui.display_entity.search.entry.name=<$white><0:0.00>m Away</$white>
gui.display_entity.search.entry.lore=\
  <$light_gray>Type: </$light_gray><$yellow><1></$yellow>\n\n\
  <$light_gray>Current: </$light_gray><$light_blue><2></$light_blue>\n\n\
  $LMB <$white_gray>Click to Select</$white_gray>