# THESE ICONS MAY BE USED IN DISPLAY ENTITIES, THEY MAY NOT EVER BE MODIFIED AFTER CREATION.
# IF YOU NEED A VARIATION YOU MUST CREATE A NEW TRANSLATION KEY.

icon.coins=$COINS
icon.cubits=$CUBITS
icon.hypercube_gold=$HYPERCUBE
icon.lmb=$LMB
icon.shift_lmb=$SHIFT_LMB
icon.rmb=$RMB
icon.shift_rmb=$SHIFT_RMB

# THESE ICONS MAY BE USED IN DISPLAY ENTITIES, THEY MAY NOT EVER BE MODIFIED AFTER CREATION.
# IF YOU NEED A VARIATION YOU MUST CREATE A NEW TRANSLATION KEY.
