# Items

item.mapmaker.checkpoint_plate.name=<$white>Checkpoint Plate</$white>
item.mapmaker.checkpoint_plate.lore=\
  <$light_gray>When activated, failing or falling below a certain</$light_gray>\n\
  <$light_gray>height (Y-level) will result in the player teleporting back.</$light_gray>
item.mapmaker.checkpoint_plate.with_data.lore=\
  <$light_gray>Reset Height: <0></$light_gray>\n\n\
  <$light_gray>When activated, failing or falling below a certain</$light_gray>\n\
  <$light_gray>height (Y-level) will result in the player teleporting back.</$light_gray>

gui.checkpoint.pick_up.name=<$white>Pick Up Checkpoint</$white>
gui.checkpoint.pick_up.lore=<$light_gray>Pick up this Checkpoint as an item</$light_gray>\n\
  <$light_gray>to place it elsewhere in your map.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Copy</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Cut</$white_gray>

gui.checkpoint.tab_settings.name=<$white>Settings</$white>
gui.checkpoint.tab_actions.name=<$white>Actions</$white>

# Name
gui.effect.name.name=<$white>Name</$white>

# Progress Index
gui.effect.progress_index.name=<$white>Progress Index</$white>

# Lives
gui.checkpoint.lives.name=<$white>Lives <3</$white>
gui.checkpoint.lives.lore=Current: <0>\ntodo put heart icon in the \nname to say its there perhaps
gui.checkpoint.lives.none=None

# Time Limit
gui.effect.time_limit.name=<$white>Time Limit</$white>
gui.effect.time_limit.lore=Current: <0>
gui.effect.time_limit.none=None

# Reset Height
gui.effect.reset_height.name=<$white>Reset Height</$white>
gui.effect.reset_height.lore=<$light_gray>Current: <0></$light_gray>\n\n\
  <$light_gray>Falling under this defined Y-level will</$light_gray>\n\
  <$light_gray>return the player to this checkpoint.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.effect.reset_height.none=Inherited

# Add Effects
gui.effect.actions.potion_effects.name=<$white>Potion Effects</$white>
gui.effect.actions.potion_effects.header=Current:
gui.effect.actions.potion_effects.entry=> <0> <1> for <2>
gui.effect.actions.potion_effects.footer=Click to edit

# Clear Effects
gui.effect.actions.clear_effects.name=<$white>Clear Potion Effects</$white>
gui.effect.actions.clear_effects.lore=Current: <0>
gui.effect.actions.clear_effects.enabled=Enabled
gui.effect.actions.clear_effects.disabled=Disabled

# Teleport
gui.effect.actions.teleport.name=<$white>Teleport to Coordinates</$white>
gui.effect.actions.teleport.lore=Current: <0>
gui.effect.actions.teleport.none=Disabled
gui.effect.actions.teleport.pos=<0>, <1>, <2> (<3>, <4>)

# Settings
gui.effect.actions.settings.name=<$white>Toggle Map Settings</$white>
gui.effect.actions.settings.lore=todo later

# Add Item
gui.effect.actions.add_item.name=<$white>Give Item</$white>
gui.effect.actions.add_item.lore=todo later

# Remove Item
gui.effect.actions.remove_item.name=<$white>Remove Item</$white>
gui.effect.actions.remove_item.lore=todo later

# Repeatable (Status Only)
gui.status.repeatable.name=<$white>Repeatable</$white>
gui.status.repeatable.lore=Current: <0>
gui.status.repeatable.enabled=Enabled
gui.status.repeatable.disabled=Disabled

# Add/Extra Time (Status Only)
gui.effect.actions.add_time.name=<$white>Extra Time</$white>
gui.effect.actions.add_time.lore=Current: <0>
gui.effect.actions.add_time.none=None
