gui.advent.information.name=<$yellow>Information</$yellow>
gui.advent.information.lore=\
<$light_gray>Every day, a new present will be available to find in</$light_gray>\n\
<$light_gray>our Christmas lobby! Hints will be available for each</$light_gray>\n\
<$light_gray>present a day after they come out. Collect enough to</$light_gray>\n\
<$light_gray>receive some limited-time cosmetics. Merry Christmas!</$light_gray>

gui.advent.day.name=<$white>Day <0></$white>
gui.advent.day.name.collected=<$white>Day <0> (Collected)</$white>
gui.advent.day.lore=<$white_gray>Hint:</$white_gray> <$white><0></$white>

gui.advent.day.1.lore=\
<$lime>Freebie!</$lime> <$light_gray>Next to the Advent NPC left of spawn.</$light_gray>\n\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><1>
gui.advent.day.5.lore=\
<$white_gray>Hint:</$white_gray> <$light_blue><0></$light_blue>\n\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><1>
gui.advent.day.10.lore=\
<$white_gray>Hint:</$white_gray> <$light_blue><0></$light_blue>\n\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><1>
gui.advent.day.15.lore=\
<$white_gray>Hint:</$white_gray> <$light_blue><0></$light_blue>\n\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><1>
gui.advent.day.20.lore=\
<$white_gray>Hint:</$white_gray> <$light_blue><0></$light_blue>\n\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><1>
gui.advent.day.25.lore=\
<$white_gray>Hint:</$white_gray> <$light_blue><0></$light_blue>\n\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><1>

gui.advent.day.hint=??? (Unlocks in <0>)

advent.present.found=$INFO<$light_gray>You <$white>found a present!</$white> View your progress with <$white>/advent</$white>.</$light_gray>
advent.present.already_found=$INFO<$light_gray>You <$white>already found</$white> this <$white>present</$white>!</$light_gray>
advent.present.found_cosmetic=$INFO<$light_gray>You <$white>found a present!</$white> and got an </$light_gray><0><$light_gray>! View it in <$white>/cosmetics</$white>.</$light_gray>

advent.not_available=$INFO<$light_gray>The Advent Calendar is not available right now. It will be available from <$white>December 1st</$white> to <$white>December 31st</$white>.</$light_gray>