gui.advent.information.name=<$yellow>Information</$yellow>
gui.advent.information.lore=\
<$light_gray>Every day, a new present will be available to find in</$light_gray>\n\
<$light_gray>our Christmas lobby! Hints will be available for each</$light_gray>\n\
<$light_gray>present a day after they come out. Collect enough to</$light_gray>\n\
<$light_gray>receive some limited-time cosmetics. Merry Christmas!</$light_gray>\n\n\
<$white_gray>Available from <$white>December 1st</$white> to <$white>January 10th</$white>.</$white_gray>

gui.advent.day.name=<$white>Day <0></$white>
gui.advent.day.name.collected=<$white>Day <0> (Collected)</$white>
gui.advent.day.lore.hint=<$white_gray>Hint:</$white_gray> <$white><0></$white>
gui.advent.day.locked=<$red>Locked</$red> <$light_gray>- Available in <$white><0></$white></$light_gray>

gui.advent.day.hint.lore=<$white_gray>Hint:</$white_gray> <$white><0></$white>
gui.advent.day.1.rewards.lore=\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><0>
gui.advent.day.5.rewards.lore=\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><0>\n\
<$white_gray>  \u2022 Requires <$white>5</$white> presents to unlock.</$white_gray>
gui.advent.day.10.rewards.lore=\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><0>\n\
<$white_gray>  \u2022 Requires <$white>10</$white> presents to unlock.</$white_gray>
gui.advent.day.15.rewards.lore=\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><0>\n\
<$white_gray>  \u2022 Requires <$white>15</$white> presents to unlock.</$white_gray>
gui.advent.day.20.rewards.lore=\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><0>\n\
<$white_gray>  \u2022 Requires <$white>20</$white> presents to unlock.</$white_gray>
gui.advent.day.25.rewards.lore=\
<$white_gray>Reward:</$white_gray>\n\
<$light_gray> - </$light_gray><0>\n\
<$white_gray>  \u2022 Requires <$white>25</$white> presents to unlock.</$white_gray>


gui.advent.day.hint=??? (Reveals in <0>)
gui.advent.day.1.hint=Next to the Advent NPC left of spawn.
gui.advent.day.2.hint=Rudolph the Red-Nosed Reindeer
gui.advent.day.3.hint=Sweet tooth!
gui.advent.day.4.hint=Target practice!
gui.advent.day.5.hint=Sure is cramped in here... as small as a new york apartment!
gui.advent.day.6.hint=Weewoo, weewoo, weewoo!
gui.advent.day.7.hint=Hold your nose.
gui.advent.day.8.hint=Sweet dreams.
gui.advent.day.9.hint=$SUS
gui.advent.day.10.hint=Cyberware, strictly off the books.\nCheck the stalls to find the spot.
gui.advent.day.11.hint=<red>DO NOT PRESS.</red>
gui.advent.day.12.hint=The reception's great up here!
gui.advent.day.13.hint=Seeking enlightenment?
gui.advent.day.14.hint=Company branding.
gui.advent.day.15.hint=Rest in pieces.
gui.advent.day.16.hint=Within the castle walls, a clear line\nof sight to the throne marks the Crown's fall.
gui.advent.day.17.hint=Up the corporate ladder
gui.advent.day.18.hint=Don't leave me hanging!
gui.advent.day.19.hint=Where the neon reaches for the clouds.
gui.advent.day.20.hint=To the moon!
gui.advent.day.21.hint=Where the ice melts.
gui.advent.day.22.hint=Technoblade never dies!
gui.advent.day.23.hint=pack.png
gui.advent.day.24.hint=<italic>Sniff sniff...</italic> That smells good!
gui.advent.day.25.hint=From: Santa Claus

advent.present.found=$INFO<$light_gray>You <$white>found a present!</$white> View your progress with <$white>/advent</$white>.</$light_gray>
advent.present.already_found=$INFO<$light_gray>You <$white>already found</$white> this <$white>present</$white>!</$light_gray>
advent.present.too_far=$WARNING<$light_gray> You are too far away from the <$white>present</$white> to collect it. Get closer!</$light_gray>
advent.present.found_cosmetic=$INFO<$light_gray>You <$white>found a present!</$white> and got an </$light_gray><0><$light_gray>! View it in <$white>/cosmetics</$white>.</$light_gray>

advent.not_available=$INFO<$light_gray>The Advent Calendar is not available right now. It will be available from <$white>December 1st</$white> to <$white>January 10th</$white>.</$light_gray>

item.mapmaker.advent_calendar.name=<$red>Advent Calendar</$red> $RMB_ITEM
item.mapmaker.advent_calendar.lore=\
  <$light_gray>Every day in December, find a new present</$light_gray>\n\
  <$light_gray>hidden around the lobby to collect limited-time</$light_gray>\n\
  <$light_gray>cosmetics! Use this to track your progress.</$light_gray>

new_years.message=$MEGAPHONE<gradient:#d19e1d:#ffd86e:#e3a812:#ffd86e:#d19e1d>Happy New Years</gradient> <$white_gray>to</$white_gray> <$azure><0></$azure><$white_gray>!</$white_gray>