#
# Generic GUIs
#

forced.input.name=<0>
gui.generic.empty.name=
gui.generic.back_arrow.name=<$red>Go Back</$red>
gui.generic.close_menu.name=<$red>Close Menu</$red>
gui.generic.information.name=<$yellow>Information</$yellow>
gui.generic.previous_page.name=<$white>Previous Page</$white>
gui.generic.next_page.name=<$white>Next Page</$white>
gui.generic.page.name=<$white>Page <0></$white>
gui.generic.page_and_max.name=<$white>Page <0> of <1></$white>
gui.generic.coming_soon.lore=<$red>Coming Soon!</$red>
gui.generic.loading.name=<$light_gray>Loading...</$light_gray>
# 0: Page Number
gui.generic.page_number.name=<$white>Page <0></$white>
gui.generic.confirmation.yes.name=<$lime>Yes</$lime>
gui.generic.confirmation.no.name=<$red>No</$red>
gui.generic.no_line.lore=<$dark_gray> </$dark_gray>
# 0: Click Action Result
gui.generic.click_to_select.lore=$LMB <$white_gray>Click to Select</$white_gray>
gui.generic.click_to_change.lore=$LMB <$white_gray>Click to Change</$white_gray>
gui.generic.shift_click_to_remove.lore=$SHIFT_LMB <$white_gray>Shift + Click to Remove</$white_gray>
gui.generic.left_click.lore=$LMB <$light_gray>Click to <0></$light_gray>
gui.generic.shift_left_click.lore=$SHIFT_LMB <$light_gray>Shift + Click to <0></$light_gray>
gui.generic.right_click.lore=$RMB <$light_gray>Click to <0></$light_gray>
gui.generic.shift_right_click.lore=$SHIFT $RMB <$light_gray>Click to <0></$light_gray>
gui.generic.click_to_cycle.lore=$LMB <$light_gray>Click to Cycle</$light_gray>

#
# Confirm Action GUI
#

gui.confirm.no.name=<$red>No</$red>
gui.confirm.no.lore=\
  <$light_gray>Cancel and return to the previous menu.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Go Back</$light_gray>
gui.confirm2.no.name=<$red>No</$red>
gui.confirm2.no.lore=$LMB <$light_gray>Click to Go Back</$light_gray>
# 0: What you are confirming. For example: "Verify you want to Delete your map MOST EPIC PARKOUR EVER WOW!!!"
gui.confirm.yes.name=<$lime>Yes</$lime>
gui.confirm.yes.lore=\
  <$light_gray>Verify you want to <0>.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Confirm</$light_gray>
gui.confirm2.yes.name=<$lime>Yes</$lime>
gui.confirm2.yes.lore=$LMB <$light_gray>Click to Confirm</$light_gray>

#
# Constant
#

# 0: Player name
mapmaker.welcome_message=$INFO<$light_gray>Welcome <$white><0></$white> to <$azure>Map Maker</$azure>!</$light_gray>
command.discord=$INFO<$white_gray>Join our Discord to interact with our community and staff, see server updates, and more:</$white_gray> <$azure><click:open_url:https://discord.hollowcube.net>discord.hollowcube.net</click></$azure>
command.store=$INFO<$light_gray>Visit our Store to help support our development:</$light_gray> <$azure>https://store.hollowcube.net</$azure>
# Generic (reused between many commands)
generic.player.only=$DENY<$light_gray>Only <$white>players</$white> can use this command!</$light_gray>
generic.no_permission=$DENY<$light_gray>You don't have <$white>permission</$white> to use that command!<$/light_gray>
generic.other_players_only=$DENY<$light_gray>You can only use this command on <$white>other players</$white>!</$light_gray>
# 0: Player name
generic.player.offline=$DENY<$light_gray><$white><0></$white> is not online!</$light_gray>
generic.player.name_length=$DENY<$light_gray> You must enter a player name that is between <$white>3 and 16 characters</$white>!</$light_gray>
# 0: Error string
generic.unknown_error=$DENY<$light_gray>An <$white>unknown error</$white> occurred, please try again later! If this issue persists, please contact an <$red>Administrator</$red>.</$light_gray>
generic.disabled_command=$DENY<$light_gray>This command is <$white>disabled</$white> for now.</$light_gray>
# 0: Proper command argument syntax
generic.wrong_syntax=$WARNING<$light_gray>Wrong syntax! Use <$white><0></$white></$light_gray>
# 0: Lowest possible enterable value
# 1: Highest possible enterable value
generic.number.not_in_range=$DENY<$light_gray>Only numbers <$white>between <0> <$light_gray>and</$light_gray> <1></$white> are accepted!</$light_gray>
generic.number.only_int=$DENY<$light_gray>You can only enter <$white>numbers</$white>!</$light_gray>
# 0: Player's ping
generic.command.ping=$INFO<$light_gray>Your ping is <$white><0>ms</$white>.</$light_gray>
generic.feature.unreleased=$DENY<$light_gray>This feature is <$white>coming later</$white>!</$light_gray>
command.not_found=$DENY<$light_gray>That command <$white>doesn't exist</$white>!</$light_gray>
generic.command.not_found=$DENY<$light_gray>That command <$white>doesn't exist</$white>!</$light_gray>
generic.map.edit.fail=$DENY<$light_gray>Failed to edit your map, please try again later! If this issue persists, please contact an <$red>Administrator</$red>.</$light_gray>
generic.map.verify.fail=$DENY<$light_gray>Failed to verify your map, please try again later! If this issue persists, please contact an <$red>Administrator</$red>.</$light_gray>
generic.map.chat.usage=$DENY<$light_gray>To use [map] in chat you need to be in a published map.</$light_gray>
generic.map.closed=$DENY<$light_gray>The map you were in has been <$white>closed</$white>!</$light_gray>
generic.map.closed.reason=$DENY<$light_gray>The map you were in has been <$white>closed</$white>: <$white><0></$white></$light_gray>
generic.command.blocked_by_target=$WARNING<$light_gray>You cannot do this as you are blocked by <$white><0></$white>!</$light_gray>
generic.command.blocked_by_self=$WARNING<$light_gray>You cannot do this as you have blocked <$white><0></$white>!</$light_gray>

#
# Join/Leave
#

# 0: Player name
chat.player.join=$PLUS<0>
chat.friend.join=<$yellow>Friend</$yellow> <$dark_gray>» [<$lime>+</$lime>]</$dark_gray> <$white><0></$white>

# 0: Player name
chat.player.leave=$MINUS<0>
chat.friend.leave=<$yellow>Friend</$yellow> <$dark_gray>» [<$dark_red><bold>-</bold></$dark_red>]</$dark_gray> <$white><0></$white>

#
# Limits
#

chat.cooldown=$DENY<$light_gray><$white>Slow down</$white>, don't chat so fast!</$light_gray>
chat.censored=$DENY<$light_gray>Your chat was <$white>censored</$white> for containing bad language! If this was a false positive, please make a bug report in our /discord.</$light_gray>

#
# Moderation
#

# 0: The staff member that cleared the chat
command.moderation.clear_chat=$CONFIRM<$light_gray>The <$white>chat</$white> was <$white>cleared</$white> by <0>!</$light_gray>
command.moderation.vanish_enabled=$CONFIRM<$light_gray><$white>Vanish enabled.</$white> You are now hidden from all normal players.</$light_gray>
command.moderation.vanish_disabled=$CONFIRM<$light_gray><$white>Vanish disabled.</$white> You are now shown for all players again.</$light_gray>
ff.maps_disabled=$DENY<$light_gray>Maps are currently <$white>disabled</$white>. Explore the lobby in the meantime!</$light_gray>


#
# Time Component
#

time.hover=<$light_gray><0></$light_gray>

time.now=just now
time.second.future=a second
time.second.past=a second ago
time.seconds.future=<0> seconds
time.seconds.past=<0> seconds ago
time.minute.future=a minute
time.minute.past=a minute ago
time.minutes.future=<0> minutes
time.minutes.past=<0> minutes ago
time.hour.future=an hour
time.hour.past=an hour ago
time.hours.future=<0> hours
time.hours.past=<0> hours ago
time.day.future=a day
time.day.past=a day ago
time.days.future=<0> days
time.days.past=<0> days ago
time.week.future=a week
time.week.past=a week ago
time.weeks.future=<0> weeks
time.weeks.past=<0> weeks ago
time.month.future=a month
time.month.past=a month ago
time.months.future=<0> months
time.months.past=<0> months ago
time.year.future=a year
time.year.past=a year ago
time.years.future=<0> years
time.years.past=<0> years ago