###
### Common keys
###

gui.action.information.name=<$yellow>Information</$yellow>
gui.action.information.lore=\
  <$light_gray>A list of actions to execute when</$light_gray>\n\
  <$light_gray>the player steps on this plate.</$light_gray>

gui.action.custom_blocks.name=<$white>Custom Blocks</$white>
gui.action.custom_blocks.lore=\
  <$light_gray>View all Custom Blocks placed in this map.</$light_gray>\n\
  <$light_gray>Useful for if you want to edit their properties from</$light_gray>\n\
  <$light_gray>afar or teleport to one in case you forgot its location.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.action.search.empty.name=<$white>Search Actions</$white>
gui.action.search.empty.lore=\
  <$light_gray>Find an action by its name.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Search</$light_gray>
gui.action.search.name=<$white>Search Actions</$white>
gui.action.search.lore=\
  <$light_gray>Find any map by its name.</$light_gray>\n\n\
  <$light_gray>Current:</$light_gray> <0>\n\n\
  $LMB <$light_gray>Click to Search</$light_gray>\n\
  $SHIFT_LMB <$light_gray>Shift + Click to Reset</$light_gray>

gui.action.add.name=<$white>Add Action</$white>

gui.action.clickselect=\n\
  $LMB <$white_gray>Click to Select</$white_gray>
gui.action.clickedit=\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
gui.action.clickeditorremove=\n\
  $LMB <$white_gray>Click to Edit</$white_gray>\n\
  $RMB <$white_gray>Click to Remove</$white_gray>
gui.action.unavailable=\n\
  <$red>Not Available</$red>



###
### Timer action
###

gui.action.timer.title=Player Time Limit

gui.action.timer.info.name=<$yellow>Information</$yellow>
gui.action.timer.info.lore=\
  <$light_gray>A countdown timer that resets a player back</$light_gray>\n\
  <$light_gray>to their last checkpoint when it runs out.</$light_gray>

gui.action.timer.subtitle.set=Set Time
gui.action.timer.subtitle.add=Add Time
gui.action.timer.subtitle.subtract=Subtract Time

gui.action.timer.operation.name=<$white>Timer Operation</$white>
gui.action.timer.operation.lore=\
  <$light_gray>Choose the operation to perform on the</$light_gray>\n\
  <$light_gray>player's countdown timer.</$light_gray>

gui.action.timer.set.label=Set
gui.action.timer.set.label.name=<$white>Set Timer</$white>
gui.action.timer.set.label.lore=\
  <$light_gray>Directly sets the countdown timer. Will overwrite</$light_gray>\n\
  <$light_gray>any current timer value that a player has.</$light_gray>
gui.action.timer.add.label=Add
gui.action.timer.add.label.name=<$white>Add Time to Timer</$white>
gui.action.timer.add.label.lore=\
  <$light_gray>Adds time to the player's countdown timer. Will start</$light_gray>\n\
  <$light_gray>a timer with the given value if none is present.</$light_gray>
gui.action.timer.subtract.label=Sub.
gui.action.timer.subtract.label.name=<$white>Subtract Time From Timer</$white>
gui.action.timer.subtract.label.lore=\
  <$light_gray>Subtracts time from the player's countdown timer.</$light_gray>\n\
  <$light_gray>Will reset a player if the timer goes to zero</$light_gray>\n\
  <$light_gray>or below. Does nothing if no timer is present.</$light_gray>

gui.action.timer.value.set=time to set
gui.action.timer.value.set.name=<$white>Time to Set</$white>
gui.action.timer.value.add=time to add
gui.action.timer.value.add.name=<$white>Time to Add</$white>
gui.action.timer.value.subtract=time to subtract
gui.action.timer.value.subtract.name=<$white>Time to Subtract</$white>

gui.action.timer.value.minus.name=<$white>Subtract Time</$white>
gui.action.timer.value.minus.lore=\n\
  $LMB <$white_gray>Click to Remove 1 Second</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Remove 5 Seconds</$white_gray>
gui.action.timer.value.plus.name=<$white>Add Time</$white>
gui.action.timer.value.plus.lore=\n\
  $LMB <$white_gray>Click to Add 1 Second</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Add 5 Seconds</$white_gray>

gui.action.timer.thumbnail.empty.name=<$white>Player Timer</$white>
gui.action.timer.thumbnail.name=<$white>Player Timer</$white>
gui.action.timer.thumbnail.lore=\
  <$light_gray>Operation: <$white><0>\n\
  <$light_gray>Time: <$white><1>



###
### Lives action
###

gui.action.lives.title=Player Lives

gui.action.lives.info.name=<$yellow>Information</$yellow>
gui.action.lives.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.lives.subtitle.set=Set Lives
gui.action.lives.subtitle.add=Add Lives
gui.action.lives.subtitle.subtract=Subtract Lives

gui.action.lives.operation.name=<$white>Lives Operation</$white>
gui.action.lives.operation.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.lives.set.label=Set
gui.action.lives.set.label.name=<$white>Set Lives</$white>
gui.action.lives.set.label.lore=\
  <$light_gray>SETH</$light_gray>
gui.action.lives.add.label=Add
gui.action.lives.add.label.name=<$white>Add Lives</$white>
gui.action.lives.add.label.lore=\
  <$light_gray>SETH</$light_gray>
gui.action.lives.subtract.label=Sub.
gui.action.lives.subtract.label.name=<$white>Subtract Lives</$white>
gui.action.lives.subtract.label.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.lives.value.set=lives to set
gui.action.lives.value.set.name=<$white>Lives to Set</$white>
gui.action.lives.value.add=lives to add
gui.action.lives.value.add.name=<$white>Lives to Add</$white>
gui.action.lives.value.subtract=lives to subtract
gui.action.lives.value.subtract.name=<$white>Lives to Subtract</$white>

gui.action.lives.value.minus.name=<$white>Subtract Lives</$white>
gui.action.lives.value.minus.lore=\n\
  $LMB <$white_gray>Click to Remove 1 Life</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Remove 5 Lives</$white_gray>
gui.action.lives.value.plus.name=<$white>Add Lives</$white>
gui.action.lives.value.plus.lore=\n\
  $LMB <$white_gray>Click to Add 1 Life</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Add 5 Lives</$white_gray>

gui.action.lives.thumbnail.empty.name=<$white>Player Lives</$white>
gui.action.lives.thumbnail.name=<$white>Player Lives</$white>
gui.action.lives.thumbnail.lore=\
  <$light_gray>Operation: <$white><0>\n\
  <$light_gray>Lives: <$white><1>



###
### ADD POTION EFFECT
###

gui.action.add_potion.title=Add Potion Effect

gui.action.add_potion.info.name=<$yellow>Information</$yellow>
gui.action.add_potion.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.add_potion.level=potion level
gui.action.add_potion.level.name=<$white>Potion Level</$white>
gui.action.add_potion.level.minus.name=<$white>Subtract Levels</$white>
gui.action.add_potion.level.minus.lore=\n\
  $LMB <$white_gray>Click to Remove 1 Level</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Remove 5 Levels</$white_gray>
gui.action.add_potion.level.plus.name=<$white>Add Levels</$white>
gui.action.add_potion.level.plus.lore=\n\
  $LMB <$white_gray>Click to Add 1 Level</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Add 5 Levels</$white_gray>

gui.action.add_potion.duration=potion duration
gui.action.add_potion.duration.name=<$white>Potion Duration</$white>
gui.action.add_potion.duration.minus.name=<$white>Subtract Time</$white>
gui.action.add_potion.duration.minus.lore=\n\
  $LMB <$white_gray>Click to Remove 1 Seconds</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Remove 5 Seconds</$white_gray>
gui.action.add_potion.duration.plus.name=<$white>Add Time</$white>
gui.action.add_potion.duration.plus.lore=\n\
  $LMB <$white_gray>Click to Add 1 Second</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Add 5 Seconds</$white_gray>

gui.action.add_potion.thumbnail.empty.name=<$white>Add Potion Effect</$white>
gui.action.add_potion.thumbnail.empty.lore=\
  <$light_gray>No potion effect selected. This action</$light_gray>\n\
  <$light_gray>will have no effect.</$light_gray>
gui.action.add_potion.thumbnail.name=<$white>Add Potion Effect</$white>
gui.action.add_potion.thumbnail.lore=\
  <$light_gray>Potion Effect: <$white><0>\n\
  <$light_gray>Level: <$white><1>\n\
  <$light_gray>Duration: <$white><2>



###
### REMOVE POTION EFFECT
###

gui.action.remove_potion.title=Remove Potion Effect

gui.action.remove_potion.info.name=<$yellow>Information</$yellow>
gui.action.remove_potion.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.remove_potion.clear.name=<$white>Clear All Effects</$white>
gui.action.remove_potion.clear.lore=\
  <$light_gray>Removes all potion effects from the player.</$light_gray>

gui.action.remove_potion.thumbnail.clear.name=<$white>Clear Potion Effects</$white>
gui.action.remove_potion.thumbnail.clear.lore=\
  <$light_gray>Removes all potion effects from the player.</$light_gray>
gui.action.remove_potion.thumbnail.name=<$white>Remove Potion Effect</$white>
gui.action.remove_potion.thumbnail.lore=\
  <$light_gray>Potion Effect: <$white><0>



###
### TELEPORT
###

gui.action.teleport.title=Teleport

gui.action.teleport.info.name=<$yellow>Information</$yellow>
gui.action.teleport.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.teleport.x=x
gui.action.teleport.x.name=<$white>X Coordinate</$white>
gui.action.teleport.y=y
gui.action.teleport.y.name=<$white>Y Coordinate</$white>
gui.action.teleport.z=x
gui.action.teleport.z.name=<$white>Z Coordinate</$white>
gui.action.teleport.yaw=yaw
gui.action.teleport.yaw.name=<$white>Yaw Angle</$white>
gui.action.teleport.yaw.lore=\
  <$light_gray>Horizontal rotation.</$light_gray>
gui.action.teleport.pitch=pitch
gui.action.teleport.pitch.name=<$white>Pitch Angle</$white>
gui.action.teleport.pitch.lore=\
  <$light_gray>Vertical rotation.</$light_gray>

gui.action.teleport.command.name=<$white>Teleport Command</$white>
gui.action.teleport.command.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.teleport.thumbnail.empty.name=<$white>Teleport</$white>
gui.action.teleport.thumbnail.name=<$white>Teleport</$white>
gui.action.teleport.thumbnail.lore=\
  <$light_gray>X: <$white><0>\n\
  <$light_gray>Y: <$white><1>\n\
  <$light_gray>Z: <$white><2>\n\
  <$light_gray>Yaw: <$white><3>\n\
  <$light_gray>Pitch: <$white><4>



###
### ENABLE SETTING
###

gui.action.enable_setting.title=Enable Setting

gui.action.enable_setting.info.name=<$yellow>Information</$yellow>
gui.action.enable_setting.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.enable_setting.thumbnail.empty.name=<$white>Enable Setting</$white>
gui.action.enable_setting.thumbnail.empty.lore=\
  <$light_gray>No setting is selected. This action</$light_gray>\n\
  <$light_gray>will have no effect.</$light_gray>
gui.action.enable_setting.thumbnail.name=<$white>Enable Setting</$white>
gui.action.enable_setting.thumbnail.lore=\
  <$light_gray>Setting: <$white><0>



###
### TELEPORT
###

gui.action.disable_setting.title=Disable Setting

gui.action.disable_setting.info.name=<$yellow>Information</$yellow>
gui.action.disable_setting.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.disable_setting.thumbnail.empty.name=<$white>Disable Setting</$white>
gui.action.disable_setting.thumbnail.empty.lore=\
  <$light_gray>No setting is selected. This action</$light_gray>\n\
  <$light_gray>will have no effect.</$light_gray>
gui.action.disable_setting.thumbnail.name=<$white>Disable Setting</$white>
gui.action.disable_setting.thumbnail.lore=\
  <$light_gray>Setting: <$white><0>



###
### PROGRESS INDEX
###

gui.action.progress_index.title=Set Progress Index

gui.action.progress_index.info.name=<$yellow>Information</$yellow>
gui.action.progress_index.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.progress_index.thumbnail.clear.name=<$white>Set Progress Index</$white>
gui.action.progress_index.thumbnail.clear.lore=\
  <$light_gray>Disables the progress index functionality.<$white>
gui.action.progress_index.thumbnail.name=<$white>Set Progress Index</$white>
gui.action.progress_index.thumbnail.lore=\
  <$light_gray>Index: <$white><0>




###
### RESET HEIGHT
###

gui.action.reset_height.title=Set Reset Height

gui.action.reset_height.info.name=<$yellow>Information</$yellow>
gui.action.reset_height.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.reset_height.thumbnail.clear.name=<$white>Set Reset Height</$white>
gui.action.reset_height.thumbnail.clear.lore=\
  <$light_gray>Disables the reset height functionality.<$white>
gui.action.reset_height.thumbnail.name=<$white>Set Reset Height</$white>
gui.action.reset_height.thumbnail.lore=\
  <$light_gray>Reset below Y=<$white><0>



###
### GIVE ELYTRA
###

gui.action.give_elytra.title=Give Elytra

gui.action.give_elytra.info.name=<$yellow>Information</$yellow>
gui.action.give_elytra.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.give_elytra.thumbnail.name=<$white>Give Elytra</$white>



###
### TAKE ELYTRA
###

gui.action.take_elytra.title=Take Elytra

gui.action.take_elytra.info.name=<$yellow>Information</$yellow>
gui.action.take_elytra.info.lore=\
  <$light_gray>SETH</$light_gray>

gui.action.take_elytra.thumbnail.name=<$white>Take Elytra</$white>
