###
### Cycle Button
###
gui.generic.cycle.entry.unselected=<$dark_gray> » </$dark_gray><$light_gray><0></$light_gray>
gui.generic.cycle.entry.selected=<$dark_gray> » </$dark_gray><$lime><0></$lime>
gui.generic.cycle.action=$LMB <$white_gray>Click to Cycle</$white_gray>