gui.cosmetics.tab.coming_later=<$red>Coming Later!</$red>
gui.cosmetics.tab.select=$LMB <$white_gray>Click to View</$white_gray>

gui.cosmetics.filter.name=<$white>Filter By</$white>
gui.cosmetics.filter.unlocked=Owned
gui.cosmetics.filter.locked=All

gui.cosmetics.tab.hat.name=<$white>Headwear</$white>
gui.cosmetics.tab.hat.lore=<$light_gray>Hats to top off your character's style.</$light_gray>
gui.cosmetics.tab.backwear.name=<$white>Backwear</$white>
gui.cosmetics.tab.backwear.lore=<$light_gray>Modeled items carried on your back.</$light_gray>
gui.cosmetics.tab.accessory.name=<$white>Accessories</$white>
gui.cosmetics.tab.accessory.lore=<$light_gray>Hand-held items with special effects.</$light_gray>
gui.cosmetics.tab.pet.name=<$white>Companions</$white>
gui.cosmetics.tab.pet.lore=<$light_gray>Pets that follow your movement.</$light_gray>
gui.cosmetics.tab.emote.name=<$white>Emotes</$white>
gui.cosmetics.tab.emote.lore=<$light_gray>Express yourself with animated emotes.</$light_gray>
gui.cosmetics.tab.particle.name=<$white>Particles</$white>
gui.cosmetics.tab.particle.lore=<$light_gray>Special effects that appear around you.</$light_gray>
gui.cosmetics.tab.victory_effect.name=<$white>Victory Effects</$white>
gui.cosmetics.tab.victory_effect.lore=<$light_gray>Celebrate your map completions with fun visuals.</$light_gray>