gui.map_browser.simple.information.name=<$yellow>Information</$yellow>
gui.map_browser.simple.information.lore=\
  <$light_gray>Browse a catalogue of categorized maps, all created by</$light_gray>\n\
  <$light_gray>the community. Clicking the buttons at the bottom of this</$light_gray>\n\
  <$light_gray>menu will show recently published maps of that category.</$light_gray>

gui.map_browser.advanced_search.name=<$white>Toggle Complex Sorting</$white>
gui.map_browser.advanced_search.lore=\
  <$light_gray>Take control and search for maps by difficulty,</$light_gray>\n\
  <$light_gray>rating, tags, and more, as well as ordering them </$light_gray>\n\
  <$light_gray>by highest/lowest plays, completions, and so on.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.map_browser.sort_best.off.name=<$red>Best</$red>
gui.map_browser.sort_best.off.lore=\
  <$light_gray>The top maps on the server that have</$light_gray>\n\
  <$light_gray>withstood the test of time. Make sure</$light_gray>\n\
  <$light_gray>to play these before anything else!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Sort</$white_gray>
gui.map_browser.sort_best.on.name=<$red>Best</$red>
gui.map_browser.sort_best.on.lore=\
  <$light_gray>The top maps on the server that have</$light_gray>\n\
  <$light_gray>withstood the test of time. Make sure</$light_gray>\n\
  <$light_gray>to play these before anything else!</$light_gray>
gui.map_browser.sort_quality.off.name=<$light_blue>Quality</$light_blue>
gui.map_browser.sort_quality.off.lore=\
  <$light_gray>Maps that have been curated by staff and</$light_gray>\n\
  <$light_gray>the community, ensuring a fun experience.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Sort</$white_gray>
gui.map_browser.sort_quality.on.name=<$light_blue>Quality</$light_blue>
gui.map_browser.sort_quality.on.lore=\
  <$light_gray>Maps that have been curated by staff and</$light_gray>\n\
  <$light_gray>the community, ensuring a fun experience.</$light_gray>
gui.map_browser.sort_new.off.name=<$white>New</$white>
gui.map_browser.sort_new.off.lore=\
  <$light_gray>The most recently published maps. Be</$light_gray>\n\
  <$light_gray>warned that anything can be here!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Sort</$white_gray>
gui.map_browser.sort_new.on.name=<$white>New</$white>
gui.map_browser.sort_new.on.lore=\
  <$light_gray>The most recently published maps. Be</$light_gray>\n\
  <$light_gray>warned that anything can be here!</$light_gray>

gui.map_browser.difficulty_easy.off.name=<#62F041>Easy</#62F041>
gui.map_browser.difficulty_easy.off.lore=<$light_gray>Simple and beginner-friendly; a walk in the park!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Enable</$white_gray>
gui.map_browser.difficulty_easy.on.name=<#62F041>Easy</#62F041>
gui.map_browser.difficulty_easy.on.lore=<$light_gray>Simple and beginner-friendly; a walk in the park!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Disable</$white_gray>
gui.map_browser.difficulty_medium.off.name=<#FFE410>Medium</#FFE410>
gui.map_browser.difficulty_medium.off.lore=<$light_gray>Requires some skill and practice. You might break a sweat!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Enable</$white_gray>
gui.map_browser.difficulty_medium.on.name=<#FFE410>Medium</#FFE410>
gui.map_browser.difficulty_medium.on.lore=<$light_gray>Requires some skill and practice. You might break a sweat!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Disable</$white_gray>
gui.map_browser.difficulty_hard.off.name=<$orange>Hard</$orange>
gui.map_browser.difficulty_hard.off.lore=\
  <$light_gray>Advanced skills needed. Get ready<$light_gray>\n\
  <$light_gray>to put in some serious effort!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Enable</$white_gray>
gui.map_browser.difficulty_hard.on.name=<$orange>Hard</$orange>
gui.map_browser.difficulty_hard.on.lore=\
  <$light_gray>Advanced skills needed. Get ready<$light_gray>\n\
  <$light_gray>to put in some serious effort!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Disable</$white_gray>
gui.map_browser.difficulty_expert.off.name=<$strawberry>Expert</$strawberry>
gui.map_browser.difficulty_expert.off.lore=\
  <$light_gray>A true challenge! Only for the</$light_gray>\n\
  <$light_gray>most dedicated players.<$light_gray>\n\n\
  $LMB <$white_gray>Click to Enable</$white_gray>
gui.map_browser.difficulty_expert.on.name=<$strawberry>Expert</$strawberry>
gui.map_browser.difficulty_expert.on.lore=\
  <$light_gray>A true challenge! Only for the</$light_gray>\n\
  <$light_gray>most dedicated players.<$light_gray>\n\n\
  $LMB <$white_gray>Click to Disable</$white_gray>
gui.map_browser.difficulty_nightmare.off.name=<$magenta>Nightmare</$magenta>
gui.map_browser.difficulty_nightmare.off.lore=\
  <$light_gray>The hardest maps that will often require</$light_gray>\n\
  <$light_gray>specific knowledge and extreme precision.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Enable</$white_gray>
gui.map_browser.difficulty_nightmare.on.name=<$magenta>Nightmare</$magenta>
gui.map_browser.difficulty_nightmare.on.lore=\
  <$light_gray>The hardest maps that will often require</$light_gray>\n\
  <$light_gray>specific knowledge and extreme precision.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Disable</$white_gray>

gui.map_browser.search_maps.empty.name=<$cyan>Search Maps<$cyan>
gui.map_browser.search_maps.empty.lore=\
  <$light_gray>Find any map by its name.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Search</$light_gray>

gui.map_browser.search_maps.name=<$cyan>Search Maps<$cyan>
gui.map_browser.search_maps.lore=\
  <$light_gray>Find any map by its name.</$light_gray>\n\n\
  <$light_gray>Current:</$light_gray> <0>\n\n\
  $LMB <$light_gray>Click to Search</$light_gray>\n\
  $SHIFT_LMB <$light_gray>Shift + Click to Reset</$light_gray>
