###
### GUI - Notifications
###

gui.notification.toast=<$yellow>New Notification!</$yellow>
gui.notification.toast.unread=<$light_gray>You have <0> unread notification.</$light_gray>
gui.notification.toast.unread.multiple=<$light_gray>You have <0> unread notifications.</$light_gray>

gui.notifications.information.name=<$yellow>Information</$yellow>
gui.notifications.information.lore=\
    <$light_gray>A list of notifications that you have received.</$light_gray>\n\
    <$light_gray>Hover over a notification to see more details.</$light_gray>
gui.notification.unread.name=Mark as Unread
gui.notification.unread.lore=\
    <$light_gray>Mark this notification as unread.</$light_gray>\n\n\
    $LMB <$light_gray>Click to Mark as Unread</$light_gray>

gui.notification.unhandled.name=<$red>Unknown Notification</$red>
gui.notification.unhandled.lore=\
    <$light_gray>This notification was not recognized, this may be due</$light_gray>\n\
    <$light_gray>to being on an outdated server. If this presists after changing</$light_gray>\n\
    <$light_gray>servers, please contact support.</$light_gray>
gui.notification.unhandled.message=\
  <hover:show_text:'Click to Copy ID'><click:copy_to_clipboard:'<0>'>\
  <$light_gray>Notification ID: <$white><0></$white><$light_gray>\
  </click></hover>

gui.notifications.notification.lore.actions=$SHIFT_LMB <$white_gray>Click to Show Extended View</$white_gray>
gui.notifications.notification.lore.rmb=$RMB <0>
gui.notifications.notification.lore.lmb=$LMB <0>

###
### Notification Actions Menu Header
###
gui.notification.information.name=<$yellow>Information</$yellow>
gui.notification.information.lore=\
    <$light_gray>A group of actions you can take on this notification.</$light_gray>\n\
    <$light_gray>Hover over an action to see more details.</$light_gray>

gui.notification.time.name=<$azure>Delivered Time</$azure>
gui.notification.time.sent_at=<$light_gray>Sent </$light_gray><$white><0></$white>
gui.notification.time.read_at=<$light_gray>Read </$light_gray><$white><0></$white>
gui.notification.time.expires_at=<$light_gray>Expires in </$light_gray><$white><0></$white>

###
### Notification Actions
###

gui.notification.action.delete.interaction=<$white_gray>Click to Delete</$white_gray>
gui.notification.action.delete.name=<$red>Delete Notification</$red>
gui.notification.action.delete.lore=\
    <$light_gray>Delete this notification.</$light_gray>\n\
    <$light_gray>This action is permanent and cannot be undone.</$light_gray>\n\n\
    $LMB <$white_gray>Click to Delete</$white_gray>

gui.notification.action.link.interaction=<$white_gray>Click to Open Link</$white_gray>
gui.notification.action.link.name=<aqua>Open Link</aqua>
gui.notification.action.link.lore=$LMB <$white_gray>Click to Open Link</$white_gray>
gui.notification.action.link.message=$INFO<$light_gray>Visit Link:</$light_gray> <click:open_url:'<0>'><$azure><0></$azure></click>

gui.notification.action.join.interaction=<$white_gray>Click to Join</$white_gray>
gui.notification.action.join.name=<green>Join Map</green>
gui.notification.action.join.lore=\
  <$light_gray>Join the map associated with this notification.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Join Map</$white_gray>

###
### Friend Added Notification
###

gui.notification.friend_added.name=<$toxic_green>Friend Added</$toxic_green>
gui.notification.friend_added.lore=<$light_gray>You are now friends with </$light_gray><$white><0></$white><$light_gray>.</$light_gray>
gui.notification.friend_added.toast=<$light_gray>Now friends with <0>!</$light_gray>

###
### Friend Request Notification
###

gui.notification.friend_request.name=<$toxic_green>New Friend Request</$toxic_green>
gui.notification.friend_request.lore=<$light_gray>You have received a new friend request from </$light_gray><$white><0></$white><$light_gray>.</$light_gray>
gui.notification.friend_request.toast=<$light_gray>Friend request from <0>!</$light_gray>

gui.notification.friend_request.action.confirm.name=<green>Accept Friend Request</green>
gui.notification.friend_request.action.confirm.lore=$LMB <$white_gray>Click to Accept</$white_gray>
gui.notification.friend_request.action.confirm.interaction=<$white_gray>Click to Accept</$white_gray>

gui.notification.friend_request.action.reject.name=<$red>Decline Friend Request</$red>
gui.notification.friend_request.action.reject.lore=$LMB <$white_gray>Click to Decline</$white_gray>
gui.notification.friend_request.action.reject.interaction=<$white_gray>Click to Decline</$white_gray>

###
### Update Notification
###

gui.notification.update.name=<$gold>New Update</$gold>
gui.notification.update.lore=<$light_gray>A new update is available: </$light_gray><$white><0></$white>

###
### Recap Notification
###

gui.notification.recap.name=<$gold>Hollow Cube Recap</$gold>
gui.notification.recap.lore=<$light_gray>Your Hollow Cube 2025 recap is ready to view!</$light_gray>

###
### Map Time Delete Notification
###

gui.notification.map_time_deleted.name=<$red>Map Time Deleted</$red>
gui.notification.map_time_deleted.lore=<$light_gray>Your map time for </$light_gray><$white><0></$white><$light_gray> has been removed.</$light_gray>

###
### Map Builder Notifications
###
gui.notification.map_builder.invite.name=<$orange>New Builder Invite</$orange>
gui.notification.map_builder.invite.lore=\n\
  <$white><0></$white> <$light_gray>has invited you to help them build on their map <$white><1></$white>!<$light_gray>

# 0: Player Display Name
# 1: Inviter's Map Name
gui.notification.map_builder.invite.accept.message=\
  $CONFIRM<$light_gray>You accepted <$white><0>'s</$white> invite to build on their map <$white><1></$white>! You can <$white>join</$white> it from the <$white>Create Maps</$white> menu in the lobby.</$light_gray>
gui.notification.map_builder.invite.accept.no_slots.message=\
  $DENY<$light_gray>You <$white>don't</$white> have a free <$white>map slot</$white> to accept <$white><0></$white>'s builder invite! <$white>Publish or leave</$white> a map to free up a slot or </$light_gray><click:run_command:'/store'><hover:show_text:'<$lime>Click to open the store!</$lime>'><$lime>click here to visit our /store!</$lime></click>

gui.notification.map_builder.invite.toast=<$light_gray>New build invite from <0>!</$light_gray>

gui.notification.map_builder.invite.action.accept=<$white_gray>Click to Accept</$white_gray>
gui.notification.map_builder.invite.action.reject=<$white_gray>Click to Reject</$white_gray>

gui.notification.map_builder.invite.action.accept.tooltip.name=<$lime>Accept Build Request</$lime>
gui.notification.map_builder.invite.action.accept.tooltip.lore=$LMB <$white_gray>Click to Accept</$white_gray>

gui.notification.map_builder.invite.action.reject.tooltip.name=<$red>Reject Build Request</$red>
gui.notification.map_builder.invite.action.reject.tooltip.lore=$LMB <$white_gray>Click to Reject</$white_gray>

gui.notification.map_builder.invite.accepted.message=<$light_gray><$white><0></$white> accepted your build invite on <$white><1></$white>!</$light_gray>
gui.notification.map_builder.invite.rejected.message=<$light_gray><$white><0></$white> rejected your build invite on <$white><1></$white>!</$light_gray>

gui.notification.map_builder.invite.accepted.toast=<$light_gray><0> accepted your build invite!</$light_gray>
gui.notification.map_builder.invite.rejected.toast=<$light_gray><0> rejected your build invite!</$light_gray>
gui.notification.map_builder.invite.accept.gone=$DENY<$light_gray>The invite is <$white_gray>no longer available</$white_gray>!</$light_gray>
