#
# STORE VIEW
#

gui.store.information.name=<$yellow>Information</$yellow>
gui.store.information.lore=\
  <$light_gray>Support our development by purchasing premium</$light_gray>\n\
  <$light_gray>packages, or get them for free by grinding.</$light_gray>
gui.store.cubits_to_coins.name=<$white>Convert Cubits to Coins</$white>
gui.store.cubits_to_coins.lore=\
  <$light_gray>Conversion Ratio: <$light_pink>1 Cubit</$light_pink> = <$gold>100 Coins</$gold></$light_gray>\n\n\
  <$light_gray>Missing coins to buy something? No problem!</$light_gray>\n\
  <$light_gray>Convert your higher currency to a lower one.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.store.tab_cubits.off.name=<$light_pink>Buy Cubits</$light_pink>
gui.store.tab_cubits.off.lore=\
  <$light_gray>The premium currency used across our</$light_gray>\n\
  <$light_gray>server to get cosmetics and features.</$light_gray>\n\n\
  $LMB <$light_gray>Click to View</$light_gray>
gui.store.tab_cubits.on.name=<$light_pink>Buy Cubits</$light_pink>
gui.store.tab_cubits.on.lore=\
  <$light_gray>The premium currency used across our</$light_gray>\n\
  <$light_gray>server to get cosmetics and features.</$light_gray>

gui.store.tab_hypercube.off.name=<$azure>Buy Hypercube</$azure>
gui.store.tab_hypercube.off.lore=\
  <$light_gray>Our monthly subscription rank that</$light_gray>\n\
  <$light_gray>gives you access to exclusive features.</$light_gray>\n\n\
  $LMB <$light_gray>Click to View</$light_gray>
gui.store.tab_hypercube.on.name=<$azure>Buy Hypercube</$azure>
gui.store.tab_hypercube.on.lore=\
  <$light_gray>Our monthly subscription rank that</$light_gray>\n\
  <$light_gray>gives you access to exclusive features.</$light_gray>

gui.store.tab_addons.off.name=<$orange>Buy Add-Ons</$orange>
gui.store.tab_addons.off.lore=\
  <$light_gray>Locked features that you can buy with</$light_gray>\n\
  <$light_gray>cubits, such as bigger maps to build in.</$light_gray>\n\n\
  $LMB <$light_gray>Click to View</$light_gray>
gui.store.tab_addons.on.name=<$orange>Buy Add-Ons</$orange>
gui.store.tab_addons.on.lore=\
  <$light_gray>Locked features that you can buy with</$light_gray>\n\
  <$light_gray>cubits, such as bigger maps to build in.</$light_gray>

gui.store.buy_cubits.name=<$white>Buy Cubits</$white>
gui.store.buy_hypercube.name=<$white>Buy Hypercube</$white>
gui.store.buy_addons.name=<$white>Buy Add-Ons</$white>

#
# CUBITS TAB
#

gui.store.cubits.1.name=<$light_pink>A Package of Cubits</$light_pink>
gui.store.cubits.1.lore=\
  <$light_gray>50 Cubits for 4.99 USD</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>
gui.store.cubits.2.name=<$light_pink>A Box of Cubits</$light_pink> <$dark_gray>[<$light_gray>5% Bonus</$light_gray>]</$dark_gray>
gui.store.cubits.2.lore=\
  <$light_gray>105 Cubits for 9.99 USD</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>
gui.store.cubits.3.name=<$light_pink>Crates of Cubits</$light_pink> <$dark_gray>[<$light_gray>10% Bonus</$light_gray>]</$dark_gray>
gui.store.cubits.3.lore=\
  <$light_gray>220 Cubits for 19.99 USD</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>
gui.store.cubits.4.name=<$light_pink>A Chest of Cubits</$light_pink> <$dark_gray>[<$light_gray>14% Bonus</$light_gray>]</$dark_gray>
gui.store.cubits.4.lore=\
  <$light_gray>400 Cubits for 34.99 USD</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>
gui.store.cubits.5.name=<$light_pink>A Shipment of Cubits</$light_pink> <$dark_gray>[<$light_gray>20% Bonus</$light_gray>]</$dark_gray>
gui.store.cubits.5.lore=\
  <$light_gray>600 Cubits for 49.99 USD</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>

#
# HYPERCUBE TAB
#

gui.store.hypercube.perks.name=$HYPERCUBE <$gold>Hypercube Perks</$gold>
gui.store.hypercube.perks.lore=\
  <$light_gray> <$dark_gray>»</$dark_gray> Gold Badge and Name</$light_gray>\n\
  <$light_gray> <$dark_gray>»</$dark_gray> White Chat Color</$light_gray>\n\
  <$light_gray> <$dark_gray>»</$dark_gray> All Premium Features (Add-Ons)</$light_gray>\n\
  <$light_gray> <$dark_gray>»</$dark_gray> Extra Emojis</$light_gray>\n\
  <$light_gray> <$dark_gray>»</$dark_gray> Discord Tag</$light_gray>\n\
  <$light_gray> <$dark_gray>»</$dark_gray> Beta Testing</$light_gray>\n\
  <$light_gray> <$dark_gray>»</$dark_gray> ... and more to come!</$light_gray>

gui.store.hypercube.perks.unlimited_map_slots.name=<$light_blue>All Map Slots</$light_blue>
gui.store.hypercube.perks.unlimited_map_slots.lore=\
  <$light_gray>Three additional maps to build at once.</$light_gray>

gui.store.hypercube.perks.all_map_sizes.name=<$light_blue>Increased Map Sizes</$light_blue>
gui.store.hypercube.perks.all_map_sizes.lore=\
  <$light_gray>Increases the building space in your maps.</$light_gray>

gui.store.hypercube.perks.beta_testing.name=<$light_blue>Beta Testing</$light_blue>
gui.store.hypercube.perks.beta_testing.lore=\
  <$light_gray>Access to certain features before</$light_gray>\n\
  <$light_gray>they are released to the public.</$light_gray>

gui.store.hypercube.perks.badge.name=<$light_blue>Gold Name and Badge</$light_blue>
gui.store.hypercube.perks.badge.lore=\
  <$light_gray>Adds a</$light_gray> $HYPERCUBE <$light_gray>badge and color to your</$light_gray>\n\
  <$light_gray>name in-game and on our <$white>/discord</$white>.</$light_gray>

gui.store.hypercube.perks.more_emojis.name=<$light_blue>More Emojis</$light_blue>
gui.store.hypercube.perks.more_emojis.lore=\
  <$light_gray>See all Hypercube-only emotes with <$white>/emojis</$white>.</$light_gray>

gui.store.hypercube.1month.name=<$gold>A Month of</$gold> $HYPERCUBE <$gold>Hypercube</$gold>
gui.store.hypercube.1month.lore=\
  <$light_gray>30 Days for 5 USD</$light_gray>\n\n\
  $NOTE <$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>Will renew automatically.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>
gui.store.hypercube.1year.name=<$gold>A Year of</$gold> $HYPERCUBE <$gold>Hypercube</$gold> <$dark_gray>[<$light_gray>2 Months Free!</$light_gray>]</$dark_gray>
gui.store.hypercube.1year.lore=\
  <$light_gray>365 Days for 50 USD</$light_gray>\n\n\
  $NOTE <$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>Will renew automatically.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>

#
# ADD-ONS //TODO add prices
#

gui.store.addons.cost_50_cubits.name=<$white>Costs 50 Cubits</$white>
gui.store.addons.cost_100_cubits.name=<$white>Costs 100 Cubits</$white>
gui.store.addons.cost_150_cubits.name=<$white>Costs 150 Cubits</$white>
gui.store.addons.cost_maxed.name=<$white>Maxed Out</$white>

gui.store.addons.map_size_large.name=<$white>Large Map Size</$white>
gui.store.addons.map_size_large.lore=\
  <$light_gray>300 x 300 border in all your maps.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>
gui.store.addons.map_size_massive.name=<$white>Large Map Size</$white>
gui.store.addons.map_size_massive.lore=\
  <$light_gray>600 x 600 border in all your maps.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>
gui.store.addons.map_size_colossal.name=<$white>Large Map Size</$white>
gui.store.addons.map_size_colossal.lore=\
  <$light_gray>1,200 x 1,200 x 500 border in all your maps.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
gui.store.addons.map_size_colossal.unlocked.name=<$white>Upgraded Map Size</$white>
gui.store.addons.map_size_colossal.unlocked.lore=<$light_gray>You already have these unlocked!</$light_gray>
gui.store.addons.map_slot.name=<$white>Map Slot <0></$white>
gui.store.addons.map_slot.lore=\
  <$light_gray>Allows you to build <0> maps at once.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>
gui.store.addons.map_builder.name=<$white>Trusted Builder <0></$white>
gui.store.addons.map_builder.lore=\
  <$light_gray>Add up to <0> players per map who can</$light_gray>\n\
  <$light_gray>load it and build when you are offline.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Purchase</$light_gray>
gui.store.addons.map_builder.unlocked.name=<$white>Trusted Builder</$white>
gui.store.addons.map_builder.unlocked.lore=<$light_gray>You already have these unlocked!</$light_gray>
store.add-ons.map_slot.buy=$CONFIRM<$light_gray>You unlocked an extra <$white>map slot</$white>!</$light_gray>
store.add-ons.trusted_builder_slot.buy=$CONFIRM<$light_gray>You unlocked an extra <$white>trusted builder slot</$white> on all of your maps!</$light_gray>
store.add-ons.map_size.buy=$CONFIRM<$light_gray>You unlocked the <$white><0> map size</$white> on all of your maps!</$light_gray>
