###
### GUI - Notifications
###

gui.notification.toast=<$yellow>New Notification!</$yellow>
gui.notifications.information.name=<$yellow>Information</$yellow>
gui.notifications.information.lore=\
    <$light_gray>A list of notifications that you have received.</$light_gray>\n\
    <$light_gray>Hover over a notification to see more details.</$light_gray>
gui.notification.unread.name=Mark as Unread
gui.notification.unread.lore=\
    <$light_gray>Mark this notification as unread.</$light_gray>\n\n\
    $LMB <$light_gray>Click to Mark as Unread</$light_gray>

gui.notifications.notification.lore.actions=$SHIFT_LMB <$white_gray>Click to Show Extended View</$white_gray>
gui.notifications.notification.lore.rmb=$RMB <0>
gui.notifications.notification.lore.lmb=$LMB <0>

###
### Notification Actions Menu Header
###
gui.notification.information.name=<$yellow>Information</$yellow>
gui.notification.information.lore=\
    <$light_gray>A group of actions you can take on this notification.</$light_gray>\n\
    <$light_gray>Hover over an action to see more details.</$light_gray>

gui.notification.time.name=<$azure>Delivered Time</$azure>
gui.notification.time.sent_at=<$light_gray>Sent </$light_gray><$white><0></$white>
gui.notification.time.read_at=<$light_gray>Read </$light_gray><$white><0></$white>
gui.notification.time.expires_at=<$light_gray>Expires in </$light_gray><$white><0></$white>

###
### Notification Actions
###

gui.notification.action.delete.interaction=Click to Delete
gui.notification.action.delete.name=<$red>Delete Notification</$red>
gui.notification.action.delete.lore=\
    <$light_gray>Delete this notification.</$light_gray>\n\
    <$light_gray>This action is permanent and cannot be undone.</$light_gray>

###
### Friend Request Notification
###

gui.notification.friend_request.name=<$toxic_green>New Friend Request</$toxic_green>
gui.notification.friend_request.lore=<$light_gray>You have received a new friend request from </$light_gray><$white><0></$white><$light_gray>.</$light_gray>
gui.notification.friend_request.toast=<$light_gray>Friend request from <0>!</$light_gray>

gui.notification.friend_request.action.confirm.name=<green>Accept Friend Request</green>
gui.notification.friend_request.action.confirm.lore=$LMB <$white_gray>Click to Accept</$white_gray>
gui.notification.friend_request.action.confirm.interaction=<$white_gray>Click to Accept</$white_gray>

gui.notification.friend_request.action.reject.name=<$red>Decline Friend Request</$red>
gui.notification.friend_request.action.reject.lore=$LMB <$white_gray>Click to Decline</$white_gray>
gui.notification.friend_request.action.reject.interaction=<$white_gray>Click to Decline</$white_gray>