gui.builder_menu.information.name=<$yellow>Information</$yellow>
gui.builder_menu.information.lore=\
  <$light_gray>Utilities that give shortcuts to the</$light_gray>\n\
  <$light_gray>building process as well as gameplay.</$light_gray>

gui.builder_menu.tab.name=<0>

gui.builder_menu.invite_players.name=<$white>Invite Players</$white>
gui.builder_menu.invite_players.lore=\
  <$light_gray>Two minds are better than one! Bring</$light_gray>\n\
  <$light_gray>some friends to help build your map.</$light_gray>\n\n\
  $NOTE<$yellow>NOTE </$yellow>$NOTE\n\
  <$light_gray>The GUI is a WIP. Use <$white_gray>/invite</$white_gray> for now.</$light_gray>\n\n\
  <$red>Coming Later!<$red>

gui.builder_menu.save_and_exit.name=<$white>Save and Exit</$white>
gui.builder_menu.save_and_exit.lore=\
  <$light_gray>Save your build progress and return to the</$light_gray>\n\
  <$light_gray>lobby. You can also use <$white_gray>/leave</$white_gray> to do this.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Teleport</$white_gray>

#
# Custom Blocks Tab
#

gui.builder_menu.tab_custom_blocks.name=<$white>Custom Blocks</$white>

gui.builder_menu.custom_blocks.finish_plate.name=<$gold>Finish Plate</$gold>
gui.builder_menu.custom_blocks.finish_plate.lore=\
  <$light_gray>Applies to: </$light_gray><$light_blue>Parkour Maps</$light_blue>\n\n\
  <$light_gray>When a player steps on this,</$light_gray>\n\
  <$light_gray>they will complete your map.</$light_gray>\n\n\
  $NOTE<$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>Though this has a custom icon, it</$light_gray>\n\
  <$light_gray>does not have its own model yet.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get</$white_gray>

gui.builder_menu.custom_blocks.checkpoint_plate.name=<$white>Checkpoint Plate</$white>
gui.builder_menu.custom_blocks.checkpoint_plate.lore=\
  <$light_gray>Applies to: </$light_gray><$light_blue>Parkour Maps</$light_blue>\n\n\
  <$light_gray>A checkpoint that players can return to.</$light_gray>\n\
  <$light_gray>Right click once placed to edit its properties.</$light_gray>\n\n\
  $NOTE<$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>Though this has a custom icon, it</$light_gray>\n\
  <$light_gray>does not have its own model yet.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get</$white_gray>

gui.builder_menu.custom_blocks.status_plate.name=<$orange>Status Plate</$orange>
gui.builder_menu.custom_blocks.status_plate.lore=\
  <$light_gray>Applies to: </$light_gray><$light_blue>Parkour Maps</$light_blue>\n\n\
  <$light_gray>Modify player attributes and enhance map gameplay.</$light_gray>\n\
  <$light_gray>Right click once placed to edit its properties.</$light_gray>\n\n\
  $NOTE<$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>Though this has a custom icon, it</$light_gray>\n\
  <$light_gray>does not have its own model yet.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get</$white_gray>

#
# Build Tools
#

gui.builder_menu.tab_build_tools.name=<$white>Build Tools</$white>

gui.builder_menu.build_tools.debug_stick.name=<$pink>Debug Stick</$pink>
gui.builder_menu.build_tools.debug_stick.lore=\
  <$light_gray>Lets you cycle between and edit block states.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get</$white_gray>

gui.builder_menu.build_tools.wand.name=<$white>Terraform Wand</$white>
gui.builder_menu.build_tools.wand.lore=\
  <$light_gray>Our recreation of World Edit's wand tool.</$light_gray>\n\
  <$light_gray>Set two points and edit blocks between them.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get</$white_gray>

#
# Custom Items
#

gui.builder_menu.tab_custom_items.name=<$white>Custom Items</$white>

gui.builder_menu.custom_items.edit_map_details.name=<$white>Edit Map Details Item</$white>
gui.builder_menu.custom_items.edit_map_details.lore=\
  <$light_gray>Change the name, tags, and other things about your map.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.builder_menu.custom_items.enter_testing_mode.name=<$white>Enter Testing Mode Item</$white>
gui.builder_menu.custom_items.enter_testing_mode.lore=\
  <$light_gray>Applies to: </$light_gray><$light_blue>Parkour Maps</$light_blue>\n\n\
  <$light_gray>Allows you to test your map as if you were playing.</$light_gray>\n\
  <$light_gray>Lets you activate checkpoints, status plates, etc.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get</$white_gray>

item.mapmaker.enter_test_mode.name=<$white>Enter Testing Mode</$white> $RMB_ITEM
item.mapmaker.enter_test_mode.lore=\
  <$light_gray>Allows you to test your map as if you were playing.</$light_gray>\n\
  <$light_gray>Lets you activate checkpoints, status plates, etc.</$light_gray>

gui.builder_menu.custom_items.spawn_point.name=<$white>Spawn Location Item</$white>
gui.builder_menu.custom_items.spawn_point.lore=\
  <$light_gray>Lets you warp to and set the</$light_gray>\n\
  <$light_gray>spawn location of your map.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get</$white_gray>

item.mapmaker.spawn_point.name=<$white>Spawn Location</$white> $RMB_ITEM<$dark_gray>/</$dark_gray> $SHIFT_RMB_ITEM
item.mapmaker.spawn_point.lore=\
  <$light_gray>Lets you warp to and set the</$light_gray>\n\
  <$light_gray>spawn location of your map.</$light_gray>