#
# BIOME LIST VIEW
#
gui.biome_list.information.name=<$yellow>Information</$yellow>
gui.biome_list.information.lore=\
  <$light_gray>Customize certain regions of your map with</$light_gray>\n\
  <$light_gray>unique colors, weather, particles, and sounds.<$light_gray>
gui.biome_list.title.name=<$white>Custom Biomes</$white>
gui.biome_list.capacity.name=<$white><0> Biome Slots Used</$white>
# //TODO use setArgs correctly for the above param <0>

# BIOME ENTRY
gui.biome_list.entry.add.name=<$lime>Add Biome</$lime>
gui.biome_list.entry.add.lore=\
  <$light_gray>Makes a new, custom biome for you to edit.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Create</$light_gray>
gui.biome_list.entry.add.disabled.name=<$red>Add Biome</$red>
gui.biome_list.entry.add.disabled.lore=<$light_gray>You cannot create any new biomes!</$light_gray>
gui.biome_list.entry.name=<$lime>Loaded Biome Slot</$lime> <$dark_gray>[<$light_gray><0></$light_gray>]</$dark_gray>
gui.biome_list.entry.unloaded.name=<$yellow>Unloaded Biome Slot</$yellow> <$dark_gray>[<$light_gray><0></$light_gray>]</$dark_gray>
# //TODO use setArgs correctly for the above params <0>
# //TODO add further detail under biome slots, such as their names, how big they are, etc.

#
# BIOME EDITOR VIEW
#
gui.biome_editor.information.name=<$yellow>Information</$yellow>
gui.biome_editor.information.lore=\
  <$light_gray>Design your own biome using many advanced options.</$light_gray>
gui.biome_editor.title.name=<$white>Biome Editor</$white>
gui.biome_editor.copy.name=<$lime>Copy Biome</$lime>
gui.biome_editor.copy.lore=\
  <$light_gray>Duplicate this biome with all of its settings.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Copy</$light_gray>
gui.biome_editor.delete.name=<$red>Delete Biome</$red>
gui.biome_editor.delete.lore=\
  <$light_gray>Delete this biome and all of its settings.</$light_gray>\n\n\
  $WARNING<$yellow>WARNING</$yellow> $WARNING\n\
  <$light_gray>After confirmation, this cannot be undone!</$light_gray>\n\n\
  $LMB <$light_gray>Click to Delete</$light_gray>
gui.biome_editor.change_name.name=<$white>Change Name</$white>
gui.biome_editor.change_name.lore=\
  <$light_gray>Write a helpful name for your biome</$light_gray>\n\
  <$light_gray>to help you remember what it is for.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Edit</$light_gray>
gui.biome_editor.sky_color.name=<$white>Sky Color</$white>
gui.biome_editor.sky_color.lore=\
  <$light_gray>Current:</$light_gray> <0> <$dark_gray>[<$light_gray><1></$light_gray>]</$dark_gray>\n\n\
  <$light_gray>Decides what color the sky is.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Edit</$light_gray>
gui.biome_editor.fog_color.name=<$white>Fog Color</$white>
gui.biome_editor.fog_color.lore=\
  <$light_gray>Current:</$light_gray> <0> <$dark_gray>[<$light_gray><1></$light_gray>]</$dark_gray>\n\n\
  <$light_gray>Decides what color the fog is that</$light_gray>\n\
  <$light_gray>shows up at the edge of your render.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Edit</$light_gray>
gui.biome_editor.water_color.name=<$white>Water Color</$white>
gui.biome_editor.water_color.lore=\
  <$light_gray>Current:</$light_gray> <0> <$dark_gray>[<$light_gray><1></$light_gray>]</$dark_gray>\n\n\
  <$light_gray>Decides what color the water is.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Edit</$light_gray>
gui.biome_editor.water_fog_color.name=<$white>Water Fog Color</$white>
gui.biome_editor.water_fog_color.lore=\
  <$light_gray>Current:</$light_gray> <0> <$dark_gray>[<$light_gray><1></$light_gray>]</$dark_gray>\n\n\
  <$light_gray>Decides what color the water fog is that</$light_gray>\n\
  <$light_gray>shows up from a distance during swimming.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Edit</$light_gray>
gui.biome_editor.grass_color.name=<$white>Grass Color</$white>
gui.biome_editor.grass_color.lore=\
  <$light_gray>Current:</$light_gray> <0> <$dark_gray>[<$light_gray><1></$light_gray>]</$dark_gray>\n\n\
  <$light_gray>Decides what color grasses, ferns, and sugar cane are.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Edit</$light_gray>
gui.biome_editor.foliage_color.name=<$white>Foliage Color</$white>
gui.biome_editor.foliage_color.lore=\
  <$light_gray>Current:</$light_gray> <0> <$dark_gray>[<$light_gray><1></$light_gray>]</$dark_gray>\n\n\
  <$light_gray>Decides what color vines and most leaves are.</$light_gray>\n\n\
  $LMB <$light_gray>Click to Edit</$light_gray>
# //TODO use setArgs correctly for the above params <0> (the hex color) and <1> (approximated real name of the hex color)