gui.map_collection.information.name=<$yellow>Information</$yellow>
gui.map_collection.information.lore=\
  <$light_gray>View a list of maps curated by a community member.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get Collection ID</$white_gray>

gui.map_collection.name.name=<$light_gray>by <0></$light_gray>
gui.edit_map_collection.name.name=<$light_gray>by <0></$light_gray>
gui.edit_map_collection.name.lore=\n$LMB <$white_gray>Click to Edit Collection Name</$white_gray>

gui.edit_map_collection.icon.name=<$white>Change Display Item</$white>
gui.edit_map_collection.icon.lore=\
  <$light_gray>Current: </$light_gray><$light_blue><0></$light_blue>\n\n\
  <$light_gray>Choose a vanilla Minecraft item</$light_gray>\n\
  <$light_gray>that best represents your collection.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>

gui.edit_map_collection.delete.name=<$white>Delete Collection</$white>
gui.edit_map_collection.delete.lore=\
    <$light_gray>Permanently delete this collection.</$light_gray>\n\n\
    $SHIFT_LMB <$white_gray>Shift + Click to Delete</$white_gray>

gui.edit_map_collection.map_display.footer=\
  $LMB <$light_gray>Click to Move</$light_gray>\n\
  $SHIFT_LMB <$light_gray>Shift + Click to Remove</$light_gray>

gui.edit_map_collection_list.entry.name=<$white><0></$white>
gui.edit_map_collection_list.entry.lore=\
  <$light_gray>by</$light_gray> <1>\n\n\
  <$light_gray>Map Count:</$light_gray> <$white><2></$white>\n\n\
  $LMB <$light_gray>Click to View</$light_gray>\n\
  $SHIFT_LMB <$light_gray>Shift + Click to Edit</$light_gray>

gui.add_map_collection_list.entry.name=<$white><0></$white>
gui.add_map_collection_list.entry.lore=\
  <$light_gray>by</$light_gray> <1>\n\n\
  <$light_gray>Map Count:</$light_gray> <$white><2></$white>\n\n\
  $LMB <$light_gray>Click to Add</$light_gray>

gui.add_map_collection_list.add.name=<$lime>Add Collection</$lime>
gui.add_map_collection_list.add.lore=\
  <$light_gray>Create a new collection to organize your maps.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Add</$white_gray>

chat.map_collection.info.id=<$white><1></$white> <$light_gray>by</$light_gray> <2>\n\
  <$light_gray>ID: </$light_gray>\
  <$white><click:copy_to_clipboard:'<0>'><hover:show_text:'Click to Copy'><0></hover></click></$white>