# Map Details GUI
gui.map_details.map_info.boost_map.name=<$gold>Boost Map</$gold>
# 0: The amount of concurrent Boosts
gui.map_details.map_info.boost_map.lore=\
  <$light_gray>Current Boosts:</$light_gray> <$red>None</$red>\n\n\
  <$light_gray>If you really like a map, you can give</$light_gray>\n\
  <$light_gray>it a boost to help it get more popular.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
# FOURTH LINE ABOVE FOR LATER: <$light_gray>Purchase them on <$azure>store.hollowcube.net!</$azure></$light_gray>\n\n\
gui.map_details.play_map.name=<$lime>Play Map</$lime>
gui.map_details.play_map.lore=\
  <$light_gray>Start a new adventure on this map!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Teleport</$white_gray>
gui.map_details.continue_map.lore=<$light_gray>Continue your progress in this map!</$light_gray>
gui.map_details.continue_map.current_savestate.lore=<$light_gray>Current Savestate</$light_gray>
gui.map_details.continue_map.current_savestate.time.lore=<$dark_gray>»</$dark_gray> <$light_gray>Time:</$light_gray> <$light_blue><0></$light_blue>
gui.map_details.continue_map.current_savestate.jumps.lore=<$dark_gray>»</$dark_gray> <$light_gray>Jumps:</$light_gray> <$light_blue><0></$light_blue>
gui.map_details.continue_map.current_savestate.fails.lore=<$dark_gray>»</$dark_gray> <$light_gray>Fails:</$light_gray> <$light_blue><0></$light_blue>
gui.map_details.suggest_similar_maps.name=<$light_blue>Suggest Similar Maps</$light_blue>
gui.map_details.suggest_similar_maps.lore=\
  <$light_gray>Look for maps similar in difficulty,</$light_gray>\n\
  <$light_gray>tags, type, and so on, to this one.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
# 0: Map publisher's name
gui.map_details.creator_profile.name=<$light_gray>by</$light_gray> <0>
#gui.map_details.creator_profile.lore=$LMB <$white_gray>Click to View Profile</$white_gray>
# Map Details GUI - Map Info Tab
gui.map_details.map_info_tab.published_id=<$white><2></$white> <$light_gray>by</$light_gray> <3>\n\
  <$light_gray><hover:show_text:'Click to Copy Full ID'><click:copy_to_clipboard:'<0>'>ID</click></hover>: \
  <$white><hover:show_text:'Click to Copy'><click:copy_to_clipboard:'<1>'><1></click></hover></$white></$light_gray>
gui.map_details.map_info_tab.information.name=<$yellow>Information</$yellow>
gui.map_details.map_info_tab.information.lore=\
  <$light_gray>View a list of the map's key qualities, such as</$light_gray>\n\
  <$light_gray>tags and settings, providing you with essential</$light_gray>\n\
  <$light_gray>information to better engage with the map.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get Map ID</$white_gray>
gui.map_details.map_info_tab.name=<$white>Map Info</$white>
gui.map_details.map_info_tab.add_to_playlist.name=<$lime>Add to Playlist</$lime>
gui.map_details.map_info_tab.add_to_playlist.lore=\
  <$light_gray>Put this map into one of your playlists.</$light_gray>\n\
  <$light_gray>Easily revisit it and manage your collection.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
gui.map_details.map_info_tab.report_map.name=<$yellow>Report Map</$yellow>
gui.map_details.map_info_tab.report_map.lore=\
  <$light_gray>Does this map break our <$red>/rules</$red>?</$light_gray>\n\n\
  <$red>Coming Later!</$red>
# Map Details GUI - Map Info Tab - Map Quality
gui.map_details.map_info_tab.quality.name=<$white>Map Quality</$white>
gui.map_details.map_info_tab.quality_description.name=<$white>Map Quality</$white>
gui.map_details.map_info_tab.quality_description.lore=\
  <$light_gray>The average rating of the map. The top</$light_gray>\n\
  <$light_gray>two qualities will be approved by staff.</$light_gray>
gui.map_details.map_info_tab.quality.masterpiece.name=<$pink>M</$pink><#F17CFE>a</#F17CFE><#F58BFE>s</#F58BFE><#F899FD>t<#FCA8FD>e</#FCA8FD><#FFB6FC>r</#FFB6FC><#FCA8FD>p</#FCA8FD><#F899FD>i</#F899FD><#F58BFE>e</#F58BFE><#F17CFE>c</#F17CFE><$pink>e Quality</$pink> <$dark_gray>[</$dark_gray><$light_gray>6<$dark_gray>/</$dark_gray>6</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.quality.masterpiece.lore=\
  <$light_gray>The pinnacle of map creation, showcasing unparalleled</$light_gray>\n\
  <$light_gray>quality, creativity, and innovation. Prepare for an</$light_gray>\n\
  <$light_gray>extraordinary and unforgettable experience.</$light_gray>\n\n\
  $NOTE<$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>This rating has been set by staff!</$light_gray>
gui.map_details.map_info_tab.quality.outstanding.name=<$sky_blue>O</$sky_blue><#88FFE4>u</#88FFE4><#98FFE9>t</#98FFE9><#A8FFEE>s</#A8FFEE><#B8FFF3>t</#B8FFF3><#C8FFF8>a</#C8FFF8><#B8FFF3>n</#B8FFF3><#A8FFEE>d</#A8FFEE><#98FFE9>i</#98FFE9><#88FFE4>n</#88FFE4><$sky_blue>g Quality</$sky_blue> <$dark_gray>[</$dark_gray><$light_gray>5<$dark_gray>/</$dark_gray>6</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.quality.outstanding.lore=\
  <$light_gray>Pushes boundaries, delivering top-notch quality in every aspect.</$light_gray>\n\n\
  $NOTE<$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>This rating has been set by staff!</$light_gray>
gui.map_details.map_info_tab.quality.excellent.name=<$sea_blue>E</$sea_blue><#8EB7FF>x</#8EB7FF><#9CBFFF>c</#9CBFFF><#A9C7FF>e</#A9C7FF><#B6CFFF>l</#B6CFFF><#A9C7FF>l</#A9C7FF><#9CBFFF>e</#9CBFFF><#8EB7FF>n</#8EB7FF><$sea_blue>t Quality</$sea_blue> <$dark_gray>[</$dark_gray><$light_gray>4<$dark_gray>/</$dark_gray>6</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.quality.excellent.lore=<$light_gray>Showcases excellence in design, quality, and creativity.</$light_gray>
gui.map_details.map_info_tab.quality.great.name=<$toxic_green>Great Quality</$toxic_green> <$dark_gray>[</$dark_gray><$light_gray>3<$dark_gray>/</$dark_gray>6</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.quality.great.lore=<$light_gray>Stands out with above-average qualities.</$light_gray>
gui.map_details.map_info_tab.quality.good.name=<$lemon>Good Quality</$lemon> <$dark_gray>[</$dark_gray><$light_gray>2<$dark_gray>/</$dark_gray>6</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.quality.good.lore=<$light_gray>Offers a decent experience.</$light_gray>
gui.map_details.map_info_tab.quality.unrated.name=<$light_red>Unrated Quality</$light_red> <$dark_gray>[</$dark_gray><$light_gray>1<$dark_gray>/</$dark_gray>6</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.quality.unrated.lore=\
  <$light_gray>There aren't enough ratings to accurately</$light_gray>\n\
  <$light_gray>determine the overall quality of this map,</$light_gray>\n\
  <$light_gray>or it does not meet higher standards.</$light_gray>
# Map Details GUI - Map Info Tab - Map Difficulty
gui.map_details.map_info_tab.difficulty_description.name=<$white>Map Difficulty</$white>
gui.map_details.map_info_tab.difficulty_description.lore=\
  <$light_gray>The average clear rate of the map.</$light_gray>
gui.map_details.map_info_tab.difficulty.unknown.name=<$white>Unknown Difficulty</$white>
gui.map_details.map_info_tab.difficulty.unknown.lore=\
  <$light_gray>This map needs more unique</$light_gray>\n\
  <$light_gray>plays to determine its difficulty!</$light_gray>
gui.map_details.map_info_tab.difficulty.easy.name=\
  <#62F041>Easy Difficulty </#62F041><$dark_gray>[</$dark_gray><$light_gray>1<$dark_gray>/</$dark_gray><$light_gray>5</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.difficulty.easy.lore=\
  <$light_gray>Simple and beginner-friendly; a walk in the park!</$light_gray>
gui.map_details.map_info_tab.difficulty.medium.name=\
  <#FFE410>Medium Difficulty </#FFE410><$dark_gray>[</$dark_gray><$light_gray>2<$dark_gray>/</$dark_gray><$light_gray>5</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.difficulty.medium.lore=\
  <$light_gray>Requires some skill and practice.</$light_gray>\n\
  <$light_gray>You might break a sweat!</$light_gray>
gui.map_details.map_info_tab.difficulty.hard.name=\
  <$orange>Hard Difficulty </$orange><$dark_gray>[</$dark_gray><$light_gray>3<$dark_gray>/</$dark_gray><$light_gray>5</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.difficulty.hard.lore=\
  <$light_gray>You'll need advanced skills and strategic thinking.<$light_gray>\n\
  <$light_gray>Get ready to put in some serious effort!</$light_gray>
gui.map_details.map_info_tab.difficulty.expert.name=\
  <$strawberry>Expert Difficulty </$strawberry><$dark_gray>[</$dark_gray><$light_gray>4<$dark_gray>/</$dark_gray><$light_gray>5</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.difficulty.expert.lore=\
  <$light_gray>Looking for a challenge? Test your limits! Only</$light_gray>\n\
  <$light_gray>for the most experienced and dedicated players.<$light_gray>
gui.map_details.map_info_tab.difficulty.nightmare.name=\
  <$magenta>Nightmare Difficulty </$magenta><$dark_gray>[</$dark_gray><$light_gray>5<$dark_gray>/</$dark_gray><$light_gray>5</$light_gray><$dark_gray>]</$dark_gray>
gui.map_details.map_info_tab.difficulty.nightmare.lore=\
  <$light_gray>Insanely difficult and not for the faint of heart.</$light_gray>\n\
  <$light_gray>Survive if you can! Be warned, this map will require</$light_gray>\n\
  <$light_gray>specific knowledge and extreme precision.</$light_gray>
# Map Details GUI - Map Info Tab - Map Type
gui.map_details.map_info_tab.type_description.name=<$white>Map Type</$white>
gui.map_details.map_info_tab.type_description.lore=\
  <$light_gray>The type of map its creator chose when making it.</$light_gray>
gui.map_details.map_info_tab.type.parkour.gauntlet.name=<$dark_cyan>Gauntlet Parkour</$dark_cyan>
gui.map_details.map_info_tab.type.parkour.gauntlet.lore=\
  <$light_gray>Focused on speed and reaction time.</$light_gray>
gui.map_details.map_info_tab.type.parkour.speedrun.name=<$dark_cyan>Speedrun Parkour</$dark_cyan>
gui.map_details.map_info_tab.type.parkour.speedrun.lore=\
  <$light_gray>Reach the end as fast as possible.</$light_gray>
gui.map_details.map_info_tab.type.parkour.rankup.name=<$dark_cyan>Rankup Parkour</$dark_cyan>
gui.map_details.map_info_tab.type.parkour.rankup.lore=\
  <$light_gray>A hardcore challenge without checkpoints.</$light_gray>
gui.map_details.map_info_tab.type.parkour.dropper.name=<$dark_cyan>Dropper Parkour/$dark_cyan>
gui.map_details.map_info_tab.type.parkour.dropper.lore=\
  <$light_gray>Fall into a safe zone while avoiding obstacles.</$light_gray>
gui.map_details.map_info_tab.type.parkour.informative.name=<$dark_cyan>Informative Parkour</$dark_cyan>
gui.map_details.map_info_tab.type.parkour.informative.lore=\
  <$light_gray>Maps that aim to teach players about parkour.</$light_gray>
gui.map_details.map_info_tab.type.parkour.generic.name=<$dark_cyan>Generic Parkour</$dark_cyan>
gui.map_details.map_info_tab.type.parkour.generic.lore=\
  <$light_gray>A parkour map that doesn't fit in other categories.</$light_gray>
gui.map_details.map_info_tab.type.parkour.one_jump.name=<$dark_cyan>One Jump Parkour</$dark_cyan>
gui.map_details.map_info_tab.type.parkour.one_jump.lore=\
  <$light_gray>A single or few jumps that require specific</$light_gray>\n\
  <$light_gray>strategies and precise setups to beat.</$light_gray>
gui.map_details.map_info_tab.type.parkour.sectioned.name=<$dark_cyan>Sectioned Parkour</$dark_cyan>
gui.map_details.map_info_tab.type.parkour.sectioned.lore=\
  <$light_gray>Split up into multiple checkpointed parts.</$light_gray>
gui.map_details.map_info_tab.type.building.showcase.name=<$dark_green>Building Showcase</$dark_green>
gui.map_details.map_info_tab.type.building.showcase.lore=\
  <$light_gray>The presentation of a completed build.</$light_gray>
gui.map_details.map_info_tab.type.building.tutorial.name=<$dark_green>Building Tutorial</$dark_green>
gui.map_details.map_info_tab.type.building.tutorial.lore=\
  <$light_gray>Teaches something about building maps, such as</$light_gray>\n\
  <$light_gray>composition, or how to use specific build tools.</$light_gray>
gui.map_details.map_info_tab.type.building.educational.name=<$dark_green>Educational</$dark_green>
gui.map_details.map_info_tab.type.building.educational.lore=\
  <$light_gray>Maps that impart knowledge on some subject, like academics, or science.</$light_gray>
gui.map_details.map_info_tab.type.building.map_pack.name=<$dark_green>Map Pack</$dark_green>
gui.map_details.map_info_tab.type.building.map_pack.lore=\
  <$light_gray>Bundled assets, such as trees or rocks.</$light_gray>
gui.map_details.map_info_tab.type.building.generic.name=<$dark_green>Generic Building</$dark_green>
gui.map_details.map_info_tab.type.building.generic.lore=\
  <$light_gray>A building map that doesn't fit in other categories.</$light_gray>
# Map Details GUI - Map Info Tab - Map Tags
gui.map_details.map_info_tab.no_tags.name=<$white>No Tags</$white>
gui.map_details.map_info_tab.no_tags.lore=<$light_gray>This map doesn't have any tags applied!</$light_gray>
gui.map_details.map_info_tab.tags.name=<$white><0></$white>
gui.map_details.map_info_tab.tags_description.name=<$white>Map Tags</$white>
gui.map_details.map_info_tab.tags_description.lore=\
  <$light_gray>The tags the map creator chose that</$light_gray>\n\
  <$light_gray>best describe what they are making.</$light_gray>
# // TODO make a separate translation key for tags that displays them by type (gameplay or visual)
# Map Details GUI - Map Info Tab - Map Settings
gui.map_details.map_info_tab.setting.name=<$white>Map Settings</$white>
gui.map_details.map_info_tab.setting.lore=\
  <$light_gray>Maps with customized gameplay elements, such as altered</$light_gray>\n\
  <$light_gray>physics interactions or restricted movement mechanics.</$light_gray>
gui.map_details.map_info_tab.no_settings.name=<$white>No Settings</$white>
gui.map_details.map_info_tab.no_settings.lore=<$light_gray>This map doesn't have any settings enabled!</$light_gray>
gui.map_details.map_info_tab.no_settings_building.name=<$white>No Settings</$white>
gui.map_details.map_info_tab.no_settings_building.lore=<$light_gray>Building map types cannot have settings!</$light_gray>
gui.map_details.map_info_tab.settings.name=<$white><0></$white>
gui.map_details.map_info_tab.settings_description.name=<$white>Map Settings</$white>
gui.map_details.map_info_tab.settings_description.lore=\
  <$light_gray>The settings the map creator chose</$light_gray>\n\
  <$light_gray>to enhance their map's gameplay.</$light_gray>
# Map Details GUI - Map Stats Tab // TODO
gui.map_details.map_stats_tab.information.name=<$yellow>Information</$yellow>
gui.map_details.map_stats_tab.information.lore=
gui.map_details.map_stats_tab.name=<$white>Map Stats</$white>
gui.map_details.map_stats_tab.lore=<$red>Coming Later!</$red>
# Map Details GUI - Top Times Tab
gui.map_details.top_times_tab.information.name=<$yellow>Information</$yellow>
gui.map_details.top_times_tab.information.lore=\
  <$light_gray>Showcasing the 10 fastest completion times, the 10 earliest completions, and</$light_gray>\n\
  <$light_gray>your personal best time, inspiring personal improvement and friendly competition.</$light_gray>
gui.map_details.top_times_tab.name=<$white>Top Times</$white>
gui.map_details.top_times_tab.toggle_first_completions.name=<$white>Toggle First Completions</$white>
gui.map_details.top_times_tab.toggle_first_completions.lore=
gui.map_details.top_times_tab.toggle_fastest_completions.name=<$white>Toggle Fastest Completions</$white>
gui.map_details.top_times_tab.toggle_fastest_completions.lore=
gui.map_details.top_times_tab.report_time.name=<$red>Report Time</$red>
gui.map_details.top_times_tab.report_time.lore=
gui.map_details.top_times_tab.first_place.name=<$gold>1st Place</$gold> <$dark_gray>-</$dark_gray><0>
gui.map_details.top_times_tab.first_place.lore=<$light_gray>Time:</$light_gray> <$white><1></$white>
gui.map_details.top_times_tab.second_place.name=<$silver>2nd Place</$silver> <$dark_gray>-</$dark_gray><0>
gui.map_details.top_times_tab.second_place.lore=<$light_gray>Time:</$light_gray> <$white><1></$white>
gui.map_details.top_times_tab.third_place.name=<$bronze>3rd Place</$bronze> <$dark_gray>-</$dark_gray><0>
gui.map_details.top_times_tab.third_place.lore=<$light_gray>Time:</$light_gray> <$white><1></$white>
gui.map_details.top_times_tab.fourth.name=<$light_gray>4th Place</$light_gray>
gui.map_details.top_times_tab.fourth.lore=
gui.map_details.top_times_tab.fifth.name=<$light_gray>5th Place</$light_gray>
gui.map_details.top_times_tab.fifth.lore=
gui.map_details.top_times_tab.other_top_times.name=<$light_gray>Other Top Times</$light_gray>
gui.map_details.top_times_tab.other_top_times.lore=
gui.map_details.top_times_tab.personal_best.name=<$light_gray>Your Personal Best</$light_gray>
gui.map_details.top_times_tab.personal_best.lore=
# Map Details GUI - Map Reviews Tab
gui.map_details.map_reviews_tab.information.name=<$yellow>Information</$yellow>
gui.map_details.map_reviews_tab.information.lore=\
  <$light_gray>See what others have to say about</$light_gray>\n\
  <$light_gray>this map or share your own thoughts!</$light_gray>
gui.map_details.map_reviews_tab.name=<$white>Map Reviews</$white>
gui.map_details.map_reviews_tab.lore=<$red>Coming Later!</$red>
# 0: Commenter's name
# 1: Commenter's review score
gui.map_details.map_reviews.review.name=<0> <1>
gui.map_details.map_reviews.review.lore=
gui.create_maps.new_map.title.name=<$white>New Map</$white>