gui.map_collection.information.name=<$yellow>Information</$yellow>
gui.map_collection.information.lore=\
  <$light_gray>View a list of maps curated by a community member.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Get Collection ID</$white_gray>

gui.map_collection.name.name=<$light_gray>by <0></$light_gray>
gui.edit_map_collection.name.name=<$light_gray>by <0></$light_gray>
gui.edit_map_collection.name.lore=\n$LMB <$white_gray>Click to Edit Collection Name</$white_gray>

gui.edit_map_collection.icon.name=<$white>Change Display Item</$white>
gui.edit_map_collection.icon.lore=\
  <$light_gray>Current: </$light_gray><$light_blue><0></$light_blue>\n\n\
  <$light_gray>Choose a vanilla Minecraft item</$light_gray>\n\
  <$light_gray>that best represents your collection.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Change</$white_gray>

gui.edit_map_collection.search.name=<$white>Search Maps</$white>
gui.edit_map_collection.search.lore=\
  <$light_gray>Search for maps to add to your collection.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Search</$white_gray>