#
# Profile
#

#
# Cosmetics
#

item.mapmaker.cosmetics.name=<$white>Cosmetic Menu</$white> $RMB_ITEM
item.mapmaker.cosmetics.lore=\
  <$light_gray>Customize your character with style!</$light_gray>

gui.cosmetics.information.name=<$yellow>Information</$yellow>
gui.cosmetics.information.lore=\
  <$light_gray>Personalize your look with a range of</$light_gray>\n\
  <$light_gray>modeled cosmetics and special effects.</$light_gray>

gui.cosmetics.wardrobe.name=<$white>Wardrobe</$white>
gui.cosmetics.wardrobe.lore=\
  <$light_gray>View all your currently equipped</$light_gray>\n\
  <$light_gray>cosmetics and quickly switch to others.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.cosmetics.show_locked.off.name=<$white>Filter By</$white>
gui.cosmetics.show_locked.off.lore=\
  <$dark_gray> »</$dark_gray> <$light_gray>All</$light_gray>\n\
  <$dark_gray> »</$dark_gray> <$lime>Owned</$lime>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>
gui.cosmetics.show_locked.on.name=<$white>Filter By</$white>
gui.cosmetics.show_locked.on.lore=\
  <$dark_gray> »</$dark_gray> <$lime>All</$lime>\n\
  <$dark_gray> »</$dark_gray> <$light_gray>Owned</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.cosmetics.tab_name.name=<0>

#
# Tabs
#

gui.cosmetics.tab.headwear.deselected.name=<$white>Headwear</$white>
gui.cosmetics.tab.headwear.deselected.lore=\
  <$light_gray>Hats to top off your character's style.</$light_gray>\n\n\
  $LMB <$white_gray>Click to View</$white_gray>
gui.cosmetics.tab.headwear.selected.name=<$white>Headwear</$white>
gui.cosmetics.tab.headwear.selected.lore=\
  <$light_gray>Hats to top off your character's style.</$light_gray>

gui.cosmetics.tab.backwear.deselected.name=<$white>Backwear</$white>
gui.cosmetics.tab.backwear.deselected.lore=\
  <$light_gray>Modeled items carried on your back.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
gui.cosmetics.tab.backwear.selected.name=<$white>Backwear</$white>
gui.cosmetics.tab.backwear.selected.lore=\
  <$light_gray>Modeled items carried on your back.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.cosmetics.tab.accessories.deselected.name=<$white>Accessories</$white>
gui.cosmetics.tab.accessories.deselected.lore=\
  <$light_gray>Hand-held items with special effects.</$light_gray>\n\n\
  $LMB <$white_gray>Click to View</$white_gray>
gui.cosmetics.tab.accessories.selected.name=<$white>Accessories</$white>
gui.cosmetics.tab.accessories.selected.lore=\
  <$light_gray>Hand-held items with special effects.</$light_gray>

gui.cosmetics.tab.companions.deselected.name=<$white>Companions</$white>
gui.cosmetics.tab.companions.deselected.lore=\
  <$light_gray>Pets that follow your movement.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
gui.cosmetics.tab.companions.selected.name=<$white>Companions</$white>
gui.cosmetics.tab.companions.selected.lore=\
  <$light_gray>Pets that follow your movement.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.cosmetics.tab.emotes.deselected.name=<$white>Emotes</$white>
gui.cosmetics.tab.emotes.deselected.lore=\
  <$light_gray>Express yourself with animated emotes.</$light_gray>\n\n\
  <$red>Coming Later!</$red>
gui.cosmetics.tab.emotes.selected.name=<$white>Emotes</$white>
gui.cosmetics.tab.emotes.selected.lore=\
  <$light_gray>Express yourself with animated emotes.</$light_gray>\n\n\
  <$red>Coming Later!</$red>

gui.cosmetics.tab.particles.deselected.name=<$white>Particles</$white>
gui.cosmetics.tab.particles.deselected.lore=\
  <$light_gray>Special effects that appear around you.</$light_gray>\n\n\
  $LMB <$white_gray>Click to View</$white_gray>
gui.cosmetics.tab.particles.selected.name=<$white>Particles</$white>
gui.cosmetics.tab.particles.selected.lore=\
  <$light_gray>Special effects that appear around you.</$light_gray>

gui.cosmetics.tab.victory_effects.deselected.name=<$white>Victory Effects</$white>
gui.cosmetics.tab.victory_effects.deselected.lore=\
  <$light_gray>Celebrate your map completions with fun visuals.</$light_gray>\n\n\
  $LMB <$white_gray>Click to View</$white_gray>
gui.cosmetics.tab.victory_effects.selected.name=<$white>Victory Effects</$white>
gui.cosmetics.tab.victory_effects.selected.lore=\
  <$light_gray>Celebrate your map completions with fun visuals.</$light_gray>

#
# Achievements
#

#
# Statistics
#