# Categories
gui.report_map.category.cheated.name=Cheated Verification
gui.report_map.category.discrimination.name=Discrimination
gui.report_map.category.explicit_content.name=Inappropriate/Explicit Content
gui.report_map.category.spam.name=Spam
gui.report_map.category.troll.name=Troll Map

# Comment
gui.report_map.add_comment.name=Add Comment
gui.report_map.add_comment.lore=Current: <0>\n\nClick to change\nRight-click to reset
gui.report_map.add_comment.none=None

# Submit button
gui.report_map.submit.name=Submit Report
gui.report_map.submit.header=Reasons:
gui.report_map.submit.category=» <0>
gui.report_map.submit.footer=\nComment: <0>\n\nClick to submit

# Confirmations
gui.report_map.submit.success=Report submitted successfully! Thank you for helping to make Map Maker better for everyone.
gui.report_map.submit.failure=Failed to submit report. Please try again later.
