gui.report_map.information.name=<$yellow>Information</$yellow>
gui.report_map.information.lore=<$light_gray>Submit a report on this map for staff to review.</$light_gray>

gui.report_map.map_id.name=<$white>Map ID:</$white> <$light_gray><0></$light_gray>

#
# CATEGORIES
#

gui.report_map.category.cheated.off.name=<$white>Cheated Verification</$white>
gui.report_map.category.cheated.off.lore=\
  <$light_gray>This map was verified using hacks or exploits.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Select</$white_gray>
gui.report_map.category.cheated.on.name=<$white>Cheated Verification</$white>
gui.report_map.category.cheated.on.lore=\
  <$light_gray>This map was verified using hacks or exploits.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Deselect</$white_gray>

gui.report_map.category.discrimination.off.name=<$white>Discrimination</$white>
gui.report_map.category.discrimination.off.lore=\
  <$light_gray>The content in this map is discriminatory</$light_gray>\n\
  <$light_gray>against a specific group of players.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Select</$white_gray>
gui.report_map.category.discrimination.on.name=<$white>Discrimination</$white>
gui.report_map.category.discrimination.on.lore=\
  <$light_gray>The content in this map is discriminatory</$light_gray>\n\
  <$light_gray>against a specific group of players.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Deselect</$white_gray>

gui.report_map.category.explicit_content.off.name=<$white>Inappropriate/Explicit Content</$white>
gui.report_map.category.explicit_content.off.lore=\
  <$light_gray>This map depicts mature content that isn't</$light_gray>\n\
  <$light_gray>appropriate for younger audiences. This</$light_gray>\n\
  <$light_gray>includes things that are suggestive in nature.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Select</$white_gray>
gui.report_map.category.explicit_content.on.name=<$white>Inappropriate/Explicit Content</$white>
gui.report_map.category.explicit_content.on.lore=\
  <$light_gray>This map depicts mature content that isn't</$light_gray>\n\
  <$light_gray>appropriate for younger audiences. This</$light_gray>\n\
  <$light_gray>includes things that are suggestive in nature.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Deselect</$white_gray>

gui.report_map.category.spam.off.name=<$white>Spam</$white>
gui.report_map.category.spam.off.lore=\
  <$light_gray>This map is low quality and designed to waste time.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Select</$white_gray>
gui.report_map.category.spam.on.name=<$white>Spam</$white>
gui.report_map.category.spam.on.lore=\
  <$light_gray>This map is low quality and designed to waste time.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Deselect</$white_gray>

gui.report_map.category.dcma.off.name=<$white>Stolen Content</$white>
gui.report_map.category.dcma.off.lore=\
  <$light_gray>Content in this map is not the</$light_gray>\n\
  <$light_gray>original work of its publisher.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Select</$white_gray>
gui.report_map.category.dcma.on.name=<$white>Stolen Content</$white>
gui.report_map.category.dcma.on.lore=\
  <$light_gray>Content in this map is not the</$light_gray>\n\
  <$light_gray>original work of its publisher.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Deselect</$white_gray>

#
# COMMENT
#

gui.report_map.add_comment.name=<$white>Add Note</$white>
gui.report_map.add_comment.lore=\
  <$light_gray>Current: </$light_gray><$light_blue><0></$light_blue>\n\n\
  <$light_gray>Attach an optional comment with any</$light_gray>\n\
  <$light_gray>additional context for staff to read.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>\n\
  $SHIFT_LMB <$white_gray>Shift + Click to Reset</$white_gray>
gui.report_map.add_comment.none=<$red>None</$red>

#
# SUBMIT
#

gui.report_map.submit.name=<$lime>Submit Report</$lime>
gui.report_map.submit.header=<$light_gray>Reasons:</$light_gray>
gui.report_map.submit.category=<$dark_gray> »</$dark_gray> <$white><0></$white>
gui.report_map.submit.footer=\n\
  <$light_gray>Comment: </$light_gray><$light_blue><0></$light_blue>\n\n\
  $LMB <$white_gray>Click to Submit</$white_gray>
gui.report_map.submit.missing_categories.name=<$red>Submit Report</$red>
gui.report_map.submit.missing_categories.lore=\
  <$light_gray>You need at least one reason to submit a report!</$light_gray>
gui.report_map.submit.error=$DENY<$light_gray>You cannot submit a report with no reasons!</$light_gray>

#
# CONFIRMATION
#

gui.report_map.submit.success=$CONFIRM<$light_gray>Report submitted successfully! Thank you for helping to make Map Maker better for everyone.</$light_gray>
gui.report_map.submit.failure=$DENY<$light_gray>Failed to submit report, please try again later! If this issue persists, please contact an <$red>Administrator</$red>.</$light_gray>