gui.rate_map.information.name=<$yellow>Information</$yellow>
gui.rate_map.information.lore=\
  <$light_gray>Did you enjoy this map? Share your thoughts!</$light_gray>\n\n\
  $NOTE <$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>Your rating will contribute positively or<$light_gray>\n\
  <$light_gray>negatively to the map's quality level.</$light_gray>
gui.map_rating.like_off.name=<$lime>Like</$lime>
gui.map_rating.like_off.lore=\
  <$light_gray>You enjoyed this map and want</$light_gray>\n\
  <$light_gray>to give it a positive rating.</$light_gray>\n\n\
  $LMB <$light_gray> Click to Select</$light_gray>
gui.map_rating.like_on.name=<$lime>Like</$lime>
gui.map_rating.like_on.lore=\
  <$light_gray>You enjoyed this map and</$light_gray>\n\
  <$light_gray>gave it a positive rating.</$light_gray>
gui.map_rating.dislike_off.name=<$red>Dislike</$red>
gui.map_rating.dislike_off.lore=\
  <$light_gray>You did not enjoy this map and</$light_gray>\n\
  <$light_gray>want to give it a negative rating.</$light_gray>\n\n\
  $LMB <$light_gray> Click to Select</$light_gray>
gui.map_rating.dislike_on.name=<$red>Dislike</$red>
gui.map_rating.dislike_on.lore=\
  <$light_gray>You did not enjoy this map</$light_gray>\n\
  <$light_gray>and gave it a negative rating.</$light_gray>