# Create Maps GUI - New Map Creation Settings Screen
# TODO improve this page
gui.create_maps.new_map.information.name=<$yellow>Information</$yellow>
gui.create_maps.new_map.information.lore=\
  <$light_gray>Choose settings on how to generate your world.</$light_gray>
gui.create_maps.new_map.generator.name=<$white>World Generator</$white>
gui.create_maps.new_map.generator.lore=<$light_gray>Choose the world type that best suites your needs.</$light_gray>
# DEFAULT SELECTION
gui.create_maps.new_map.generator.void.name=<$purple>Void World</$purple>
gui.create_maps.new_map.generator.void.lore=\
  <$light_gray>An empty expanse of nothingness. A</$light_gray>\n\
  <$light_gray>blank slate full of infinite possibilities!</$light_gray>
gui.create_maps.new_map.generator.flat.name=<$lime>Flat World<$lime>
gui.create_maps.new_map.generator.flat.lore=\
  <$light_gray>A vast, open landscape with no natural</$light_gray>\n\
  <$light_gray>terrain variations, great for building on.</$light_gray>\n\n\
  <$red>Coming Later!<$red>
gui.create_maps.new_map.generator.ocean.name=<$light_blue>Ocean World<$light_blue>
gui.create_maps.new_map.generator.ocean.lore=\
  <$light_gray>An open stretch of water, perfect for</$light_gray>\n\
  <$light_gray>creating islands, ships, and more.</$light_gray>\n\n\
  <$red>Coming Later!<$red>
gui.create_maps.new_map.generator.more.name=<$light_gray>More Generation</$light_gray>
gui.create_maps.new_map.generator.more.lore=<$red>Coming Later!<$red>
gui.create_maps.new_map.size.name=<$white>World Size</$white>
gui.create_maps.new_map.size.lore=<$light_gray>Determines how big the area you can build in is.</$light_gray>
# DEFAULT SIZE AND SELECTION - Normal Map World Size (150 Normal, 250 Personal World)
gui.create_maps.new_map.size.normal.name=<$white>Normal</$white>
gui.create_maps.new_map.size.normal.lore=\
  <$light_gray>150 x 150 Blocks</$light_gray>
# Large Map World Size (300 Normal, 500 Personal World) - 50 Cubits
gui.create_maps.new_map.size.large.name=<$white>Large</$white>
gui.create_maps.new_map.size.large.lore=\
  <$light_gray>300 x 300 Blocks</$light_gray>\n\n\
  <$red>Coming Later!</$red>
# Massive Map World Size (600 Normal, 1,000 Personal World) - 100 Cubits
gui.create_maps.new_map.size.massive.name=<$white>Massive</$white>
gui.create_maps.new_map.size.massive.lore=\
  <$light_gray>600 x 600 Blocks</$light_gray>\n\n\
  <$red>Coming Later!</$red>
# Colossal Map World Size (1,200 Normal, Custom Y Height up to 500 (TBD), 2,000 Personal World) - 200 Cubits
gui.create_maps.new_map.size.colossal.name=<$white>Colossal</$white>
gui.create_maps.new_map.size.colossal.lore=\
  <$light_gray>1,200 x 1,200 Blocks Wide, 500 Blocks Tall</$light_gray>\n\n\
  <$red>Coming Later!</$red>
gui.create_maps.new_map.submit.name=<$lime>Confirm Settings</$lime>
gui.create_maps.new_map.submit.lore=\
  <$light_gray>World Generator:</$light_gray> <$purple>Void</$purple>\n\
  <$light_gray>World Size:</$light_gray> <$white>Normal</$white>\n\n\
  <$light_gray>Create a world with your chosen settings.</$light_gray>
gui.create_maps.new_map.reset_to_default.name=<$white>Reset to Default</$white>
gui.create_maps.new_map.reset_to_default.lore=<$red>Coming Later!</$red>
gui.create_maps.new_map.more_options.name=<$white>More Options</$white>
gui.create_maps.new_map.more_options.lore=<$red>Coming Later!</$red>