item.hdb.head.name=<$white><0></$white>
hdb.category.alphabet.name=<$white>Alphabet</$white>
hdb.category.animals.name=<$white>Animals</$white>
hdb.category.blocks.name=<$white>Blocks</$white>
hdb.category.decoration.name=<$white>Decoration</$white>
hdb.category.food-drinks.name=<$white>Food & Drinks</$white>
hdb.category.humans.name=<$white>Humans</$white>
hdb.category.humanoid.name=<$white>Humanoid</$white>
hdb.category.miscellaneous.name=<$white>Miscellaneous</$white>
hdb.category.monsters.name=<$white>Monsters</$white>
hdb.category.plants.name=<$white>Plants</$white>
command.hdb.give.result=$CONFIRM<$light_gray>You have been given a custom head.</$light_gray>
command.hdb.give.no_result=$DENY<$light_gray>That is not a custom head!</$light_gray>
### TODO make the above 2 translation keys not giga stink