item.hdb.head.name=<$white><0></$white>
gui.hdb.browser.information.name=<$yellow>Information</$yellow>
gui.hdb.browser.information.lore=\
  <$light_gray>A basic, WIP custom implementation</$light_gray>\n\
  <$light_gray>of <$light_blue>https://minecraft-heads.com/</$light_blue>.</$light_gray>
gui.hdb.browser.title.name=<$white><0></$white>
gui.hdb.browser.search.name=<$azure>Search Heads</$azure>
gui.hdb.browser.search.lore=\
  <$light_gray>Find a custom head by its name.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Edit</$white_gray>
hdb.category.alphabet.name=<$white>Alphabet</$white>
hdb.category.animals.name=<$white>Animals</$white>
hdb.category.blocks.name=<$white>Blocks</$white>
hdb.category.decoration.name=<$white>Decoration</$white>
hdb.category.food-drinks.name=<$white>Food & Drinks</$white>
hdb.category.humans.name=<$white>Humans</$white>
hdb.category.humanoid.name=<$white>Humanoid</$white>
hdb.category.miscellaneous.name=<$white>Miscellaneous</$white>
hdb.category.monsters.name=<$white>Monsters</$white>
hdb.category.plants.name=<$white>Plants</$white>
command.hdb.give.result=$CONFIRM<$light_gray>You have been given a custom head.</$light_gray>
command.hdb.give.no_result=$DENY<$light_gray>That is not a custom head!</$light_gray>
### TODO make the above 2 translation keys not giga stink