# Hotbars

# Lobby Hotbar
hotbar.lobby.play_maps.name=<blue>Play Maps</blue> <dark_gray>[<gray>Right Click</gray>]</dark_gray> 
hotbar.lobby.play_maps.lore=<gray>Browse a large catalog of unique</gray>\n\
   <gray>maps, all created by players!</gray>
hotbar.lobby.create_maps.name=<dark_aqua>Create Maps</dark_aqua> <dark_gray>[<gray>Right Click</gray>]</dark_gray>
hotbar.lobby.create_maps.lore=<gray>Create a map using our custom tools</gray>\n\
   <gray>and publish it for others to play!</gray>
hotbar.lobby.official_content.name=Official Content
hotbar.lobby.official_content.lore=
hotbar.lobby.my_profile.name=My Profile
hotbar.lobby.my_profile.lore=



# Regular Play Hotbar
hotbar.regular_play.map_details=Map Details [Right Click]
hotbar.regular_play.map_details.lore=View the map preview where you can\n\
   rate the map, edit statistics, and more.

hotbar.regular_play.return_to_checkpoint=Return to Checkpoint [Right Click]
hotbar.regular_play.return_to_checkpoint.lore=Teleport back to your last activated Checkpoint.

hotbar.regular_play.enter_spectator_mode=Spectator Mode [Right Click]
hotbar.regular_play.enter_spectator_mode.lore=Spectator Mode allows you to practice jumps and fly.\n\
   You cannot complete a map in Spectator Mode.

hotbar.regular_play.reset=Reset Progress [Right Click]
hotbar.regular_play.reset.lore=Fully reset your progress and return to the start of the map.

hotbar.regular_play.leave=Leave Map [Right Click]
hotbar.regular_play.leave.lore=Exit the map and return to the lobby. Your\n\
   last location and progress will be saved.



# Regular Play Spectator Mode Hotbar
hotbar.regular_play.spectator_mode.map_details=Map Details [Right Click]
hotbar.regular_play.spectator_mode.map_details.lore=View the map preview where you can\n\
   rate the map, edit statistics, and more.

hotbar.regular_play.spectator_mode.return_to_checkpoint=Return to Checkpoint [Right Click]
hotbar.regular_play.spectator_mode.return_to_checkpoint.lore=Teleport back to your last artificial checkpoint\n\
   or where you entered Spectator Mode.

hotbar.regular_play.spectator_mode.set_checkpoint=Set Checkpoint [Right Click]
hotbar.regular_play.spectator_mode.set_checkpoint.lore=Set a temporary artificial checkpoint for practicing.

hotbar.regular_play.spectator_mode.exit_spectator_mode=Exit Spectator Mode [Right Click]
hotbar.regular_play.spectator_mode.exit_spectator_mode.lore=Return to playing the map from where you entered Spectator Mode.

hotbar.regular_play.spectator_mode.toggle_flight.on=Flight » Disabled [Right Click]
hotbar.regular_play.spectator_mode.toggle_flight.on.lore=Toggle your flight status on.
hotbar.regular_play.spectator_mode.toggle_flight.off=Flight » Enabled [Right Click]
hotbar.regular_play.spectator_mode.toggle_flight.off.lore=Toggle your flight status off.

hotbar.regular_play.spectator_mode.leave=Leave Map [Right Click]
hotbar.regular_play.spectator_mode.leave.lore=Exit the map and return to the lobby. Your\n\
   last location and progress will be saved.



# Regular Play Finished Mode Hotbar
hotbar.regular_play.finished_mode.map_details=Map Details [Right Click]
hotbar.regular_play.finished_mode.map_details.lore=View the map preview where you can\n\
   rate the map, edit statistics, and more.

hotbar.regular_play.finished_mode.review_map=Review Map [Right Click]
hotbar.regular_play.finished_mode.review_map.lore=Give a rating to the map.

hotbar.regular_play.finished_mode.play_similar_map=Play Similar Map [Right Click]
hotbar.regular_play.finished_mode.play_similar_map.lore=Join a map similar in tags, difficulty, etc.

hotbar.regular_play.finished_mode.reset=Reset Progress [Right Click]
hotbar.regular_play.finished_mode.reset.lore=Fully reset your progress and return to the start of the map.

hotbar.regular_play.finished_mode.leave=Leave Map [Right Click]
hotbar.regular_play.finished_mode.leave.lore=Exit the map and return to the lobby. Your\n\
   last location and progress will be saved.



# Map Creator Hotbar
hotbar.map_creator.map_details=Map Details [Right Click]
hotbar.map_creator.map_details.lore=View and edit map details.

hotbar.map_creator.builder_menu=Builder Menu [Right Click]
hotbar.map_creator.builder_menu.lore=Various tools, settings, and custom blocks\n\
   that can help you create and improve your map.

hotbar.map_creator.enter_testing_mode=Testing Mode [Right Click]
hotbar.map_creator.enter_testing_mode.lore=Enter a mode that allows you to test\n\
   your map as if you were a player.

hotbar.map_creator.teleport_to_start=Teleport to Start [Right Click]
hotbar.map_creator.teleport_to_start.lore=Teleport to the starting location\n\
   of your map (0,0 by default).

hotbar.map_creator.save_and_exit=Save and Exit [Right Click]
hotbar.map_creator.save_and_exit.lore=Exit your map and return to the lobby. Your\n\
   last location and build progress will be saved.



# Map Creator Testing Mode Hotbar
hotbar.map_creator.testing_mode.map_details=Map Details [Right Click]
hotbar.map_creator.testing_mode.map_details.lore=View and edit map details.

hotbar.map_creator.testing_mode.return_to_checkpoint=Return to Checkpoint [Right Click]
hotbar.map_creator.testing_mode.return_to_checkpoint.lore=Teleport back to your last activated Checkpoint.

hotbar.map_creator.testing_mode.set_checkpoint=Set Checkpoint [Right Click]
hotbar.map_creator.testing_mode.set_checkpoint.lore=Set a temporary artificial checkpoint for practicing.

hotbar.map_creator.testing_mode.exit_testing_mode=Exit Testing Mode [Right Click]
hotbar.map_creator.testing_mode.exit_testing_mode.lore=Return to building your map from where you entered Testing Mode.

hotbar.map_creator.testing_mode.finished_mode.reset=Reset Progress [Right Click]
hotbar.map_creator.testing_mode.finished_mode.reset.lore=Return to where you entered Testing Mode.

hotbar.map_creator.testing_mode.save_and_exit=Leave Map [Right Click]
hotbar.map_creator.testing_mode.save_and_exit.lore=Exit your map and return to the lobby. Your\n\
   last location and build progress will be saved.