# Hotbars

# Lobby Hotbar
item.mapmaker.play_maps.name=<$azure>Play Maps</$azure> $RMB_ITEM
item.mapmaker.play_maps.lore=\
  <$light_gray>Browse a large catalog of unique</$light_gray>\n\
  <$light_gray>content, all created by players!</$light_gray>
item.mapmaker.create_maps.name=<$dark_cyan>Create Maps</$dark_cyan> $RMB_ITEM
item.mapmaker.create_maps.lore=\
  <$light_gray>Create something using our custom tools</$light_gray>\n\
  <$light_gray>and publish it for others to play!</$light_gray>



# Regular Play Hotbar
item.mapmaker.map_details.name=<$white>Map Details</$white> $RMB_ITEM
item.mapmaker.map_details.lore=\
  <$light_gray>View the map's information, like its type and tags.</$light_gray>

item.mapmaker.return_to_checkpoint.name=<$white>Return to Checkpoint</$white> $RMB_ITEM
item.mapmaker.return_to_checkpoint.lore=\
  <$light_gray>Teleport back to your last activated Checkpoint.</$light_gray>

item.mapmaker.enter_spectator.name=<$white>Enter Spectator Mode</$white> $RMB_ITEM
item.mapmaker.enter_spectator.lore=\
  <$light_gray>Allows you to practice jumps, fly, and more.</$light_gray>\n\n\
  $NOTE <$yellow>NOTE</$yellow> $NOTE\n\
  <$light_gray>You cannot complete a map in Spectator Mode.</$light_gray>

item.mapmaker.reset_savestate.name=<$white>Reset Progress</$white> $RMB_ITEM
item.mapmaker.reset_savestate.lore=\
  <$light_gray>Fully reset your progress and</$light_gray>\n\
  <$light_gray>return to the start of the map.</$light_gray>\n\n\
  $WARNING <$yellow>WARNING</$yellow> $WARNING\n\
  <$light_gray>After confirmation, this cannot be undone!</$light_gray>

item.mapmaker.return_to_hub.name=<$white>Leave Map</$white> $RMB_ITEM
item.mapmaker.return_to_hub.lore=\
  <$light_gray>Exit the map and return to the lobby. Your</$light_gray>\n\
  <$light_gray>last location and progress will be saved.</$light_gray>



# Regular Play Spectator Mode Hotbar
item.mapmaker.return_to_spectator_checkpoint.name=<$white>Return to Spectator Checkpoint</$white> $RMB_ITEM
item.mapmaker.return_to_spectator_checkpoint.lore=\
  <$light_gray>Teleport back to your last artificial checkpoint,</$light_gray>\n\
  <$light_gray>or by default, where you entered Spectator Mode.</$light_gray>

item.mapmaker.set_spectator_checkpoint.name=<$white>Set Spectator Checkpoint</$white> $RMB_ITEM
item.mapmaker.set_spectator_checkpoint.lore=\
  <$light_gray>Set a temporary, artificial checkpoint for practicing jumps.</$light_gray>

item.mapmaker.exit_spectator.name=<$white>Exit Spectator Mode</$white> $RMB_ITEM
item.mapmaker.exit_spectator.lore=\
  <$light_gray>Return to playing the map from</$light_gray>\n\
  <$light_gray>where you entered Spectator Mode.</$light_gray>

# TODO switch the item and its icon when right-clicked for better visual clarity
item.mapmaker.toggle_flight.name=<$white>Toggle Fly</$white>
item.mapmaker.toggle_flight.lore=<$light_gray>Toggle your flight status on or off.</$light_gray>

# OLD FLIGHT TRANSLATIONS KEYS (will remove/fix after the above TODO is done)
item.spectator.toggle_flight.on.name=Flight » Disabled $RMB_ITEM
item.spectator.toggle_flight.on.lore=Toggle your flight status on.
item.spectator.toggle_flight.off=Flight » Enabled $RMB_ITEM
item.spectator.toggle_flight.off.lore=Toggle your flight status off.



# Regular Play Finished Mode Hotbar
item.mapmaker.review_map.name=Review Map $RMB_ITEM
item.mapmaker.review_map.lore=Give a rating to the map.

item.finished.play_similar.name=Play Similar Map $RMB_ITEM
item.finished.play_similar.lore=Join a map similar in tags, difficulty, etc.



# Map Creator Hotbar
item.build.map_details=Map Details $RMB_ITEM
item.build.map_details.lore=View and edit map details.

item.build.builder_menu=Builder Menu $RMB_ITEM
item.build.builder_menu.lore=Various tools, settings, and custom blocks\n\
   that can help you create and improve your map.

item.build.enter_testing_mode=Testing Mode $RMB_ITEM
item.build.enter_testing_mode.lore=Enter a mode that allows you to test\n\
   your map as if you were a player.

item.build.teleport_to_start=Teleport to Start $RMB_ITEM
item.build.teleport_to_start.lore=Teleport to the starting location\n\
   of your map (0,0 by default).

item.build.save_and_exit=Save and Exit $RMB_ITEM
item.build.save_and_exit.lore=Exit your map and return to the lobby. Your\n\
   last location and build progress will be saved.



# Map Creator Testing Mode Hotbar
item.test.map_details=Map Details $RMB_ITEM
item.test.map_details.lore=View and edit map details.

item.test.return_to_checkpoint=Return to Checkpoint $RMB_ITEM
item.test.return_to_checkpoint.lore=Teleport back to your last activated Checkpoint.

item.test.set_checkpoint=Set Checkpoint $RMB_ITEM
item.test.set_checkpoint.lore=Set a temporary artificial checkpoint for practicing.

item.test.exit_testing_mode=Exit Testing Mode $RMB_ITEM
item.test.exit_testing_mode.lore=Return to building your map from where you entered Testing Mode.

item.test.finished_mode.reset=Reset Progress $RMB_ITEM
item.test.finished_mode.reset.lore=Return to where you entered Testing Mode.

item.test.save_and_exit=Leave Map $RMB_ITEM
item.test.save_and_exit.lore=Exit your map and return to the lobby. Your\n\
   last location and build progress will be saved.