# Play Map (/play <MapID>)
# 0: The map ID the user is trying to enter a course with
command.play.usage=$INFO<$light_gray>Usage:</$light_gray> <$white>/play <Map ID></$white>
command.play.invalid_ID=$DENY<$light_gray>The Map ID <$white><0> doesn't exist</$white>!</$light_gray>
command.play.wrong_format=$DENY<$light_gray>The Map ID <$white><0> isn't valid</$white>!</$light_gray>
# Legacy Maps
command.map.legacy.import.usage=$INFO<$light_gray>Usage:</$light_gray> <$white>/map legacy import <Legacy Map ID></$white>
# 0: Legacy map ID
command.map.legacy.import.invalid_id=$DENY<$light_gray>The Legacy Map ID <$white><0> doesn't exist</$white>!</$light_gray>
command.map.legacy.import.not_owner=$DENY<$light_gray>You cannot import a Legacy Map if you <$white>aren't its Owner</$white>!</$light_gray>
# 0: Legacy map name
# 1: Slot number
command.map.legacy.import.success=$CONFIRM <$light_gray>You have <$white>successfully imported</$white> your Legacy Map <$white><0></$white> to your Slot <$white><1></$white>.</$light_gray>
command.map.legacy.import.failure=$DENY<$light_gray>An <$white>error occurred</$white> while importing your legacy map! Please contact an <$red>Administrator</$red>!</$light_gray>
command.map.legacy.list.usage=$INFO<$light_gray>Usage:</$light_gray> <$white>/map legacy list</$white>
command.map.legacy.list.no_maps=$INFO<$light_gray>You have <$white>no Legacy Maps</$white> to list!</$light_gray>
# 0: Legacy map ID
command.map.legacy.list.header=<$light_gray>Your Legacy Maps:</$light_gray>
# 0: Legacy map name
# 1: Legacy map ID
command.map.legacy.list.entry=<click:run_command:'/map legacy import <1>'><hover:show_text:'<$lime>Click to Import!</$lime>'><$light_gray> Name: <$white><0></$white> ID: <$white><1></$white><$light_gray></click>
command.map.legacy.list.failure=$DENY<$light_gray>An <$white>error occurred</$white> while listing your legacy maps! Please contact an <$red>Administrator</$red>!</$light_gray>

# Join Command
# 0: Player name
# 1: Map name
command.join.usage=$INFO<$light_gray>Usage: <$white>/join <player></$white> Teleports you to the map someone is in if it is published.</$light_gray>
command.join.only_playing=$DENY<$light_gray> You can only join someone who is in a <$white>published map</$white>!</$light_gray>
command.join.hub=$DENY<$light_gray> You cannot join <$white><0></$white> as they are not in a map!</$light_gray>
command.join.building=\
  <click:run_command:'/request <0>'><hover:show_text:'<$lime>Click here to /request <0>!</$lime>'>$DENY<$light_gray> You cannot join <$white><0></$white> as they are not in a published map!</$light_gray> <$lime>Click here to request to join them!</$lime></click>
command.join.same_map=$DENY<$light_gray> You are already in the <$white>same map</$white> as <$white><0></$white>!</$light_gray>

# Where Command
command.where.usage=$INFO<$light_gray>Usage: <$white>/where <player></$white> Tells you what map someone is in.</$light_gray>
command.where.same_map=$INFO<$light_gray> You are in the <$white>same map</$white> as <$white><0></$white>.</$light_gray>
command.where.hub=$INFO<$light_gray><$white><0></$white> is in the <$white>/hub</$white>.</$light_gray>
command.where.playing=\
  <click:run_command:'/join <0>'><hover:show_text:'<$lime>Click to join!</$lime>'>$INFO<$light_gray><$white><0></$white> is playing on <$white><1></$white>. <$lime>Click here to join them!</$lime></$light_gray></click>
command.where.building=\
  <click:run_command:'/request <0>'><hover:show_text:'<$lime>Click to request!</$lime>'>$INFO<$light_gray><$white><0></$white> is building on a map. <$lime>Click here to request to join them!</$lime></$light_gray></click>
command.where.self.hub=$INFO<$light_gray><$white>You</$white> are in the <$white>/hub</$white>.</$light_gray>
# 0: Map name
command.where.self.playing=$INFO<$light_gray><$white>You</$white> are playing on <$white><0></$white>.</$light_gray>
command.where.self.building=$INFO<$light_gray><$white>You</$white> are building on <$white><0></$white></$light_gray>

# Teleporting
teleport.spawn=$CONFIRM<$light_gray>Warped to the <$white>lobby</$white>.</$light_gray>
teleport.self=$DENY<$light_gray>You can't teleport to <$white>yourself</$white>!</$light_gray>
teleport.not_same_map=$DENY<$light_gray>That player isn't in the <$white>same map</$white> as you!</$light_gray>
teleport.success=CONFIRM<$light_gray>Teleported to <$white><0></$white>.</$light_gray>

# Currency
# 0: Cubits purchase amount
currency.store.success=[?] Your store transaction of <0> Cubits has successfully been processed, enjoy!
# 0: The package purchased
# 1: Cubits purchase amount
currency.cubits.purchase.successful_transaction=[?] You successfully purchased <0> for <1> Cubits.
# 0: Cubits balance
# 1: Amount of missing Cubits need to purchase package
# 2: The package trying to be purchased
currency.cubits.purchase.insufficient_funds=[?] You only have <0> Cubits; you are short <1> Cubits to purchase <2>!
# Creating a Map
# 0: slot number
command.map.create.slot_in_use=[?] <red>Slot <0> is already in use.
# 0: name
command.map.create.name_in_use=[?] <red>Cannot create map named '<0>' because it is already in use.
# 0: slot number, 1: map name
command.map.create.success=$CONFIRM <$light_gray>Created new map in slot <$white><1></$white></$light_gray>. \
  <click:suggest_command:/map edit <0>><$lime>Click to Edit</$lime></click>



# Administrative Commands
command.fly.hub=$INFO<$light_gray>Your <$white>flight</$white> has been toggled <$white><0></$white>.</$light_gray>