gui.create_maps.contest_slot.locked.name=<$white>Item Competition Map Slot</$white>
gui.create_maps.contest_slot.locked.lore=<$light_gray>Work on an entry for our first competition!</$light_gray>\n\
  <$light_gray>Read More Here:<$light_gray> <$light_blue>https://hollowcu.be/map-comp</$light_blue>\n\n\
  <$red>Unlocks In: <0></$red>
