gui.create_maps.contest_slot.locked.name=<$white>Item Competition Map Slot</$white>
gui.create_maps.contest_slot.locked.lore=<$light_gray>Work on an entry for our first competition!</$light_gray>\n\
  <$light_gray>Read More Here:<$light_gray> <$light_blue>https://hollowcu.be/map-comp</$light_blue>\n\n\
  <$red>Unlocks In: <0></$red>

gui.create_maps.contest_slot.create.name=<$white>Item Competition Map Slot</$white>
gui.create_maps.contest_slot.create.lore=<$light_gray>Work on an entry for our first competition!</$light_gray>\n\
  <$light_gray>Read More Here:<$light_gray> <$light_blue>https://hollowcu.be/map-comp</$light_blue>\n\n\
  <$red>Ends In: <0></$red>\n\n\
  $LMB <$white_gray>Click to Create</$white_gray>

gui.create_maps.contest_slot.in_progress.name=<$white>Item Competition Map Slot</$white>
gui.create_maps.contest_slot.in_progress.lore=<$light_gray>Work on an entry for our first competition!</$light_gray>\n\
  <$light_gray>Read More Here:<$light_gray> <$light_blue>https://hollowcu.be/map-comp</$light_blue>\n\n\
  <$red>Ends In: <0></$red>\n\n\
  $LMB <$white_gray>Click to Select</$white_gray>

gui.create_maps.contest_slot.submitted.name=<$white>Item Competition Map Slot</$white>
gui.create_maps.contest_slot.submitted.lore=<$light_gray>You already submitted your entry!</$light_gray>\n\
  <$light_gray>Wait for the competition to be over.</$light_gray>\n\
  <$light_gray>Read More Here:<$light_gray> <$light_blue>https://hollowcu.be/map-comp</$light_blue>\n\n\
  <$red>Ends In: <0></$red>

gui.create_maps.contest_slot.completed.name=<$white>Item Competition Map Slot</$white>
gui.create_maps.contest_slot.completed.lore=<$light_gray>The competition is over and now awaits judging!</$light_gray>\n\
  <$light_gray>Wait for an announcement on the results in our <$light_blue>/discord</$light_blue>.

create_maps.slot.comp.create.info.name=<$white>Item Competition Map Info</$white>
create_maps.slot.comp.create.info.lore=\
  <$light_gray>- The theme is items.</$light_gray>\n\
  <$light_gray>- 1,200 x 1,200 build space.</$light_gray>\n\
  <$light_gray>- Deadline August 10th.</$light_gray>\n\n\
  <$light_gray>Read More Here:<$light_gray> <$light_blue>https://hollowcu.be/map-comp</$light_blue>\n\n\
  $LMB <$white_gray>Click to Get Link</$white_gray>

gui.create_maps.slot.comp.submit.name=<$lime>Submit Map</$lime>
gui.create_maps.slot.comp.submit.lore=\
  <$light_gray>Submit your finalized work for the competition.</$light_gray>\n\
  <$light_gray>Submissions are viewable to the NPC left of spawn.</$light_gray>\n\n\
  $WARNING<$lemon>WARNING</$lemon> $WARNING\n\
  <$light_gray>You cannot edit your map after this!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Submit</$white_gray>

gui.create_maps.slot.comp.submit.confirm=Submit your map to the Competition. This CANNOT be undone!

create_maps.slot.comp.submission.success=$CONFIRM<$light_gray>You have submitted your map to the competition. If you need any future changes to your map, like fixing a skip, you will have to ask a staff member.</$light_gray>

gui.create_maps.slot.comp.map_info_tab.select_type.building.name=<$dark_green>Create Building Showcase</$dark_green>
gui.create_maps.slot.comp.map_info_tab.select_type.building.lore=<$red>You must make a parkour map for this competition!</$red>

gui.create_maps.slot.comp.map_actions_tab.name=<$white>Map Actions</$white>
gui.create_maps.slot.comp.map_actions_tab.lore=<$red>Unavailable for Competition</$red>


gui.create_maps.submit_map.name=<$lime>Submit Map</$lime>
gui.create_maps.submit_map.lore=\
  <$light_gray>Release your map for others to play.</$light_gray>\n\n\
  $WARNING<$lemon>WARNING</$lemon> $WARNING\n\
  <$light_gray>You cannot edit your map after this!</$light_gray>\n\n\
  $LMB <$white_gray>Click to Submit</$white_gray>
gui.create_maps.can't_submit_map.no_name_and_no_display_item.name=<$red>Submit Map</$red>
gui.create_maps.can't_submit_map.no_name_and_no_display_item.lore=\
  <$light_gray>You need to choose a map name</$light_gray>\n\
  <$light_gray>and a display item before you</$light_gray>\n\
  <$light_gray>can submit your work!</$light_gray>
gui.create_maps.can't_submit_map.no_name.name=<$red>Submit Map</$red>
gui.create_maps.can't_submit_map.no_name.lore=\
  <$light_gray>You need to choose a map name</$light_gray>\n\
  <$light_gray>before you can submit your work!</$light_gray>
gui.create_maps.can't_submit_map.no_display_item.name=<$red>Submit Map</$red>
gui.create_maps.can't_submit_map.no_display_item.lore=\
  <$light_gray>You need to choose a display item</$light_gray>\n\
  <$light_gray>before you can submit your work!</$light_gray>
gui.create_maps.can't_submit_map.build_once.name=<$red>Submit Map</$red>
gui.create_maps.can't_submit_map.build_once.lore=\
  <$light_gray>You need to build more in your</$light_gray>\n\
  <$light_gray>map before you can submit it!</$light_gray>
gui.create_maps.can't_submit_map.play_longer.name=<$red>Submit Map</$red>
gui.create_maps.can't_submit_map.play_longer.lore=\
  <$light_gray>You need to spend at least 5</$light_gray>\n\
  <$light_gray>minutes building in your map!</$light_gray>
gui.create_maps.can't_submit_map.missing_finish_plate.name=<$red>Submit Map</$red>
gui.create_maps.can't_submit_map.missing_finish_plate.lore=\
  <$light_gray>You must place a finish plate</$light_gray>\n\
  <$light_gray>to verify your map!</$light_gray>
gui.create_maps.can't_submit_map.bad_status_plate.name=<$red>Submit Map</$red>
gui.create_maps.can't_submit_map.bad_status_plate.lore=\
  <$light_gray>Only parkour maps can have checkpoints</$light_gray>\n\
  <$light_gray>and finish plates! Either change your</$light_gray>\n\
  <$light_gray>map type to parkour or remove them.</$light_gray>

gui.competition.items.submissions.info_hover.name=<$white>Competition Rules and Information</$white>
gui.competition.items.submissions.info_hover.lore=\
  <$light_blue>https://hollowcu.be/map-comp</$light_blue>\n\n\
  $LMB <$white_gray>Click to Get Link</$white_gray>

chat.competition.link=$INFO<click:open_url:'https://hollowcu.be/map-comp'><$lime>Click here to view the full competition details!</$lime></click>
