# Map Status Updates
play.checkpoint.reached=$INFO<$light_gray>You have reached a new <$white>Checkpoint</$white>.</$light_gray>
# 0: Completion time
# 1: Difference of your completion time compared to your best time
map.completed.first=$CONFIRM <$light_gray>Map <$white>completed</$white> in</$light_gray> <0><$light_gray>!</$light_gray>
map.completed.with_prior=$CONFIRM <$light_gray>Map <$white>completed</$white> in</$light_gray> <0><$light_gray>! (</$light_gray><1><$light_gray>)</$light_gray>
# 0: Map name
# 1: Savestate time
map.status.finish=$INFO <$light_gray>You <$white>finished</$white> the map <$white><0></$white> in <$light_blue><1></$light_blue>.</$light_gray>
map.status.reset_confirmation=$WARNING <$light_gray>Are you sure you want to <$white>restart</$white> this map? Right-click again within 2 seconds to confirm.</$light_gray>
map.status.reset.timed_out=$INFO <$light_gray>Reset confirmation timed out.</$light_gray>
map.status.reported=$CONFIRM <$light_gray>You successfully <$white>reported</$white> the map <$white><0></$white>!</$light_gray>
map.spectator_mode.solid_ground=$DENY <$light_gray>You must be on the <$white>ground</$white> to enter Spectator Mode!</$light_gray>
# 0: Boosts amount
# 1: Map name
map.status.boosted=$CONFIRM <$light_gray>You gave <$white><0> Boosts</$white> to the map <$white><1></$white>!</$light_gray>
play_maps.loading=$WARNING <$light_gray>We are <$white>still loading</$white> the world data! <$white>Please wait</$white> a few seconds.<$light_gray>