punishment.help.header.1=<$white>Minor Chat Infractions:</$white>
punishment.help.header.2=<$white_gray>Toxicity, Spamming, Inappropriate Topics</$white_gray>
punishment.help.header.3=<$white>Major Chat Infractions:</$white>
punishment.help.header.4=<$white_gray>Discrimination, Harassment, Advertising, Filter Bypass</$white_gray>
punishment.help.header.5=<$white>Minor Gameplay Infractions:</$white>
punishment.help.header.6=<$white_gray>Stats-Boosting, Macros</$white_gray>
punishment.help.header.7=<$white>Major Gameplay Infractions:</$white>
punishment.help.header.8=<$white_gray>Cheats, Exploits, Bug-Abuse, Ban Evasion</$white_gray>
punishment.help.header.9=<$white>Severe Gameplay Infractions:</$white>
punishment.help.header.10=<$white_gray>Bad Skin and/or Name (Appealable), Doxing, DDosing, Illegal Content</$white_gray>
punishment.help.empty=

punishment.help.ladder.name=<$white><0> // <1></$white>
punishment.help.ladder.separator=<$white_gray> -> </$white_gray>
punishment.help.ladder.entry=<$white_gray><0></$white_gray>
punishment.help.ladder.entries=<$white_gray><0></$white_gray>

punishment.status.header=$INFO<$white_gray>Status for</$white_gray> <0>
punishment.status.ban.entry=<$white_gray>Banned: <0></$white_gray>
punishment.status.mute.entry=<$white_gray>Muted: <0></$white_gray>
# 0=executor, 1=type, 2=comment, 3=relative time of ban, 4=relative time of expiry (or permanent)
punishment.status.entry=<$white_gray>By <0> for <hover:show_text:'<2>'><1></hover> <3> ago (<4>)</$white_gray>
punishment.status.duration.relative=<$white_gray>Expires in <0></$white_gray>
punishment.status.duration.permanent=<$red>Permanent<$red>
punishment.status.none=<$lime>No</$lime>

punishment.history.none=$DENY<$light_gray>No Punishments Found!</$light_gray>
punishment.history.header=$INFO<$white_gray>History for <0> (<1> total)</$white_gray>

punishment.muted=$DENY<$light_gray>You cannot talk as you are muted!</$light_gray>
punishment.banned=$DENY<$light_gray>>You are banned from this server!</$light_gray>

# Same for all below, can add more (@seth)
# 0=player, 1=executor, 2=ladder id
punishment.staff_announce.ban.created=$INFO<$white_gray><0> has been banned by <1> for <2>!</$white_gray>
punishment.staff_announce.mute.created=$INFO<$white_gray><0> has been muted by <1> for <2>!</$white_gray>
punishment.staff_announce.kick.created=$INFO<$white_gray><0> has been kicked by <1> for <2>!</$white_gray>
punishment.staff_announce.ban.revoked=$INFO<$white_gray><0> has been unbanned by <1> for <2>!</$white_gray>
punishment.staff_announce.mute.revoked=$INFO<$white_gray><0> has been unmuted by <1> for <2>!</$white_gray>
