punishment.help.header=Blah blah explain whats below in a SHORT description (@seth)
punishment.help.ladder.name=<0> // <1>
punishment.help.ladder.separator=->
punishment.help.ladder.entry=<0>
punishment.help.ladder.entries=<0>

punishment.status.header=Status for <0>
punishment.status.ban.entry=Banned: <0>
punishment.status.mute.entry=Muted: <0>
# 0=executor, 1=type, 2=comment, 3=relative time of ban, 4=relative time of expiry (or permanent)
punishment.status.entry=By <0> for <hover:show_text:'<2>'><1></hover> <3> ago (<4>)
punishment.status.duration.relative=expires in <0>
punishment.status.duration.permanent=permanent
punishment.status.none=<$lime>No</$lime>

punishment.history.none=No punishments found
punishment.history.header=History for <0> (<1> total)

punishment.muted=$DENY<$red>You cannot talk as you are muted!
punishment.banned=$DENY<$red>You are banned from this server!
