command.rules.full=\
  <$light_red>Minor Chat Infractions:</$light_red>\n\
  <$white>Toxicity:</$white> <$light_gray>Being disrespectful to, arguing with, or inciting drama with other players.</$light_gray>\n\
  <$white>Spamming:</$white> <$light_gray>Repeating similar messages or sending messages containing repeated characters.</$light_gray>\n\
  <$white>Inappropriate Topics:</$white> <$light_gray>Discussion of mature content that isn't appropriate for younger audiences. This includes things that are suggestive in nature.</$light_gray>\n\n\
  <$red>Major Chat Infractions:</$red>\n\
  <$white>Discrimination:</$white> <$light_gray>Content that is discriminatory against a specific group of players.</$light_gray>\n\
  <$white>Harassment:</$white> <$light_gray>Bullying, personal attacks, threats, or any behavior intended to intimidate, harm, or distress another player.</$light_gray>\n\
  <$white>Advertising:</$white> <$light_gray>Intentionally advertising servers or media unrelated to Hollow Cube.</$light_gray>\n\
  <$white>Filter Bypass:</$white> <$light_gray>Bypassing the filter by changing characters to send a message that is meant to be filtered out.</$light_gray>\n\n\
  <$light_red>Minor Gameplay Infractions:</$light_red>\n\
  <$white>Stat-Boosting:</$white> <$light_gray>Using multiple accounts, other players, or unique glitches to boost the statistics of a player in an unintended way.</$light_gray>\n\
  <$white>Inappropriate Gameplay:</$white> <$light_gray>Display of mature content that isn't appropriate for younger audiences. This includes things that are suggestive in nature.</$light_gray>\n\
  <$white>Macros:</$white> <$light_gray>Automated sequences of inputs or actions that give an unfair gameplay advantage.</$light_gray>\n\n\
  <$red>Major Gameplay Infractions:</$red>\n\
  <$white>Cheats:</$white> <$light_gray>Using any client modifications/settings that are not original Minecraft features and give an unfair gameplay advantage.</$light_gray>\n\
  <$white>Exploits/Bug-Abuse:</$white> <$light_gray>Purposely using a bug or flaw to gain advantage/hinder the experience of others.</$light_gray>\n\
  <$white>Punishment Evasion:</$white> <$light_gray>Evading an already existing punishment by going on a different account to bypass it.</$light_gray>\n\n\
  <$dark_red>Severe Gameplay Infraction:</$dark_red>\n\
  <$white>Doxing:</$white> <$light_gray>Releasing someone's private info, or threatening to.</$light_gray>\n\
  <$white>DDoSing:</$white> <$light_gray>DDoSing the server or a player, or threatening to.</$light_gray>\n\
  <$white>Illegal Content:</$white> <$light_gray>Any content that is illegal in nature and breaks the law.</$light_gray>\n\n\
  <$white>Name/Skin Infraction (Perm Until Appeal):</$white> <$light_gray>Any skin or username that may be offensive towards other players or display inappropriate content.</$light_gray>\n\n\
  <$red>Map Infractions:</$red>\n\
  <$white>Cheated Verification:</$white> <$light_gray>This map was verified using hacks or exploits.</$light_gray>\n\
  <$white>Discrimination:</$white> <$light_gray>The content in this map is discriminatory against a specific group of players.</$light_gray>\n\
  <$white>Inappropriate/Explicit Content:</$white> <$light_gray>This map depicts mature content that isn't appropriate for younger audiences. This includes things that are suggestive in nature.</$light_gray>\n\
  <$white>Spam:</$white> <$light_gray>This map is low quality and designed to waste time.</$light_gray>\n\
  <$white>Stolen Content:</$white> <$light_gray>Content in this map is not the original world of its publisher.</$light_gray>
# THE ABOVE IS REALLY BAD AND GARBAGE LMAO I need to update this to something else but I already wrote it so I'm just going to keep it here

command.rules=\
  <$white_gray>Below are a list of things we do not allow on our server. Thank you for helping us maintain a fair and friendly environment for everyone!</$white_gray>\n\n\
  <$white>Minor Chat Infractions:</$white>\n\
  <$light_gray>Toxicity, Spamming, Inappropriate Topics</$light_gray>\n\n\
  <$white>Major Chat Infractions:</$white>\n\
  <$light_gray>Harassment, Advertising, Filter Bypass</$light_gray>\n\n\
  <$white>Minor Gameplay Infractions:</$white>\n\
  <$light_gray>Stat-Boosting, Inappropriate Gameplay, Macros</$light_gray>\n\n\
  <$white>Major Gameplay Infractions:</$white>\n\
  <$light_gray>Cheats, Exploits/Bug-Abuse, Punishment Evasion</$light_gray>\n\n\
  <$white>Severe Gameplay Infractions:</$white>\n\
  <$light_gray>Doxing, DDoSing, Illegal Content, Name/Skin Infraction (Perm Until Appeal)</$light_gray>\n\n\
  <$white>Map Infractions:</$white>\n\
  <$light_gray>Cheated Verification, Discrimination, Inappropriate/Explicit Content, Spam, Stolen Content</$light_gray>\n\n\
  <$white_gray>For a full explanation of each infraction, visit <$azure>https://hollowcube.net/rules</$azure>.<$white_gray>