#
# Friends
#

# /friend add
# when someone sends a friend request, then the other sends it and they become friends automatically, there is no positive response sent back to the original person to indicate that they are now friends
command.friend.add.self=$DENY<$light_gray>You can't friend <$white>yourself</$white>!</$light_gray>
# 0: Target Username
command.friend.add.request_sent=$CONFIRM<$light_gray>You sent <$white><0></$white> a <$white>friend request</$white>!</$light_gray>
# added is when they were added as a friend
# idk did I write the below one correctly lol?
command.friend.add.added=$INFO<$light_gray>You are now friends with <$white><0></$white>!</$light_gray>
command.friend.add.already_friends=$DENY<$light_gray>You are <$white>already friends</$white> with <$white><0></$white>!</$light_gray>
command.friend.add.blocked_by_self=$DENY<$light_gray>You <$white>cannot</$white> send <$white><0></$white> a <$white>friend request</$white> as you have them <$white>blocked</$white>!</$light_gray>
#command.friend.add.blocked_by_target=Will go unused for now. Prob better to be arbitrary and just use the auto rejected message when someone is blocked
command.friend.add.already_requested=$DENY<$light_gray>You already have a <$white>pending friend request</$white> to <$white><0></$white>!</$light_gray>
command.friend.add.auto_rejected=$DENY<$light_gray>You cannot send friend requests to this player!</$light_gray>
# 0: Friend Limit (15 or 1000)
# 1: Sender's Current Friends Count / get rid of this and # 2 we don't really need to say them, surely?
# 2: Sender's Current Outgoing Friend Requests
command.friend.add.limit_reached.non_hypercube=$DENY<$light_gray>We <$white>couldn't send</$white> your <$white>friend request</$white> as you've reached the <$white>friend limit</$white> of <$white><0></$white>!</$light_gray>
command.friend.add.limit_reached.hypercube=$DENY<$light_gray>We <$white>couldn't send</$white> your <$white>friend request</$white> as you've reached the <$white>friend limit</$white> of <$white><0></$white>!</$light_gray>
# 0: Target display name
# TODO this can be removed in the future once the feature is enabled for everyone (and flag is removed)
command.friend.add.feature_disabled_target=$DENY<$light_gray><$white>Friend requests</$white> are currently <$white>limited to $HYPERCUBE <$gold>Hypercube</$gold></$white> members only!

# /friend remove
command.friend.remove.self=$DENY<$light_gray>You can't friend <$white>yourself</$white>!</$light_gray>
# 0: Target Username
command.friend.remove.success=$CONFIRM<$light_gray>You <$white>removed <0></$white> from your <$white>friends</$white> list!</$light_gray>
command.friend.remove.not_friends=$DENY<$light_gray>You are not friends with <0>!

# /friend request list <incoming/outgoing>
command.friend.request.list.empty.incoming=$INFO<$light_gray>You don't have any <$white>incoming friend requests</$white>!</$light_gray>
command.friend.request.list.empty.outgoing=$INFO<$light_gray>You don't have any <$white>outgoing friend requests</$white>!</$light_gray>
# 0: Page Number
# 1: Max Page Number/Page Count
command.friend.request.list.header.incoming=<$lemon>Incoming Friend Requests</$lemon> <$dark_gray>[<$light_gray><0></$light_gray>/<$light_gray><1></$light_gray>]</$dark_gray>
command.friend.request.list.header.outgoing=<$lemon>Outgoing Friend Requests</$lemon> <$dark_gray>[<$light_gray><0></$light_gray>/<$light_gray><1></$light_gray>]</$dark_gray>
# 0: Friend Username / should add timestamp maybe?
# 1: Plain Username
command.friend.request.list.line.incoming=<$dark_gray> » </$dark_gray><$white><0></$white> <hover:show_text:'<$lime>Click to accept this friend request!'><click:run_command:'/friend add <1>'><$dark_gray> [ </$dark_gray><$lime>✔</$lime></click></hover> <$dark_gray>|</$dark_gray> <hover:show_text:'<$red>Click to deny this friend request!'><click:run_command:'/friend request remove <1>'><$red>❌</$red><$dark_gray> ]</$dark_gray></click></hover>
command.friend.request.list.line.outgoing=<$dark_gray> » </$dark_gray><$white><0></$white> <click:run_command:'/friend request remove <1>'><hover:show_text:'<$red>Click to cancel your friend request!'><$dark_gray>[</$dark_gray> <$red>❌</$red> <$dark_gray>]</$dark_gray></hover></click>

# /friend request remove - player removes a request bidirectionally (so either they sent, or they received)
command.friend.request.remove.self=$DENY<$light_gray>You can't send or remove friend requests to <$white>yourself</$white>!</$light_gray>
# 0: Target Username
command.friend.request.remove.success=$CONFIRM<$light_gray>You <$white>removed</$white> that <$white>friend request</$white>!</$light_gray>
# above is actually a garbage TL key lol, should be replaced with the 2 below
command.friend.request.incoming.remove.success=$CONFIRM<$light_gray>You <$white>denied <0>'s friend request</$white>!</$light_gray>
command.friend.request.outgoing.remove.success=$CONFIRM<$light_gray>You <$white>canceled</$white> your <$white>friend request</$white> to <$white><0></$white>!</$light_gray>
command.friend.request.remove.not_requested=$DENY<$light_gray>You have <$white>no friend request</$white> to or from <$white><0></$white>!</$light_gray>

# /friend list
command.friend.list.empty=$INFO<$light_gray>You <$white>don't have</$white> any <$white>friends</$white> yet! Use <$white>/friend add <player></$white> to send a friend request.</$light_gray>
# 0: Page Number
# 1: Max Page Number/Page Count
# TODO add remaining friend slots
command.friend.list.header=<$lemon>Friends List</$lemon> <$dark_gray>[<$light_gray><0></$light_gray>/<$light_gray><1></$light_gray>]</$dark_gray>
# 0: Friend Username
command.friend.list.line.hub=<$lime> » </$lime><$light_gray><$white><0></$white> is in the <$white>/hub</$white>.</$light_gray>
# 0: Friend Username
# 1: Plain Username
# 2: Map Name (not used rn)
command.friend.list.line.building=<click:run_command:'request <1>'><hover:show_text:'<$lime>Click to request to join!'><$lime> » </$lime><$light_gray><$white><0></$white> is building on <$white><2></$white>.</$light_gray></hover></click>
# 0: Friend Username
# 1: Map Name (not used rn)
command.friend.list.line.verifying=<$lime> » </$lime><$white><0></$white> is verifying their map, <$white><1></$white>.</$light_gray>
# 0: Friend Username
# 1: Plain Username
# 2: Map Name
command.friend.list.line.playing=<click:run_command:'join <1>'><hover:show_text:'<$lime>Click to join!'><$lime> » </$lime><$light_gray><$white><0></$white> is playing on <$white><2></$white>.</$light_gray></hover></click>
# 0: Friend Username
command.friend.list.line.online_unknown=<$lime> » </$lime><$white><0></$white> <$light_gray>is <$white_gray>currently online</$white_gray>.</$light_gray>
# 0: Friend Username
command.friend.list.line.offline=<$dark_gray> » </$dark_gray><$white><0></$white><$light_gray> is currently offline.</$light_gray>

#
# Blocked
#

# /block
command.block.self=$DENY<$light_gray>You can't block <$white>yourself</$white>!</$light_gray>
# 0: Player Name
command.block.success=$CONFIRM<$light_gray>You <$white>blocked <0></$white>! You will <$white>not see</$white> their <$white>private messages</$white> anymore.</$light_gray>
command.block.already_blocked=$INFO<$light_gray>You <$white>already blocked</$white> <0>!</$light_gray>
command.block.cannot_target_staff=$DENY<$light_gray>You <$white>can't block staff members</$white>! If they are abusing this, please contact an <$red>Administrator</$red>.</$light_gray>

# /block list
command.block.list.empty=$INFO<$light_gray>You <$white>don't have</$white> any <$white>blocked players</$white>! Use <$white>/block <player></$white> to block a player.</$light_gray>
# 0: Page Number
# 1: Page Count
command.block.list.header=<$light_red>Blocked Players</$light_red> <$dark_gray>[<$light_gray><0></$light_gray>/<$light_gray><1></$light_gray>]</$dark_gray>
# 0: Player Display Name
# 1: Player Name
#command.block.list.line=<$dark_gray>» <click:run_command:'/unblock <0>'><hover:show_text:'<$lime>Click to unblock this player!'><$white><0></$white></hover></click> Seth's old message, could be removed
command.block.list.line=<click:run_command:'/unblock <0>'><hover:show_text:'<$lime>Click to unblock this player!'><$dark_gray> » </$dark_gray><$white><0></$white><$dark_gray> [ <$red>❌</$red> ]</$dark_gray></hover></click>
# <$dark_gray>»</$dark_gray> <$light_gray><hover:show_text:'<$lime>Click to unblock this player.</$lime>'><click:run_command:/unblock <0>'<white><0></$white>'</click></hover></$light_gray>
# /unblock
command.unblock.self=$DENY<$light_gray>You can't block <$white>yourself</$white>!</$light_gray>
command.unblock.success=$CONFIRM<$light_gray>You <$white>unblocked <0></$white>! You will <$white>see</$white> their <$white>private messages</$white> again.</$light_gray>
command.unblock.not_blocked=$INFO<$light_gray>You <$white>don't</$white> have <$white><0> blocked</$white>!</$light_gray>

#
# Parties (Coming Later)
#