#
# Spawn Point
#

#
# Customized Leaderboard
#

gui.spawn.customized_leaderboard.title.name=<$white>Customized Leaderboard</$white>
gui.spawn.customized_leaderboard.title.lore=\
  <$light_gray>How completions and rankings are</$light_gray>\n\
  <$light_gray>determined on your map.</$light_gray>\n\n\
$LMB <$white_gray>Click to Edit</$white_gray>

gui.spawn.customized_leaderboard.information.name=<$yellow>Information</$yellow>
gui.spawn.customized_leaderboard.information.lore=\
  <$light_gray>Blah blah TODO</$light_gray>

# Format Switch
gui.spawn.customized_leaderboard.format.playtime.name=<$white>Time</$white>
gui.spawn.customized_leaderboard.format.playtime.lore=\
  <$light_gray>Displays scores as a formatted time,</$light_gray>\n\
  <$light_gray>like 01:23.456. This is the default.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.spawn.customized_leaderboard.format.number.name=<$white>Number</$white>
gui.spawn.customized_leaderboard.format.number.lore=\
  <$light_gray>Displays scores as a raw numeric</$light_gray>\n\
  <$light_gray>value, like 1000 or 99.99.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.spawn.customized_leaderboard.format.percent.name=<$white>Percent</$white>
gui.spawn.customized_leaderboard.format.percent.lore=\
  <$light_gray>Displays scores as a percentage.</$light_gray>\n\
  <$light_gray>Valid between 0 and 100.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

# Order Switch
gui.spawn.customized_leaderboard.order.asc.name=<$white>Ascending</$white>
gui.spawn.customized_leaderboard.order.asc.lore=\
  <$light_gray>Lowest scores are ranked at the top.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Toggle</$white_gray>

gui.spawn.customized_leaderboard.order.desc.name=<$white>Descending</$white>
gui.spawn.customized_leaderboard.order.desc.lore=\
  <$light_gray>Highest scores are ranked at the top.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Toggle</$white_gray>
  
# Score Expression
gui.spawn.customized_leaderboard.score.expression.name=<$white>Score Expression</$white>
gui.spawn.customized_leaderboard.score.expression.lore=MATT!!!

# Reset Button
gui.spawn.customized_leaderboard.action.reset.name=<$white>Reset to Default</$white>
gui.spawn.customized_leaderboard.action.reset.lore=\
  <$light_gray>Restores the leaderboard configuration</$light_gray>\n\
  <$light_gray>back to its default state.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Reset</$white_gray>