#
# Spawn Point
#

#
# Customized Leaderboard
#
gui.spawn.customized_leaderboard.title.name=<$white>Customize Leaderboard</$white>
gui.spawn.customized_leaderboard.title.lore=\
  <$light_gray>Control how the leaderboard ranking</$light_gray>\n\
  <$light_gray>is determined on your map.</$light_gray>\n\n\
$LMB <$white_gray>Click to Edit</$white_gray>

gui.spawn.customized_leaderboard.information.name=<$yellow>Information</$yellow>
# TODO: probably can write something better here
gui.spawn.customized_leaderboard.information.lore=\
  <$light_gray>Control how the leaderboard ranking</$light_gray>\n\
  <$light_gray>is determined on your map.</$light_gray>

# Format Switch
gui.spawn.customized_leaderboard.format.playtime.name=<$white>Time</$white>
gui.spawn.customized_leaderboard.format.playtime.lore=\
  <$light_gray>Displays scores as a formatted time.</$light_gray>\n\
  <$light_gray>The input number is in ticks.</$light_gray>\n\n\
  <$light_gray>Example: <$white>01:23.456</$white></$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.spawn.customized_leaderboard.format.number.name=<$white>Number</$white>
gui.spawn.customized_leaderboard.format.number.lore=\
  <$light_gray>Displays scores as a scaled number.</$light_gray>\n\n\
  <$light_gray>Examples: <$white>0.253</$white>, <$white>1,000</$white>, <$white>10.2k</$white>, <$white>1.5m</$white></$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.spawn.customized_leaderboard.format.percent.name=<$white>Percent</$white>
gui.spawn.customized_leaderboard.format.percent.lore=\
  <$light_gray>Displays scores as a percentage.</$light_gray>\n\
  <$light_gray>Clamped to the range of 0 - 100.</$light_gray>\n\n\
  <$light_gray>Examples: <$white>1.5%</$white>, <$white>100%</$white></$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

# Order Switch
gui.spawn.customized_leaderboard.order.asc.name=<$white>Ascending</$white>
gui.spawn.customized_leaderboard.order.asc.lore=\
  <$light_gray>Lower scores are better.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Toggle</$white_gray>

gui.spawn.customized_leaderboard.order.desc.name=<$white>Descending</$white>
gui.spawn.customized_leaderboard.order.desc.lore=\
  <$light_gray>Higher scores are better.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Toggle</$white_gray>
  
# Score Expression
gui.spawn.customized_leaderboard.score.expression.name=<$white>Score Expression</$white>
gui.spawn.customized_leaderboard.score.expression.lore=\
  <$light_gray>A valid Molang expression that evaluates to a number.</$light_gray>\n\
  <$light_gray>You can use variables set by actions or query functions.</$light_gray>\n\n\
  <$light_gray>For simple operations you can</$light_gray>\n\
  <$light_gray>put a number or do 'variable.name + 1'</$light_gray>
gui.spawn.customized_leaderboard.score.expression.input=<$white>Score Expression</$white>

# Reset Button
gui.spawn.customized_leaderboard.action.reset.name=<$white>Reset to Default</$white>
gui.spawn.customized_leaderboard.action.reset.lore=\
  <$light_gray>Restores the leaderboard configuration</$light_gray>\n\
  <$light_gray>back to its default state.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Reset</$white_gray>
