#
# Spawn Point
#

#
# Customized Leaderboard
#

gui.spawn.customized_leaderboard.title.name=<$white>Customized Leaderboard</$white>
gui.spawn.customized_leaderboard.title.lore=$LMB <$white_gray>Click to Edit</$white_gray>
## Could use an actual description but idk what to write that's not yapping

# Format Switch
gui.spawn.customized_leaderboard.format.playtime.name=<$white>Time</$white>
gui.spawn.customized_leaderboard.format.playtime.lore=\
  <$dark_gray>[</$dark_gray><$lime>Time</$lime><$dark_gray>/</$dark_gray><$light_gray>Number</$light_gray><$dark_gray>/</$dark_gray><$light_gray>Percent</$light_gray><$dark_gray>]</$dark_gray>\n\n\
  <$light_gray>Displays scores as a formatted time.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.spawn.customized_leaderboard.format.number.name=<$white>Number</$white>
gui.spawn.customized_leaderboard.format.number.lore=\
  <$dark_gray>[</$dark_gray><$light_gray>Time</$light_gray><$dark_gray>/</$dark_gray><$lime>Number</$lime><$dark_gray>/</$dark_gray><$light_gray>Percent</$light_gray><$dark_gray>]</$dark_gray>\n\n\
  <$light_gray>Displays scores as a raw numeric value.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

gui.spawn.customized_leaderboard.format.percent.name=<$white>Percent</$white>
gui.spawn.customized_leaderboard.format.percent.lore=\
  <$dark_gray>[</$dark_gray><$light_gray>Time</$light_gray><$dark_gray>/</$dark_gray><$light_gray>Number</$light_gray><$dark_gray>/</$dark_gray><$lime>Percent</$lime><$dark_gray>]</$dark_gray>\n\n\
  <$light_gray>Displays scores as a percentage.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Cycle</$white_gray>

# Order Switch (TODO figure out if use the above click to cycle that shows all the options or just do the below simpler one like click to switch to X)
gui.spawn.customized_leaderboard.order.asc.name=<$white>Ascending</$white>
gui.spawn.customized_leaderboard.order.asc.lore=\
  <$light_gray>Lowest scores are ranked at the top.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Switch to Descending</$white_gray>

gui.spawn.customized_leaderboard.order.desc.name=<$white>Descending</$white>
gui.spawn.customized_leaderboard.order.desc.lore=\
  <$light_gray>Highest scores are ranked at the top.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Switch to Ascending</$white_gray>
  
# Score Expression
gui.spawn.customized_leaderboard.score.expression.name=<$white>Score Expression</$white>
gui.spawn.customized_leaderboard.score.expression.lore=MATT!!!

# Reset Button
gui.spawn.customized_leaderboard.action.reset.name=<$white>Reset to Default</$white>
gui.spawn.customized_leaderboard.action.reset.lore=\
  <$light_gray>Restores the leaderboard configuration</$light_gray>\n\
  <$light_gray>back to its default state.</$light_gray>\n\n\
  $LMB <$white_gray>Click to Reset</$white_gray>