store.confirmation.cubits=Thank you for purchasing [cubit icon]<0>!
store.confirmation.hypercube=Thank you for purchasing <0> months of Hypercube!
store.confirmation.vote=Thank you for voting on <0>! You received <1>.

quantity.coins=[coins icon]<0>
quantity.cubits=[cubits icon]<0>
