# 0: cubits (using quantity.cubits key)
store.confirmation.cubits=Thank you for purchasing <0>!
# 0: months (int)
store.confirmation.hypercube=Thank you for purchasing <0> months of Hypercube!
# 0: website name
# 1: reward (as a quantity.* key)
store.confirmation.vote=Thank you for voting on <0>! You received <1>.

quantity.coins=$COINS<$gold><0></$gold>
quantity.cubits=$CUBITS<$light_pink><0></$light_pink>

icon.coins=$COINS
icon.cubits=$CUBITS

merchant.trade.buy=$LMB <$white_gray>Click to Buy</$white_gray>
merchant.trade.cannot_afford=<$red>You cannot afford this item.</$red>
