# 0: cubits (using quantity.cubits key)
store.confirmation.cubits=$INFO<$light_gray>Thank you for purchasing <$pink><0></$pink>!</$light_gray>
# 0: months (int)
store.confirmation.hypercube=$INFO<$light_gray>Thank you for purchasing <$white><0></$white> months of <$gold>Hypercube</$gold>!</$light_gray>
# 0: website name
# 1: reward (as a quantity.* key)
store.confirmation.vote=Thank you for voting on <0>! You received <1>.
currency.missing=$DENY<$light_gray>You don't have enough <$pink>Cubits</$pink> to buy this! Get more from our <$white>/store</$white>.</$light_gray>
store.checkout.open_in_browser=$LMB <$white_gray>Click to checkout</$white_gray>\n\n\
  <$light_gray><i>The checkout page will open in your browser.</i></$light_gray>.
item.mapmaker.store.name=<$lime>Store</$lime> $RMB_ITEM
item.mapmaker.store.lore=\
  <$light_gray>Support our development via cosmetics and extra features!</$light_gray>

quantity.coins=$COINS<$gold><0></$gold>
quantity.cubits=$CUBITS<$light_pink><0></$light_pink>

icon.coins=$COINS
icon.cubits=$CUBITS

merchant.trade.buy=$LMB <$white_gray>Click to Buy</$white_gray>
merchant.trade.cannot_afford=<$red>You cannot afford this item.</$red>

merchant.trade.success=<$light_gray>You bought <0></$light_gray>.

#0: when you subscribed, 1: time remaining
command.hypercube.subscription_info=$INFO<$light_gray>You bought <$gold>Hypercube</$gold> on <$white><0></$white> and expires on <$white><1></$white>.</$light_gray>
