#
# COMMANDS
#

# Generic
terraform.generic.no_selection=$DENY<$light_gray>You need to have a <$white>selection</$white> to use this command!</$light_gray>
terraform.generic.empty_clipbord=$DENY<$light_gray>Your clipboard is empty!</$light_gray>
# Positions
terraform.pos1.already_set=$INFO<$light_gray>Position 1 is <$white>already set</$white> here!</$light_gray>
terraform.pos2.already_set=$INFO<$light_gray>Position 2 is <$white>already set</$white> here!</$light_gray>
terraform.warn.border_exceeded=$DENY<$light_gray>You cannot build outside the <$white>world border</$white>!</$light_gray>
# Tools
tool.create=$CONFIRM<$light_gray><$white><0></$white> tool created.</$light_gray>

# Set
terraform.selection.set=$CONFIRM<$light_gray>Finished setting <$white><0></$white> blocks.</$light_gray>
terraform.selection.stack=$CONFIRM<$light_gray>Finished setting <$white><0></$white> blocks.</$light_gray>
terraform.selection.smear=$CONFIRM<$light_gray>Finished setting <$white><0></$white> blocks.</$light_gray>
# Replace
terraform.selection.replace=$CONFIRM<$light_gray>Finished replacing <$white><0></$white> blocks.</$light_gray>
# Copy
terraform.copy=$CONFIRM<$light_gray>Copied <$white><0></$white> blocks to your clipboard.</$light_gray>
# Cut
terraform.cut=$CONFIRM<$light_gray>Cut <$white><0></$white> blocks to your clipboard.</$light_gray>
# Clipboard
terraform.clipboard.clear=$CONFIRM<$light_gray>Your clipboard has been <$white>cleared</$white>.</$light_gray>
terraform.clipboard.list=$INFO<$light_gray>Current Clipboard:</$light_gray> <$white><0></$white>
terraform.clipboard.list.none=$INFO<$light_gray>You have <$white>nothing</$white> in your clipboard.</$light_gray>

#
# SELECTION TYPES
#
terraform.cuboid.explain.primary=$INFO<$light_gray>First position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.cuboid.explain.secondary=$INFO<$light_gray>Second position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.line.explain.primary=$INFO<$light_gray>First position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.line.explain.secondary=$INFO<$light_gray>Second position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.bezier.explain.primary=$INFO<$light_gray>First position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.bezier.explain.secondary=$INFO<$light_gray>Second position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.sel.type.set=$INFO<$light_gray>Your selection type was set to <$white><0></$white>.</$light_gray>
terraform.sel.clear=$CONFIRM<$light_gray>Your selection has been <$white>cleared</$white>.</$light_gray>

#
# HISTORY
#
terraform.history.cleared=$CONFIRM<$light_gray>Your history has been <$white>cleared</$white>.</$light_gray>
terraform.history.undo=$CONFIRM<$light_gray>Undid <$white><0></$white> change(s).</$light_gray>
terraform.history.redo=$CONFIRM<$light_gray>Redid <$white><0></$white> change(s).</$light_gray>