terraform.generic.set=$CONFIRM<$light_gray>Finished setting <$white><0></$white> blocks.</$light_gray>
terraform.generic.no_selection=$DENY<$light_gray>You need to have a <$white>selection</$white> to use this command!</$light_gray>
terraform.generic.no_clipboard=$DENY<$light_gray>Your clipboard is empty!</$light_gray>
terraform.selection.not_cuboid=$DENY<$light_gray>You need to have a <$white>cuboid</$white> selection to use this command!</$light_gray>

terraform.history.undo=$CONFIRM<$light_gray>Undid <$white><0></$white> change(s).</$light_gray>
terraform.history.redo=$CONFIRM<$light_gray>Redid <$white><0></$white> change(s).</$light_gray>
terraform.history.cleared=$CONFIRM<$light_gray>Your history has been <$white>cleared</$white>.</$light_gray>

terraform.clipboard.clear=$CONFIRM<$light_gray>Your clipboard has been <$white>cleared</$white>.</$light_gray>
terraform.clipboard.flip=$CONFIRM<$light_gray>Your clipboard has been <$white>flipped</$white></$light_gray>
terraform.clipboard.rotate=$CONFIRM<$light_gray>Your clipboard has been rotated.</$light_gray>
terraform.copy=$CONFIRM<$light_gray>Copied <$white><0></$white> blocks to your clipboard.</$light_gray>
terraform.cut=$CONFIRM<$light_gray>Cut <$white><0></$white> blocks to your clipboard.</$light_gray>
terraform.paste=$CONFIRM<$light_gray>Pasted <$white><0></$white> blocks from your clipboard.</$light_gray>

terraform.pos1.already_set=$INFO<$light_gray>Position 1 is <$white>already set</$white> here!</$light_gray>
terraform.pos2.already_set=$INFO<$light_gray>Position 2 is <$white>already set</$white> here!</$light_gray>
terraform.hpos.no_block=$DENY<$light_gray>No block in your line of sight!</$light_gray>
terraform.selection.reshape_unsupported=$DENY<$light_gray>The current selection type cannot be moved.</$light_gray>
terraform.selection.clear=$CONFIRM<$light_gray>Your selection has been <$white>cleared</$white>.</$light_gray>
terraform.selection.stack=$CONFIRM<$light_gray>Finished stacking <$white><0></$white> blocks.</$light_gray>
terraform.selection.move=$CONFIRM<$light_gray>Finished moving <$white><0></$white> blocks.</$light_gray>

terraform.schem.load=Schematic loaded (message todo)
terraform.schem.save=Schematic saved (message todo)
terraform.schem.delete=Schematic deleted (message todo)
terraform.schem.not_found=$DENY<$light_gray>Schematic <$white><0></$white> not found!</$light_gray>
terraform.schem.duplicate=$DENY<$light_gray>Schematic <$white><0></$white> already exists!</$light_gray>
terraform.schem.limit_exceeded=$DENY<$light_gray>You have reached the maximum number of schematics you can save!</$light_gray>
terraform.schem.size_limit_exceeded=$DENY<$light_gray>The schematic is too large to save!</$light_gray>

terraform.tool.create=$CONFIRM<$light_gray><$white><0></$white> tool created.</$light_gray>

terraform.generic.queue_full=$DENY<$light_gray>The task queue is full!</$light_gray>
terraform.generic.entities_unsupported=$WARNING<$light_gray>Entities are not supported in this command.</$light_gray>
terraform.generic.biomes_unsupported=$WARNING<$light_gray>Biomes are not supported in this command.</$light_gray>
terraform.clipboard.paste.original_pos_unsupported=$WARNING<$light_gray>Original position unsupported.</$light_gray>

#
# Worldedit specific messages
#

terraform.paste.select_only=$CONFIRM<$light_gray>Selected clipboard paste region</$light_gray>
terraform.selchunk=$CONFIRM<$light_gray>Selected chunk <$white><0></$white>.</$light_gray>
terraform.selchunk.range=$CONFIRM<$light_gray>Selected chunk region <$white><0></$white> .. <$white><1></$white>.</$light_gray>
terraform.selection.expand=$CONFIRM<$light_gray>Region expanded.</$light_gray>
terraform.selection.contract=$CONFIRM<$light_gray>Region contracted.</$light_gray>
terraform.selection.outset=$CONFIRM<$light_gray>Region outset.</$light_gray>
terraform.selection.inset=$CONFIRM<$light_gray>Region inset.</$light_gray>
terraform.selection.shift=$CONFIRM<$light_gray>Region shifted.</$light_gray>
terraform.selection.count=$CONFIRM<$light_gray>The region contains <$white><0></$white> matching blocks.</$light_gray>

#
# BELOW NEEDS TO BE REFACTORED INTO MESSAGES CLASSES
#

#
# COMMANDS
#

terraform.warn.border_exceeded=$DENY<$light_gray>You cannot build outside the <$white>world border</$white>!</$light_gray>
terraform.selection.replace=$CONFIRM<$light_gray>Finished replacing <$white><0></$white> blocks.</$light_gray>
terraform.selection.smear=$CONFIRM<$light_gray>Finished smearing <$white><0></$white> blocks.</$light_gray>
terraform.command.tf.cui.on=$INFO<$light_gray>Toggled cui <$lime>on</$lime>.</$light_gray>
terraform.command.tf.cui.off=$INFO<$light_gray>Toggled cui <$red>off</$red>.</$light_gray>

terraform.command.vanilla.clone.intersets=$DENY<$light_gray>Destination is inside of source, use force mode to bypass!</$light_gray>

#
# Clipboard
#
terraform.clipboard.list=$INFO<$light_gray>Current Clipboard:</$light_gray> <$white><0></$white>
terraform.clipboard.list.none=$INFO<$light_gray>You have <$white>nothing</$white> in your clipboard.</$light_gray>
# Flip
terraform.clipboard.flip.unknown_axis=$DENY<$light_gray>Unknown argument <0>! For now, you can only flip your clipboard on the x, y, and z axes.</$light_gray>
# Rotate
terraform.clipboard.rotate.unknown_axis=$DENY<$light_gray>Unknown argument <0>! For now, you can only rotate your clipboard on the x, y, and z axes.</$light_gray>
terraform.clipboard.rotate.invalid=$CONFIRM<$light_gray>You cannot rotate by nothing.</$light_gray>

#
# SELECTION TYPES
#
terraform.cuboid.explain.primary=$INFO<$light_gray>First position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.cuboid.explain.secondary=$INFO<$light_gray>Second position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.line.explain.primary=$INFO<$light_gray>First position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.line.explain.secondary=$INFO<$light_gray>Second position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.bezier.explain.primary=$INFO<$light_gray>First position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.bezier.explain.secondary=$INFO<$light_gray>Second position set to <$white><0></$white>, <$white><1></$white>, <$white><2></$white>.</$light_gray>
terraform.sel.type.set=$INFO<$light_gray>Your selection type was set to <$white><0></$white>.</$light_gray>
terraform.sel.clear=$CONFIRM<$light_gray>Your selection has been <$white>cleared</$white>.</$light_gray>

# SETH TODOS BELOW THEY NEED TO BE NICEIFIED

terraform.version=Terraform v<0>
terraform.queue.target_not_found=No player: <0>
terraform.queue.empty=No tasks running
terraform.queue.header=Running tasks (<0>):
# 0=task id, 1=task state, 2=time since start (pretty print)
terraform.queue.entry=<0>: <1> (created <2> ago)
terraform.cancel.not_found=Task not found: <0>
terraform.cancel.invalid=Task cannot be canceled
terraform.cancel.success=Task canceled!
terraform.cancel.all_none=No tasks running
terraform.cancel.all=All tasks canceled

