#
# COMMANDS
#

# Common to many commands
terraform.generic.no_selection=no selection
# (H)Pos(1|2)
terraform.pos1.already_set=pos1 is already there :(
terraform.pos2.already_set=pos1 is already there :(
# Set
# todo success message
# Replace
# todo success message
# Clipboard
terraform.clipboard.clear.

#
# REGION TYPES
#
terraform.cuboid.explain.primary=first pos set to <0> <1> <2>
terraform.cuboid.explain.secondary=second pos set to <0> <1> <2>
