apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "map-isolate.labels" . | nindent 4 }}
data:
  {{ .Release.Name }}-image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
