{{/*apiVersion: monitoring.coreos.com/v1*/}}
{{/*kind: ServiceMonitor*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "mapmaker-dev.fullname" . }}*/}}
{{/*  labels:*/}}
{{/*    {{- include "mapmaker-dev.labels" . | nindent 4 }}*/}}
{{/*spec:*/}}
{{/*  jobLabel: {{ .Release.Name }}*/}}
{{/*  namespaceSelector:*/}}
{{/*    matchNames:*/}}
{{/*      - {{ .Release.Namespace }}*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      {{- include "mapmaker-dev.selectorLabels" . | nindent 6 }}*/}}
{{/*  endpoints:*/}}
{{/*    - port: "http"*/}}
{{/*      path: /metrics*/}}
{{/*      interval: 30s*/}}
{{/*      scrapeTimeout: 10s*/}}
{{/*      relabelings:*/}}
{{/*        - sourceLabels: [ __meta_kubernetes_endpoints_label_app_kubernetes_io_version ]*/}}
{{/*          targetLabel: version*/}}
