apiVersion: v1
kind: Service
metadata:
  name: "map-headless"
  labels:
    {{- include "mapmaker-dev.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None # Headless service
  ports:
    - port: 25565
      targetPort: minecraft
      protocol: TCP
      name: minecraft
    - port: 9124
      targetPort: http
      protocol: TCP
      name: http
{{/*      nodePort: 30565*/}}
  selector:
    {{- include "mapmaker-dev.selectorLabels" . | nindent 4 }}
