package net.hollowcube.terraform.compat.axiom.packet.client;

public sealed interface AxiomClientPacket permits AxiomClientHelloPacket, AxiomClientRequestBlockEntityPacket, AxiomClientSetBlockPacket, AxiomClientSetBufferPacket, AxiomClientSetFlySpeedPacket, AxiomClientSetGameModePacket, AxiomClientSetWorldPropertyPacket, AxiomClientTeleportPacket {

}
