package net.hollowcube.scripting.emit;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import net.hollowcube.luau.LuaState;
import net.hollowcube.scripting.LuaNames;
import net.hollowcube.scripting.Model;

import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;

/// Emits the cross-cutting `LuaApiRegistry` class with a single `register(state)` that boots
/// every slopgen-generated library and top-level enum. The host's ScriptEngine calls this once
/// at state creation instead of hand-listing `<Lib>$luau.register(state)` per library.
///
/// Hand-written bits that *aren't* slopgen-generated (atom-callback wiring, vector lib, custom
/// globals) still get explicit calls — this registry is scoped to the surface slopgen actually
/// owns, so authors retain control over the rest of the boot sequence.
///
/// Aggregating: collects every library + every top-level enum in this AP run. Order is by FQN
/// of the glue class — deterministic across rounds. Registration order does not currently
/// matter (each library installs its own globals/modules; no cross-library references at
/// register time), so a single alphabetical sort is enough.
public final class ApiRegistryEmitter {

    public static final ClassName LUA_API_REGISTRY =
        ClassName.get(LuaNames.RUNTIME_PACKAGE_NAME, "LuaApiRegistry");

    public JavaFile emit(Collection<Model.Library> libraries,
                         Collection<Model.EnumDecl> topLevelEnums,
                         Element... originatingElements) {
        var typeBuilder = TypeSpec.classBuilder(LUA_API_REGISTRY)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL);
        for (var e : originatingElements) typeBuilder.addOriginatingElement(e);

        // Sort by glue FQN — single deterministic key for both libraries and enums.
        var libSorted = new ArrayList<>(libraries);
        libSorted.sort(Comparator.comparing(lib -> lib.glueType().canonicalName()));
        var enumSorted = new ArrayList<>(topLevelEnums);
        enumSorted.sort(Comparator.comparing(en -> en.glueType().canonicalName()));

        var register = MethodSpec.methodBuilder("register")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addParameter(LuaState.class, "state");

        if (libSorted.isEmpty() && enumSorted.isEmpty()) {
            // Nothing to register; keep the method present so callers don't have to conditionally
            // invoke it based on whether anything's annotated.
            return JavaFile.builder(LUA_API_REGISTRY.packageName(), typeBuilder.addMethod(register.build()).build())
                .addFileComment("Generated by Lua Slopgen. DO NOT EDIT!")
                .indent("    ")
                .build();
        }

        if (!libSorted.isEmpty()) register.addComment("Libraries");
        for (var lib : libSorted) {
            register.addStatement("$T.register(state)", lib.glueType());
        }
        if (!enumSorted.isEmpty()) {
            if (!libSorted.isEmpty()) register.addCode("\n");
            register.addComment("Top-level enums");
            for (var en : enumSorted) {
                register.addStatement("$T.register(state)", en.glueType());
            }
        }

        typeBuilder.addMethod(register.build());
        return JavaFile.builder(LUA_API_REGISTRY.packageName(), typeBuilder.build())
            .addFileComment("Generated by Lua Slopgen. DO NOT EDIT!")
            .indent("    ")
            .build();
    }
}
