package net.hollowcube.scripting.emit;

import com.palantir.javapoet.*;
import net.hollowcube.luau.LuaState;
import net.hollowcube.scripting.Model;
import org.jetbrains.annotations.NotNull;

import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;

/// Generates `<EnumName>$luau.java` for a TOP-LEVEL `@LuaEnum`. The companion class carries:
///
///   - `<NAME>_TAG` — light-userdata tag, minted by [net.hollowcube.scripting.Idents].
///   - `<NAME>_VALUES` — Java `.values()` array for ordinal lookup at check time.
///   - `push<Name>(state, value)` / `check<Name>Arg(state, idx)` — runtime push/check.
///   - `register(state)` — builds the constant table and sets it as a global.
///
/// Inner enums of an `@LuaLibrary` do NOT use this class — their glue is folded into the
/// enclosing library's `<Lib>$luau` by [LibraryEmitter] so a single `register(state)` call
/// boots the whole library.
public final class EnumEmitter {

    private static final ParameterSpec NOT_NULL_STATE = ParameterSpec.builder(LuaState.class, "state")
        .addAnnotation(NotNull.class)
        .build();

    public JavaFile emit(Model.EnumDecl en, Element... originatingElements) {
        var glue = TypeSpec.classBuilder(en.glueType())
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL);
        for (var e : originatingElements) glue.addOriginatingElement(e);

        // Java-side identifiers track the Java class name (matching the `@LuaExport` /
        // `pushItem` convention); only the Lua-visible identifiers — global name, table key,
        // error string — use the optional `@LuaEnum(name = …)` override.
        String javaName = en.sourceType().simpleName();
        String tagName = javaName.toUpperCase() + "_TAG";
        String valuesName = javaName.toUpperCase() + "_VALUES";

        glue.addField(FieldSpec.builder(int.class, tagName)
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer("$L", en.lightUserDataTag())
            .build());
        glue.addField(FieldSpec.builder(ArrayTypeName.of(en.sourceType()), valuesName)
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer("$T.values()", en.sourceType())
            .build());

        glue.addMethod(MethodSpec.methodBuilder("push" + javaName)
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addParameter(NOT_NULL_STATE)
            .addParameter(en.sourceType(), "value")
            .addStatement("state.pushLightUserDataTagged(value.ordinal(), $L)", tagName)
            .build());

        glue.addMethod(MethodSpec.methodBuilder("check" + javaName + "Arg")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addParameter(NOT_NULL_STATE)
            .addParameter(int.class, "argIndex")
            .returns(en.sourceType().annotated(AnnotationSpec.builder(NotNull.class).build()))
            .beginControlFlow("if ($L != state.lightUserDataTag(argIndex))", tagName)
            .addStatement("state.typeError(argIndex, $S)", en.luaName())
            .addStatement("return null")
            .endControlFlow()
            .addStatement("return $L[(int) state.toLightUserData(argIndex)]", valuesName)
            .build());

        var register = MethodSpec.methodBuilder("register")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addParameter(LuaState.class, "state");
        register.addStatement("state.newTable()");
        for (var c : en.constants()) {
            register.addStatement("state.pushLightUserDataTagged($L, $L)", c.ordinal(), tagName);
            register.addStatement("state.setField(-2, $S)", c.luaName());
        }
        register.addStatement("state.setReadOnly(-1, true)");
        register.addStatement("state.setGlobal($S)", en.luaName());
        glue.addMethod(register.build());

        return JavaFile.builder(en.glueType().packageName(), glue.build())
            .addFileComment("Generated by Lua Slopgen. DO NOT EDIT!")
            .indent("    ")
            .build();
    }
}
