package net.hollowcube.scripting.emit;

import net.hollowcube.scripting.Model;
import net.hollowcube.scripting.types.LuauType;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/// Emits the single ambient `global.d.luau` for every GLOBAL-scope library, in luau-lsp
/// `declare` grammar: `declare class <Name> [extends <Super>] … end` per export (the only place
/// operator metamethods are first-class), and `declare <Lib>: { … }` for a library's static
/// surface. No `require`, no `export type` table bodies, no `return`.
///
/// An ambient file cannot `require`, so any signature that references an `@`-require type is a
/// hard error — there is no valid Luau for it.
public final class GlobalDeclEmitter {

    private final Map<String, LibraryModuleEmitter.ExportRef> exportsByJavaType;

    public GlobalDeclEmitter(Map<String, LibraryModuleEmitter.ExportRef> exportsByJavaType) {
        this.exportsByJavaType = exportsByJavaType;
    }

    /// Thrown when a GLOBAL signature references a require-scope type — impossible in an ambient
    /// definitions file. Fails the build (caught by `DeclMain`).
    public static final class UnrepresentableGlobalException extends RuntimeException {
        public UnrepresentableGlobalException(String message) {
            super(message);
        }
    }

    /// Two-arg form for top-level enums + GLOBAL libraries. Inner enums of a GLOBAL library
    /// are picked up via [Model.Library#enums]; top-level enums (no enclosing library) come
    /// through `topLevelEnums`. The split exists because top-level enums don't synthesize a
    /// library wrapper.
    public String emit(List<Model.Library> globalLibs, List<Model.EnumDecl> topLevelEnums) {
        // Stable order by module name.
        var libs = new ArrayList<>(globalLibs);
        libs.sort(java.util.Comparator.comparing(Model.Library::moduleName));

        var out = new StringBuilder();
        out.append("-- Generated by lua-slopgen. DO NOT EDIT.\n");

        for (var entry : topoSortedExports(libs)) {
            var lib = entry.getKey();
            var ex = entry.getValue();
            RenderContext ctx = ambientContext(lib, ex.luaName());
            out.append('\n');
            emitClass(out, ex, ctx);
        }

        // Top-level enums first, then inner enums of GLOBAL libraries — both render with the
        // same `declare class <Name> end` + `declare <Name>: { … }` shape.
        for (var en : sortedEnums(topLevelEnums)) {
            out.append('\n');
            emitEnum(out, en);
        }
        for (var lib : libs) {
            for (var en : sortedEnums(lib.enums())) {
                out.append('\n');
                emitEnum(out, en);
            }
        }

        for (var lib : libs) {
            if (lib.staticMethods().isEmpty() && lib.staticProperties().isEmpty()) continue;
            RenderContext ctx = ambientContext(lib, lib.moduleName());
            out.append('\n');
            emitLibTable(out, lib, ctx);
        }
        return out.toString();
    }

    /// Back-compat single-arg overload for tests that don't care about enums.
    public String emit(List<Model.Library> globalLibs) {
        return emit(globalLibs, List.of());
    }

    private static List<Model.EnumDecl> sortedEnums(List<Model.EnumDecl> in) {
        var copy = new ArrayList<>(in);
        copy.sort(java.util.Comparator.comparing(Model.EnumDecl::luaName));
        return copy;
    }

    /// Ambient enum: a nominal placeholder class for the value type and a typed singleton table
    /// of its constants. Distinct from `declare class` for libraries — enums have no methods,
    /// just constant values.
    private static void emitEnum(StringBuilder out, Model.EnumDecl en) {
        out.append("declare class ").append(en.luaName()).append(" end\n");
        out.append("declare ").append(en.luaName()).append(": {\n");
        for (var c : en.constants())
            out.append('\t').append("read ").append(c.luaName()).append(": ")
                .append(en.luaName()).append(",\n");
        out.append("}\n");
    }

    private RenderContext ambientContext(Model.Library lib, String what) {
        return (module, name) -> {
            // Bare, or a short-form qualifier into another GLOBAL library: every global type is
            // ambient and visible by its bare name, so the qualifier is dropped.
            if (module == null || !module.startsWith("@")) return name;
            // An `@`-require type genuinely cannot appear here — ambient files cannot `require`.
            throw new UnrepresentableGlobalException(
                "global library '" + lib.moduleName() + "' (" + what + ") references require-scope type '"
                + module + "." + name + "' — ambient definitions cannot `require`, so there is no "
                + "valid Luau for this. Make the referenced type GLOBAL or drop the reference.");
        };
    }

    // ===================== declare class =====================

    private void emitClass(StringBuilder out, Model.Export ex, RenderContext ctx) {
        // `declare` syntax has no `type T = A | B` form, so a union alias can't be represented
        // in an ambient file. Fail loudly rather than emitting malformed Luau.
        if (ex.kind() == Model.Export.Kind.UNION_ALIAS)
            throw new UnrepresentableGlobalException(
                "global export '" + ex.luaName() + "' is a @LuaUnion alias; Luau `declare` "
                + "grammar has no type-alias form, so unions can't be ambient. Use REQUIRE "
                + "scope for the library that owns this union.");

        String header = "declare class " + ex.luaName();
        var sup = superName(ex);
        if (sup != null) header += " extends " + sup;

        var lines = new ArrayList<String>();
        for (var p : ex.properties()) {
            var acc = p.getter() != null ? p.getter() : p.setter();
            lines.add(p.luaName() + ": " + LuauTypeRenderer.render(acc.type(), ctx));
        }
        for (var m : ex.methods())
            lines.add(declFunction(m.luaName(), m.params(), m.returns(), ctx));
        for (var mm : ex.metaMethods())
            lines.add(declFunction(mm.meta(), mm.params(), mm.returns(), ctx));

        if (lines.isEmpty()) {
            out.append(header).append(" end\n");
            return;
        }
        out.append(header).append('\n');
        for (var l : lines) out.append('\t').append(l).append('\n');
        out.append("end\n");
    }

    /// `function name(self, p: T): R` — declare-class method form (self is untyped here).
    private String declFunction(String name, List<Model.Param> params, List<Model.Return> returns,
                                RenderContext ctx) {
        var sb = new StringBuilder("function ").append(name).append("(self");
        for (int i = 0; i < params.size(); i++) {
            var p = params.get(i);
            sb.append(", ");
            if (i == params.size() - 1 && p.type() instanceof LuauType.GenericPack)
                sb.append("...: ").append(LuauTypeRenderer.render(p.type(), ctx));
            else
                sb.append(p.name()).append(": ")
                    .append(LuauTypeRenderer.render(p.optional()
                        ? new LuauType.Optional(p.type()) : p.type(), ctx));
        }
        var rs = new ArrayList<LuauType>();
        for (var r : returns) rs.add(r.type());
        return sb.append("): ").append(LuauTypeRenderer.renderReturns(rs, ctx)).toString();
    }

    private String superName(Model.Export ex) {
        if (ex.superExport() == null) return null;
        var ref = exportsByJavaType.get(ex.superExport().toString());
        if (ref != null) return ref.luaName();
        String fqcn = ex.superExport().toString();
        return fqcn.substring(fqcn.lastIndexOf('.') + 1);
    }

    // ===================== declare <Lib>: { ... } =====================

    private void emitLibTable(StringBuilder out, Model.Library lib, RenderContext ctx) {
        // The global value is named by the library's leaf module name (e.g. `Text`, `runtime`).
        var parts = lib.moduleName().split("/");
        String name = parts[parts.length - 1];

        var lines = new ArrayList<String>();
        for (var p : lib.staticProperties()) {
            var acc = p.getter() != null ? p.getter() : p.setter();
            lines.add(p.luaName() + ": " + LuauTypeRenderer.render(acc.type(), ctx));
        }
        for (var sm : lib.staticMethods()) {
            var ps = new ArrayList<LuauType.Param>();
            for (var p : sm.params())
                ps.add(new LuauType.Param(p.name(),
                    p.optional() ? new LuauType.Optional(p.type()) : p.type()));
            var rs = new ArrayList<LuauType>();
            for (var r : sm.returns()) rs.add(r.type());
            lines.add(sm.luaName() + ": " + LuauTypeRenderer.render(
                new LuauType.Function(ps, null, rs), ctx));
        }

        out.append("declare ").append(name).append(": {\n");
        for (var l : lines) out.append('\t').append(l).append(",\n");
        out.append("}\n");
    }

    // ===================== topo order (super before sub) =====================

    private List<Map.Entry<Model.Library, Model.Export>> topoSortedExports(List<Model.Library> libs) {
        // Map export Java type -> its node, preserving (lib, export) source order as tiebreak.
        var byJava = new LinkedHashMap<String, Map.Entry<Model.Library, Model.Export>>();
        for (var lib : libs)
            for (var ex : lib.exports())
                byJava.put(ex.javaType().toString(), Map.entry(lib, ex));

        var ordered = new ArrayList<Map.Entry<Model.Library, Model.Export>>();
        var done = new java.util.HashSet<String>();
        for (var key : byJava.keySet()) visit(key, byJava, done, ordered);
        return ordered;
    }

    private void visit(String key,
                       Map<String, Map.Entry<Model.Library, Model.Export>> byJava,
                       java.util.Set<String> done,
                       List<Map.Entry<Model.Library, Model.Export>> out) {
        if (!byJava.containsKey(key) || !done.add(key)) return;
        var node = byJava.get(key);
        var sup = node.getValue().superExport();
        if (sup != null) visit(sup.toString(), byJava, done, out);
        out.add(node);
    }
}
