package net.hollowcube.sqlgen;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterSpec;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;

import javax.lang.model.element.Modifier;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/// Renders a [Model.Database] to source text, keyed by the path each file belongs at.
///
/// Nothing here reads the clock, the filesystem, or a hash map's iteration order: the same model
/// always produces byte-identical output, which is what lets the generated sources be committed and
/// checked for drift in CI.
final class Emitter {

    static final ClassName NULLABLE = ClassName.get("org.jetbrains.annotations", "Nullable");
    static final ClassName SNEAKY = ClassName.get("net.hollowcube.sqlgen.runtime", "Sneaky");
    static final ClassName CONNECTION_SOURCE = ClassName.get("net.hollowcube.sqlgen.runtime", "ConnectionSource");

    private static final String FILE_COMMENT = "Generated by sql-gen from src/main/sql. Do not edit.";

    private final Model.Database database;
    private final TypeMap types;

    Emitter(Model.Database database, TypeMap types) {
        this.database = database;
        this.types = types;
    }

    Map<String, String> emit() {
        var files = new LinkedHashMap<String, String>();
        var catalog = new EmitCatalog(database, types);

        for (var table : database.tables()) add(files, catalog.tableRecord(table));
        for (var pgEnum : database.enums()) add(files, catalog.pgEnum(pgEnum));

        add(files, EmitDatabase.emit(database));
        for (var group : database.groups()) {
            var emit = new EmitGroup(database, types, group);
            add(files, emit.groupInterface());
            add(files, emit.groupImpl());
        }
        files.put(database.packageName().replace('.', '/') + "/package-info.java", packageInfo());
        return Map.copyOf(files);
    }

    private void add(Map<String, String> files, TypeSpec type) {
        var file = JavaFile.builder(database.packageName(), type)
            .addFileComment(FILE_COMMENT)
            .indent("    ")
            .skipJavaLangImports(true)
            .build();
        var path = database.packageName().replace('.', '/') + "/" + type.name() + ".java";
        if (files.put(path, file.toString()) != null) {
            throw new GenException("two generated types would both be written to " + path);
        }
    }

    /// Everything in the generated package is non-null unless it says otherwise, which is what
    /// makes the `@Nullable` on an outer-join column or a `:one` query mean something.
    private String packageInfo() {
        return "// " + FILE_COMMENT + "\n"
            + "@NotNullByDefault\n"
            + "package " + database.packageName() + ";\n"
            + "\n"
            + "import org.jetbrains.annotations.NotNullByDefault;\n";
    }

    /// A record whose components come straight from a parameter list. javapoet models records by
    /// their canonical constructor, so this is the one place that shape is built.
    static TypeSpec record(String name, String javadoc, Iterable<ParameterSpec> components,
        Modifier... extra) {
        return record(name, javadoc, components, List.of(), extra);
    }

    /// @param extra modifiers beyond `public` — `static` for a record nested in an interface, which
    ///              is implicit in the language but not to javapoet
    static TypeSpec record(String name, String javadoc, Iterable<ParameterSpec> components,
        Iterable<MethodSpec> methods, Modifier... extra) {
        return TypeSpec.recordBuilder(name)
            .addJavadoc(javadoc)
            .addModifiers(Modifier.PUBLIC)
            .addModifiers(extra)
            .recordConstructor(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameters(components)
                .build())
            .addMethods(methods)
            .build();
    }

    static ParameterSpec component(TypeName type, String name, boolean nullable) {
        var parameter = ParameterSpec.builder(type, name);
        if (nullable) parameter.addAnnotation(AnnotationSpec.builder(NULLABLE).build());
        return parameter.build();
    }

    /// The SQL constant's initializer: a text block where the statement allows one, and a plain
    /// string where a `"""` or a backslash in the SQL would make that ambiguous.
    static CodeBlock sqlLiteral(String sql) {
        if (sql.isBlank() || !sql.contains("\n") || sql.contains("\"\"\"") || sql.contains("\\")) {
            return CodeBlock.of("$S", sql);
        }
        // The extra indent is incidental whitespace the compiler strips, and it keeps the SQL
        // reading as a nested block rather than as something that escaped the field declaration.
        var indented = sql.lines().map(line -> line.isEmpty() ? line : "    " + line)
            .collect(Collectors.joining("\n"));
        return CodeBlock.of("$L", "\"\"\"\n" + indented + "\"\"\"");
    }
}
