package net.hollowcube.anticheat.protocol;

import static net.hollowcube.anticheat.protocol.PacketTable.*;

/// The packet id tables for protocol version 777 (26.3): [Protocol776]'s, with the packets 26.3
/// added and the decoders whose layout it changed.
///
/// `swing` became `punch`, which is kept: the server resets the attack strength ticker on it. The
/// new S2C packets are all dropped — `add_transient_block` is a render-only ghost block,
/// `post_effects` a shader list, `swing_animation` the arm swing that left `animate`.
public final class Protocol777 {

    private static final Builder HANDSHAKE_C2S = new Builder()
        .drop("intention");
    private static final Builder LOGIN_C2S = new Builder()
        .drop("hello")
        .drop("key")
        .drop("custom_query_answer")
        .keep("login_acknowledged")
        .drop("cookie_response");
    private static final Builder LOGIN_S2C = new Builder()
        .keep("login_disconnect")
        .drop("hello")
        .keep("login_finished")
        .drop("login_compression")
        .drop("custom_query")
        .drop("cookie_request");
    private static final Builder CONFIGURATION_C2S = new Builder()
        .drop("client_information")
        .keep("cookie_response")
        .decode("custom_payload", C2SCustomPayload.V776::decode)
        .decode("finish_configuration", C2SFinishConfiguration.V776::decode)
        .keep("keep_alive")
        .decode("pong", C2SPong.V776::decode)
        .drop("resource_pack")
        .keep("select_known_packs")
        .drop("custom_click_action")
        .keep("accept_code_of_conduct");
    private static final Builder CONFIGURATION_S2C = new Builder()
        .keep("cookie_request")
        .decode("custom_payload", S2CCustomPayload.V776::decode)
        .keep("disconnect")
        .decode("finish_configuration", S2CFinishConfiguration.V776::decode)
        .keep("keep_alive")
        .decode("ping", S2CPing.V776::decode)
        .drop("reset_chat")
        .decode("registry_data", S2CRegistryData.V776::decode)
        .drop("resource_pack_pop")
        .keep("resource_pack_push")
        .drop("post_effects")
        .drop("store_cookie")
        .keep("transfer")
        .keep("update_enabled_features")
        .decode("update_tags", S2CUpdateTags.V776::decode)
        .keep("select_known_packs")
        .drop("custom_report_details")
        .drop("server_links")
        .keep("clear_dialog")
        .keep("show_dialog")
        .keep("code_of_conduct");
    private static final Builder PLAY_C2S = new Builder()
        .keep("accept_teleportation")
        .keep("attack")
        .drop("block_entity_tag_query")
        .keep("bundle_item_selected")
        .drop("change_difficulty")
        .keep("change_game_mode")
        .drop("chat_ack")
        .drop("chat_command")
        .drop("chat_command_signed")
        .drop("chat")
        .drop("chat_session_update")
        .keep("chunk_batch_received")
        .keep("client_command")
        .keep("client_tick_end")
        .drop("client_information")
        .drop("command_suggestion")
        .decode("configuration_acknowledged", C2SConfigurationAcknowledged.V776::decode)
        .drop("container_button_click")
        .keep("container_click")
        .keep("container_close")
        .drop("container_slot_state_changed")
        .keep("cookie_response")
        .decode("custom_payload", C2SCustomPayload.V776::decode)
        .drop("debug_subscription_request")
        .drop("edit_book")
        .drop("entity_tag_query")
        .keep("interact")
        .drop("jigsaw_generate")
        .keep("keep_alive")
        .drop("lock_difficulty")
        .decode("move_player_pos", C2SMovePlayerPos.V776::decode)
        .decode("move_player_pos_rot", C2SMovePlayerPosRot.V776::decode)
        .decode("move_player_rot", C2SMovePlayerRot.V776::decode)
        .decode("move_player_status_only", C2SMovePlayerStatusOnly.V776::decode)
        .keep("move_vehicle")
        .keep("paddle_boat")
        .keep("pick_item_from_block")
        .keep("pick_item_from_entity")
        .drop("ping_request")
        .drop("place_recipe")
        .keep("player_abilities")
        .keep("player_action")
        .keep("player_command")
        .keep("player_input")
        .keep("player_loaded")
        .decode("pong", C2SPong.V776::decode)
        .keep("punch")
        .drop("recipe_book_change_settings")
        .drop("recipe_book_seen_recipe")
        .drop("rename_item")
        .drop("resource_pack")
        .drop("seen_advancements")
        .drop("select_trade")
        .drop("set_beacon")
        .keep("set_carried_item")
        .drop("set_command_block")
        .drop("set_command_minecart")
        .keep("set_creative_mode_slot")
        .drop("set_game_rule")
        .drop("set_jigsaw_block")
        .drop("set_structure_block")
        .drop("set_test_block")
        .drop("sign_update")
        .keep("spectator_action")
        .keep("teleport_to_entity")
        .drop("test_instance_block_action")
        .keep("use_item_on")
        .keep("use_item")
        .drop("custom_click_action");
    private static final Builder PLAY_S2C = new Builder()
        .decode("bundle_delimiter", S2CBundleDelimiter.V776::decode)
        .decode("add_entity", S2CAddEntity.V776::decode)
        .decodePingWhen("animate", S2CAnimate.V777::decode, WAKE_UP)
        .drop("award_stats")
        .ping("block_changed_ack")
        .drop("block_destruction")
        .ping("block_entity_data")
        .ping("block_event")
        .decodePing("block_update", S2CBlockUpdate.V776::decode)
        .drop("boss_event")
        .drop("change_difficulty")
        .keep("chunk_batch_finished")
        .keep("chunk_batch_start")
        .keep("chunks_biomes")
        .drop("clear_titles")
        .drop("command_suggestions")
        .drop("commands")
        .keep("container_close")
        .decodePing("container_set_content", S2CContainerSetContent.V776::decode)
        .drop("container_set_data")
        .decodePing("container_set_slot", S2CContainerSetSlot.V776::decode)
        .keep("cookie_request")
        .ping("cooldown")
        .drop("custom_chat_completions")
        .decode("custom_payload", S2CCustomPayload.V776::decode)
        .keep("damage_event")
        .drop("debug/block_value")
        .drop("debug/chunk_value")
        .drop("debug/entity_value")
        .drop("debug/event")
        .drop("debug_sample")
        .drop("delete_chat")
        .keep("disconnect")
        .drop("disguised_chat")
        .decodePingWhen("entity_event", S2CEntityEvent.V776::decode, SELF_EVENT)
        .decode("entity_position_sync", S2CEntityPositionSync.V777::decode)
        .ping("explode")
        .drop("add_transient_block")
        .decodePing("forget_level_chunk", S2CForgetLevelChunk.V776::decode)
        .ping("game_event")
        .drop("game_rule_values")
        .drop("game_test_highlight_pos")
        .keep("mount_screen_open")
        .drop("hurt_animation")
        .ping("initialize_border")
        .keep("keep_alive")
        .decodePing("level_chunk_with_light", S2CLevelChunkWithLight.V777::decode)
        .drop("level_event")
        .drop("level_particles")
        .keep("light_update")
        .decodePing("login", S2CLogin.V777::decode)
        .drop("low_disk_space_warning")
        .drop("map_item_data")
        .drop("merchant_offers")
        .decode("move_entity_pos", S2CMoveEntityPos.V777::decode)
        .decode("move_entity_pos_rot", S2CMoveEntityPosRot.V777::decode)
        .keep("move_minecart_along_track")
        .decode("move_entity_rot", S2CMoveEntityRot.V777::decode)
        .keep("move_vehicle")
        .keep("open_book")
        .keep("open_screen")
        .keep("open_sign_editor")
        .decode("ping", S2CPing.V776::decode)
        .drop("pong_response")
        .drop("place_ghost_recipe")
        .ping("player_abilities")
        .drop("player_chat")
        .drop("player_combat_end")
        .drop("player_combat_enter")
        .keep("player_combat_kill")
        .keep("player_info_remove")
        .ping("player_info_update")
        .ping("player_look_at")
        .decodePing("player_position", S2CPlayerPosition.V776::decode)
        .decodePing("player_rotation", S2CPlayerRotation.V776::decode)
        .drop("recipe_book_add")
        .drop("recipe_book_remove")
        .drop("recipe_book_settings")
        .decode("remove_entities", S2CRemoveEntities.V776::decode)
        .decodePingWhen("remove_mob_effect", S2CRemoveMobEffect.V776::decode, SELF)
        .drop("reset_score")
        .drop("resource_pack_pop")
        .keep("resource_pack_push")
        .drop("post_effects")
        .decodePing("respawn", S2CRespawn.V777::decode)
        .drop("rotate_head")
        .decodePing("section_blocks_update", S2CSectionBlocksUpdate.V776::decode)
        .drop("select_advancements_tab")
        .drop("server_data")
        .drop("set_action_bar_text")
        .ping("set_border_center")
        .ping("set_border_lerp_size")
        .ping("set_border_size")
        .drop("set_border_warning_delay")
        .drop("set_border_warning_distance")
        .ping("set_camera")
        .decodePing("set_chunk_cache_center", S2CSetChunkCacheCenter.V776::decode)
        .decodePing("set_chunk_cache_radius", S2CSetChunkCacheRadius.V776::decode)
        .keep("set_cursor_item")
        .drop("set_default_spawn_position")
        .drop("set_display_objective")
        .decodePingWhen("set_entity_data", S2CSetEntityData.V776::decode, SELF)
        .decode("set_entity_link", S2CSetEntityLink.V776::decode)
        .decodePingWhen("set_entity_motion", S2CSetEntityMotion.V776::decode, SELF)
        .decode("set_equipment", S2CSetEquipment.V776::decode)
        .drop("set_experience")
        .ping("set_health")
        .ping("set_held_slot")
        .drop("set_objective")
        .decode("set_passengers", S2CSetPassengers.V776::decode)
        .decodePing("set_player_inventory", S2CSetPlayerInventory.V776::decode)
        .ping("set_player_team")
        .drop("set_score")
        .keep("set_simulation_distance")
        .drop("set_subtitle_text")
        .ping("set_time")
        .drop("set_title_text")
        .drop("set_titles_animation")
        .drop("sound_entity")
        .drop("sound")
        .decode("start_configuration", S2CStartConfiguration.V776::decode)
        .drop("stop_sound")
        .drop("store_cookie")
        .drop("swing_animation")
        .drop("system_chat")
        .drop("tab_list")
        .drop("tag_query")
        .drop("take_item_entity")
        .decode("teleport_entity", S2CTeleportEntity.V776::decode)
        .drop("test_instance_block_status")
        .ping("ticking_state")
        .ping("ticking_step")
        .keep("transfer")
        .drop("update_advancements")
        .decodePingWhen("update_attributes", S2CUpdateAttributes.V776::decode, SELF)
        .decodePingWhen("update_mob_effect", S2CUpdateMobEffect.V776::decode, SELF)
        .drop("update_recipes")
        .decodePing("update_tags", S2CUpdateTags.V776::decode)
        .drop("projectile_power")
        .drop("custom_report_details")
        .drop("server_links")
        .drop("waypoint")
        .keep("clear_dialog")
        .keep("show_dialog");

    public static final PacketTable PACKETS = new PacketTable(HANDSHAKE_C2S, LOGIN_C2S, LOGIN_S2C,
        CONFIGURATION_C2S, CONFIGURATION_S2C, PLAY_C2S, PLAY_S2C);

    private Protocol777() {}
}
