apiVersion: v1
kind: Service
metadata:
  name: {{ include "mapmaker-dev.fullname" . }}
  labels:
    {{- include "mapmaker-dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http

  selector:
    {{- include "mapmaker-dev.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "mapmaker-dev-minecraft"
  labels:
    {{- include "mapmaker-dev.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 25566
      targetPort: minecraft
      protocol: TCP
      name: minecraft

  selector:
    {{- include "mapmaker-dev.selectorLabels" . | nindent 4 }}
