package net.hollowcube.luau.engineapi.emit;

import com.palantir.javapoet.ClassName;
import net.hollowcube.luau.gen.LuaLibrary;
import net.hollowcube.luau.slopgen.Model;
import net.hollowcube.luau.slopgen.types.LuauType;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class LibraryModuleEmitterTest {

    private static final LibraryModuleEmitter EMPTY_REFS =
        new LibraryModuleEmitter(Map.of());

    private static LuauType t(String name) {
        return new LuauType.Named(null, name, List.of());
    }

    private static Model.Property roProp(String name, LuauType type) {
        return new Model.Property(name,
            new Model.Accessor("get", ClassName.get("p", "C"), "", null, type), null);
    }

    private static Model.Library lib(String module, List<Model.Export> exports,
                                     List<Model.Method> statics, List<Model.Property> staticProps) {
        return new Model.Library(ClassName.get("p", "Lib"), ClassName.get("p", "Lib$luau"),
            module, LuaLibrary.Scope.REQUIRE, exports, statics, staticProps, "");
    }

    @Test
    void exportWithGenericsPropsAndMethod() {
        var box = new Model.Export(
            ClassName.get("p", "Box"), "Box", null, false,
            List.of(new Model.GenericParam("T", false, "")),
            List.of(new Model.Property("value",
                new Model.Accessor("getValue", ClassName.get("p", "Box"), "", null, t("number")),
                new Model.Accessor("setValue", ClassName.get("p", "Box"), "", "v", t("number")))),
            List.of(new Model.Method("compute", "compute", false, ClassName.get("p", "Box"), "",
                List.of(), List.of(new Model.Param("x", false, t("number"), "")),
                List.of(new Model.Return(t("string"), "")))),
            List.of(), 1, false, "");

        String out = EMPTY_REFS.emit(lib("@mapmaker/foo", List.of(box), List.of(), List.of()));
        assertEquals("""
            -- Generated by lua-slopgen. DO NOT EDIT.
            
            export type Box<T> = {
            \tread value: number,
            \twrite value: number,
            \tread compute: (self: Box<T>, x: number) -> string,
            }
            
            return {}
            """, out);
    }

    @Test
    void metamethodUsesTypeofSetmetatable() {
        var box = new Model.Export(
            ClassName.get("p", "Box"), "Box", null, false, List.of(),
            List.of(roProp("value", t("number"))), List.of(),
            List.of(new Model.MetaMethod("__eq", "eq", false, "", List.of(),
                List.of(new Model.Param("other", false, t("Box"), "")),
                List.of(new Model.Return(t("boolean"), "")))),
            1, false, "");

        String out = EMPTY_REFS.emit(lib("@mapmaker/foo", List.of(box), List.of(), List.of()));
        assertTrue(out.contains("""
            type Box_Fields = {
            \tread value: number,
            }
            type Box_Meta = {
            \t__eq: (self: Box, other: Box) -> boolean,
            }
            export type Box = typeof(setmetatable({} :: Box_Fields, {} :: Box_Meta))"""), out);
    }

    @Test
    void superExportRendersAsIntersection() {
        var refs = new LibraryModuleEmitter(Map.of(
            "p.Base", new LibraryModuleEmitter.ExportRef("@mapmaker/foo", "Base")));
        var sub = new Model.Export(
            ClassName.get("p", "Sub"), "Sub", ClassName.get("p", "Base"), true, List.of(),
            List.of(roProp("x", t("number"))), List.of(), List.of(), 2, false, "");

        String out = refs.emit(lib("@mapmaker/foo", List.of(sub), List.of(), List.of()));
        assertTrue(out.contains("export type Sub = Base & {\n\tread x: number,\n}"), out);
    }

    @Test
    void staticMethodsUseLuneStyle() {
        var m = new Model.Method("doIt", "doIt", false, ClassName.get("p", "Lib"), "",
            List.of(), List.of(new Model.Param("n", false, t("number"), "")),
            List.of(new Model.Return(t("string"), "")));
        String out = EMPTY_REFS.emit(lib("@mapmaker/foo", List.of(), List.of(m), List.of()));
        assertTrue(out.contains("local foo = {}"), out);
        assertTrue(out.contains("function foo.doIt(n: number): string\n\treturn nil :: any\nend"), out);
        assertTrue(out.contains("return foo"), out);
    }

    @Test
    void staticPropsOnlyUseCast() {
        String out = EMPTY_REFS.emit(lib("@mapmaker/foo", List.of(), List.of(),
            List.of(roProp("version", t("string")))));
        assertTrue(out.endsWith("return (nil :: any) :: {\n\tread version: string,\n}\n"), out);
    }

    @Test
    void unionAliasEmitsSyntheticCommonShapeAndUnion() {
        // Mirrors the LibProp authoring shape: abstract sealed parent + two final variants. The
        // alias's id property must end up on the synthetic __PropMembers shape, not on Prop.
        var propType = ClassName.get("p", "Prop");
        var blockType = ClassName.get("p", "Block");
        var itemType = ClassName.get("p", "Item");

        var prop = new Model.Export(
            propType, "Prop", null, /*isFinal=*/false, List.of(),
            List.of(roProp("id", t("string"))),
            List.of(), List.of(), 1, /*hasSubtypes=*/true,
            Model.Export.Kind.UNION_ALIAS, List.of(blockType, itemType), "kind", "");
        var block = new Model.Export(
            blockType, "Block", propType, true, List.of(),
            List.of(roProp("kind", new LuauType.StringLiteral("block")),
                roProp("block", t("string"))),
            List.of(), List.of(), 2, false,
            Model.Export.Kind.UNION_VARIANT, List.of(), null, "");
        var item = new Model.Export(
            itemType, "Item", propType, true, List.of(),
            List.of(roProp("kind", new LuauType.StringLiteral("item")),
                roProp("item", t("string"))),
            List.of(), List.of(), 3, false,
            Model.Export.Kind.UNION_VARIANT, List.of(), null, "");

        String out = EMPTY_REFS.emit(lib("@mapmaker/prop", List.of(prop, block, item),
            List.of(), List.of()));
        assertTrue(out.contains("""
            type __PropMembers = {
            \tread id: string,
            }
            export type Prop = Block | Item
            """), out);
        assertTrue(out.contains("""
            export type Block = __PropMembers & {
            \tread kind: "block",
            \tread block: string,
            }
            """), out);
        assertTrue(out.contains("""
            export type Item = __PropMembers & {
            \tread kind: "item",
            \tread item: string,
            }
            """), out);
    }

    @Test
    void unionAliasNoMembersEmitsEmptyCommonShape() {
        // No declared members on the parent — the synthetic shape is still emitted as `{}` so
        // variants have something to intersect with (cheap and uniform).
        var rootType = ClassName.get("p", "Root");
        var aType = ClassName.get("p", "A");

        var root = new Model.Export(
            rootType, "Root", null, false, List.of(), List.of(), List.of(), List.of(),
            1, true, Model.Export.Kind.UNION_ALIAS, List.of(aType), null, "");
        var a = new Model.Export(
            aType, "A", rootType, true, List.of(),
            List.of(roProp("x", t("number"))),
            List.of(), List.of(), 2, false,
            Model.Export.Kind.UNION_VARIANT, List.of(), null, "");

        String out = EMPTY_REFS.emit(lib("@mapmaker/r", List.of(root, a), List.of(), List.of()));
        assertTrue(out.contains("type __RootMembers = {}"), out);
        assertTrue(out.contains("export type Root = A"), out);
        assertTrue(out.contains("export type A = __RootMembers & {\n\tread x: number,\n}"), out);
    }

    @Test
    void emptyLibraryReturnsEmptyTable() {
        String out = EMPTY_REFS.emit(lib("@mapmaker/foo", List.of(), List.of(), List.of()));
        assertEquals("-- Generated by lua-slopgen. DO NOT EDIT.\n\nreturn {}\n", out);
    }

    @Test
    void crossModuleReferenceEmitsRelativeRequire() {
        var ex = new Model.Export(
            ClassName.get("p", "User"), "User", null, false, List.of(),
            List.of(roProp("thing", new LuauType.Named("@mapmaker/bar", "Thing", List.of()))),
            List.of(), List.of(), 1, false, "");
        String out = EMPTY_REFS.emit(lib("@mapmaker/foo", List.of(ex), List.of(), List.of()));
        assertTrue(out.contains("local Bar = require(\"./bar\")"), out);
        assertTrue(out.contains("read thing: Bar.Thing"), out);
    }
}
