env:
  PROMETHEUS_DISABLE_CREATED_SERIES: "true"

image:
  repository: mworzala/mapmaker-dev
  pullPolicy: Always
imagePullSecrets:
  - name: dockerio

podAnnotations: { }

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    memory: 4Gi
  requests:
    memory: 2Gi

nodeSelector: { }
