replicaCount: 1

env:
  MAPMAKER_MONGO_URI: "${MONGO_URI}"
  # Legacy, kept for chat facet which does not use config quite yet
  MM_MONGO_URI: "${MONGO_URI}"
  MAPMAKER_S3_ADDRESS: "${R2_S3_ADDRESS}"
  MAPMAKER_S3_ACCESSKEY: "${R2_ACCESS_KEY}"
  MAPMAKER_S3_SECRETKEY: "${R2_SECRET_KEY}"
  MAPMAKER_SPICEDB_ADDRESS: "${SPICEDB_ADDRESS}"
  MAPMAKER_SPICEDB_SECRETKEY: "${SPICEDB_SECRET_KEY}"
  MAPMAKER_SPICEDB_TLS: "false"
