package net.hollowcube.luau.slopgen.emit;

import com.palantir.javapoet.*;
import it.unimi.dsi.fastutil.objects.Object2ShortMap;
import it.unimi.dsi.fastutil.objects.Object2ShortMaps;
import it.unimi.dsi.fastutil.objects.Object2ShortOpenHashMap;
import net.hollowcube.luau.LuaCallbacks;
import net.hollowcube.luau.LuaState;
import net.hollowcube.luau.slopgen.Idents;
import net.hollowcube.luau.slopgen.LuaNames;

import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import java.lang.foreign.Arena;

/// Emits the runtime atom-callback class (`GeneratedStringAtoms`) consulted by the Luau VM via
/// `LuaCallbacks.UserAtom`, plus the compile-time-constant class `LuaStringAtoms` referenced from
/// generated glue (the symbol form that lets the per-library processor stay isolating). Aggregating
/// by nature — collects atoms across every library in one place.
public final class AtomTableEmitter {

    public static final ClassName GENERATED_STRING_ATOMS =
        ClassName.get(LuaNames.RUNTIME_PACKAGE_NAME, "GeneratedStringAtoms");
    public static final ClassName LUA_STRING_ATOMS =
        ClassName.get(LuaNames.RUNTIME_PACKAGE_NAME, "LuaStringAtoms");

    public JavaFile emitConstants(Idents idents, Element... originatingElements) {
        var typeBuilder = TypeSpec.classBuilder(LUA_STRING_ATOMS)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL);
        for (var e : originatingElements) typeBuilder.addOriginatingElement(e);

        for (var entry : idents.entries()) {
            typeBuilder.addField(FieldSpec.builder(short.class, LuaNames.atomIdentifier(entry.luaName()))
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer("(short) $L", entry.value())
                .build());
        }

        return JavaFile.builder(LuaNames.RUNTIME_PACKAGE_NAME, typeBuilder.build())
            .addFileComment("Generated by Lua Slopgen. DO NOT EDIT!")
            .indent("    ")
            .build();
    }

    public JavaFile emit(Idents idents) {
        return emit(idents, new Element[0]);
    }

    public JavaFile emit(Idents idents, Element... originatingElements) {
        var typeBuilder = TypeSpec.classBuilder(GENERATED_STRING_ATOMS)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL);
        for (var e : originatingElements) typeBuilder.addOriginatingElement(e);

        typeBuilder.addField(FieldSpec.builder(LuaCallbacks.UserAtom.class, "USER_ATOM")
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .initializer("$T.allocate($T::$L, $T.global())",
                LuaCallbacks.UserAtom.class, GENERATED_STRING_ATOMS, "userAtom", Arena.class)
            .build());

        var mapType = ParameterizedTypeName.get(Object2ShortMap.class, String.class);
        typeBuilder.addField(FieldSpec.builder(mapType, "HOLDER")
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC, Modifier.FINAL)
            .build());

        typeBuilder.addMethod(MethodSpec.methodBuilder("register")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addParameter(LuaState.class, "state")
            .addStatement("state.callbacks().userAtom(USER_ATOM)")
            .build());

        typeBuilder.addMethod(MethodSpec.methodBuilder("userAtom")
            .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
            .addParameter(String.class, "string")
            .returns(TypeName.SHORT)
            .addStatement("return HOLDER.getOrDefault(string, $T.NO_ATOM)", LuaState.class)
            .build());

        var initBlock = CodeBlock.builder();
        initBlock.addStatement("$T holder = new $T<>()", mapType, Object2ShortOpenHashMap.class);
        for (var entry : idents.entries())
            initBlock.addStatement("holder.put($S, (short) $L)", entry.luaName(), entry.value());
        initBlock.addStatement("HOLDER = $T.unmodifiable(holder)", Object2ShortMaps.class);
        typeBuilder.addStaticBlock(initBlock.build());

        return JavaFile.builder(LuaNames.RUNTIME_PACKAGE_NAME, typeBuilder.build())
            .addFileComment("Generated by Lua Slopgen. DO NOT EDIT!")
            .indent("    ")
            .build();
    }
}
