apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mapmaker-dev.fullname" . }}
  labels:
    {{- include "mapmaker-dev.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mapmaker-dev.selectorLabels" . | nindent 6 }}
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        mapmaker.hollowcube.net/role: map
        {{- include "mapmaker-dev.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9124
              protocol: TCP
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: 9124
          readinessProbe:
            httpGet:
              path: /ready
              port: 9124
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}