// Generated by Lua Slopgen. DO NOT EDIT!
package fixtures;

import java.lang.String;
import java.lang.foreign.Arena;
import net.hollowcube.luau.LuaFunc;
import net.hollowcube.luau.LuaState;
import net.hollowcube.luau.gen.runtime.LuaStringAtoms;
import org.jetbrains.annotations.NotNull;

public final class LibSample$luau {
    private static final String LIB_NAME = "@test/sample";

    private static final LuaFunc INDEX = LuaFunc.wrap(LibSample$luau::index$meta, "__index", Arena.global());

    private static final LuaFunc NEWINDEX = LuaFunc.wrap(LibSample$luau::newindex$meta, "__newindex", Arena.global());

    private static final LuaFunc NAMECALL = LuaFunc.wrap(LibSample$luau::namecall$meta, "__namecall", Arena.global());

    private static final int ANIMAL_TAG = 1;

    private static final LuaFunc ANIMAL_INDEX = LuaFunc.wrap(LibSample$luau::animal$index$meta, "__index", Arena.global());

    private static final LuaFunc ANIMAL_NEWINDEX = LuaFunc.wrap(LibSample$luau::animal$newindex$meta, "__newindex", Arena.global());

    private static final LuaFunc ANIMAL_NAMECALL = LuaFunc.wrap(LibSample$luau::animal$namecall$meta, "__namecall", Arena.global());

    public static void pushAnimal(@NotNull LuaState state, LibSample.Animal obj) {
        state.newUserDataTaggedWithMetatable(obj, ANIMAL_TAG);
    }

    public static LibSample. @NotNull Animal checkAnimalArg(@NotNull LuaState state, int argIndex) {
        Object obj = state.toUserDataTagged(argIndex, ANIMAL_TAG);
        if (obj instanceof LibSample.Animal actual) {
            return actual;
        }
        state.typeError(argIndex, "Animal");
        return null;
    }

    private static int animal$namecall$dispatch(LuaState state, LibSample.Animal self, int atom) {
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to call nonexistent method");
        };
    }

    private static int animal$newindex$dispatch(LuaState state, LibSample.Animal self, int atom) {
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to update nonexistent property");
        };
    }

    private static int animal$index$dispatch(LuaState state, LibSample.Animal self, int atom) {
        return switch (atom) {
            case LuaStringAtoms.A_name/*name*/ -> self.getName(state);
            case LuaState.NO_ATOM -> 0;
            default -> 0;
        };
    }

    private static int dog$namecall$dispatch(LuaState state, LibSample.Dog self, int atom) {
        return switch (atom) {
            case LuaStringAtoms.A_bark/*bark*/ ->  {
                state.remove(1);
                self.bark(state);
                yield 0;
            }
            case Short.MIN_VALUE -> 0;
            default -> animal$namecall$dispatch(state, self, atom);
        };
    }

    private static int dog$newindex$dispatch(LuaState state, LibSample.Dog self, int atom) {
        return switch (atom) {
            case LuaStringAtoms.A_breed/*breed*/ ->  {
                self.setBreed(state);
                yield 0;
            }
            case Short.MIN_VALUE -> 0;
            default -> animal$newindex$dispatch(state, self, atom);
        };
    }

    private static int dog$index$dispatch(LuaState state, LibSample.Dog self, int atom) {
        return switch (atom) {
            case LuaStringAtoms.A_breed/*breed*/ -> self.getBreed(state);
            case LuaState.NO_ATOM -> 0;
            default -> animal$index$dispatch(state, self, atom);
        };
    }

    private static int animal$index$meta(LuaState state) {
        LibSample.Animal self = checkAnimalArg(state, 1);
        short atom = state.toStringAtomRaw(2);
        return switch (self) {
            case LibSample.Dog self1 -> dog$index$dispatch(state, self1, atom);
            default -> animal$index$dispatch(state, self, atom);
        };
    }

    private static int animal$newindex$meta(LuaState state) {
        LibSample.Animal self = checkAnimalArg(state, 1);
        state.remove(1);
        short atom = state.toStringAtomRaw(1);
        state.remove(1);
        return switch (self) {
            case LibSample.Dog self1 -> dog$newindex$dispatch(state, self1, atom);
            default -> animal$newindex$dispatch(state, self, atom);
        };
    }

    private static int animal$namecall$meta(LuaState state) {
        LibSample.Animal self = checkAnimalArg(state, 1);
        short atom = state.nameCallAtomRaw();
        return switch (self) {
            case LibSample.Dog self1 -> dog$namecall$dispatch(state, self1, atom);
            default -> animal$namecall$dispatch(state, self, atom);
        };
    }

    public static void register(LuaState state) {
        state.newUserData(new Object());
        state.newMetaTable(LIB_NAME);
        state.pushString(LIB_NAME);
        state.setField(-2, "__type");
        state.pushFunction(INDEX);
        state.setField(-2, "__index");
        state.pushFunction(NEWINDEX);
        state.setField(-2, "__newindex");
        state.pushFunction(NAMECALL);
        state.setField(-2, "__namecall");
        state.setReadOnly(-1, true);
        state.setMetaTable(-2);
        state.requireRegisterModule(LIB_NAME);

        // Type setup for Animal
        state.newMetaTable(LIB_NAME + ".Animal");
        state.pushString("Animal");
        state.setField(-2, "__type");
        state.pushFunction(ANIMAL_INDEX);
        state.setField(-2, "__index");
        state.pushFunction(ANIMAL_NEWINDEX);
        state.setField(-2, "__newindex");
        state.pushFunction(ANIMAL_NAMECALL);
        state.setField(-2, "__namecall");
        state.setReadOnly(-1, true);
        state.setUserDataMetaTable(ANIMAL_TAG);
    }

    private static int index$meta(LuaState state) {
        short atom = state.toStringAtomRaw(2);
        return switch (atom) {
            case LuaStringAtoms.A_version/*version*/ -> LibSample.getVersion(state);
            case LuaState.NO_ATOM -> 0;
            default -> 0;
        };
    }

    private static int newindex$meta(LuaState state) {
        state.remove(1);
        short atom = state.toStringAtomRaw(1);
        state.remove(1);
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to update nonexistent property");
        };
    }

    private static int namecall$meta(LuaState state) {
        short atom = state.nameCallAtomRaw();
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to call nonexistent method");
        };
    }
}
