package net.hollowcube.luau.engineapi.emit;

import net.hollowcube.luau.slopgen.Model;
import net.hollowcube.luau.slopgen.types.LuauType;
import org.jetbrains.annotations.Nullable;

import java.util.*;

/// Emits one real, `require`-able Luau module per REQUIRE-scope library: `export type` per
/// `@LuaExport`, the library's static surface as the module value, and relative `require`s for
/// every cross-library type it references. Mirrors the hand-written reference at
/// `bin/hub/src/main/resources/scripts/.types/*.luau`.
///
/// Operator metamethods can't live in an `export type` table, so an export that has any are
/// emitted as `typeof(setmetatable({} :: <E>_Fields, {} :: <E>_Meta))`.
public final class LibraryModuleEmitter {

    /// Cross-schema lookup: an export's Java type string → where it lives. Used to resolve
    /// `superExport` (a Java type) to the parent's Luau name and owning module.
    public record ExportRef(String moduleName, String luaName) {}

    private final Map<String, ExportRef> exportsByJavaType;

    public LibraryModuleEmitter(Map<String, ExportRef> exportsByJavaType) {
        this.exportsByJavaType = exportsByJavaType;
    }

    public String emit(Model.Library lib) {
        String module = lib.moduleName();

        // Pre-pass: collect every cross-library module referenced anywhere in this file so the
        // require header and its bindings are fixed and deterministic before rendering.
        var modules = new java.util.TreeSet<String>();
        for (var t : allRootTypes(lib)) collectModules(t, module, modules);

        var bindings = assignBindings(modules);
        RenderContext ctx = (m, name) -> {
            if (m == null || m.equals(module)) return name;
            String b = bindings.get(m);
            return b == null ? name : b + "." + name;
        };

        // Local lookup so a UNION_VARIANT's super reference can be rewritten onto its parent's
        // synthetic common shape. `permits` keeps the variants in the same compilation unit, so
        // the parent is always in the same library — a local map suffices.
        var exportsBySimpleType = new HashMap<String, Model.Export>();
        for (var ex : lib.exports()) exportsBySimpleType.put(ex.javaType().toString(), ex);

        var out = new StringBuilder();
        out.append("-- Generated by lua-slopgen. DO NOT EDIT.\n");

        if (!bindings.isEmpty()) {
            out.append('\n');
            for (var e : bindings.entrySet()) {
                out.append("local ").append(e.getValue())
                    .append(" = require(\"")
                    .append(ModuleLayout.relativeRequire(module, e.getKey()))
                    .append("\")\n");
            }
        }

        for (var ex : lib.exports()) {
            out.append('\n');
            emitExport(out, ex, ctx, exportsBySimpleType);
        }

        out.append('\n');
        emitModuleValue(out, lib, ctx);
        return out.toString();
    }

    /// Synthetic non-exported common-shape name for a [Model.Export.Kind#UNION_ALIAS]'s
    /// declared members. Variants intersect with this rather than the alias itself so the union
    /// type isn't self-referential.
    private static String commonShapeName(String aliasLuaName) {
        return "__" + aliasLuaName + "Members";
    }

    // ===================== Exports =====================

    private void emitExport(StringBuilder out, Model.Export ex, RenderContext ctx,
                            Map<String, Model.Export> exportsBySimpleType) {
        // UNION_ALIAS gets a bespoke layout: its declared members become a non-exported common
        // shape, and the exported name is the union of its variants. There are no metamethods
        // on a union alias (the parent class is abstract — no `__add` etc. is callable on it).
        if (ex.kind() == Model.Export.Kind.UNION_ALIAS) {
            emitUnionAlias(out, ex, ctx);
            return;
        }

        String name = ex.luaName();
        String gdecl = genericDecl(ex.generics());
        String guse = genericUse(ex.generics());
        LuauType superT = superType(ex, exportsBySimpleType);

        var members = new ArrayList<String>();
        for (var p : ex.properties()) {
            if (p.getter() != null)
                members.add("read " + p.luaName() + ": " + LuauTypeRenderer.render(p.getter().type(), ctx));
            if (p.setter() != null)
                members.add("write " + p.luaName() + ": " + LuauTypeRenderer.render(p.setter().type(), ctx));
        }
        for (var m : ex.methods())
            members.add("read " + m.luaName() + ": "
                        + LuauTypeRenderer.render(methodFn(ex, m.params(), m.returns()), ctx));

        if (ex.metaMethods().isEmpty()) {
            String body = superT == null
                ? table(members)
                : LuauTypeRenderer.render(superT, ctx) + (members.isEmpty() ? "" : " & " + table(members));
            out.append("export type ").append(name).append(gdecl).append(" = ").append(body).append('\n');
            return;
        }

        // typeof(setmetatable(...)) — the only module-scope form that carries metamethods.
        var metaLines = new ArrayList<String>();
        for (var mm : ex.metaMethods())
            metaLines.add(mm.meta() + ": "
                          + LuauTypeRenderer.render(methodFn(ex, mm.params(), mm.returns()), ctx));

        String fields = superT == null
            ? table(members)
            : LuauTypeRenderer.render(superT, ctx) + " & " + table(members.isEmpty() ? List.of() : members);
        out.append("type ").append(name).append("_Fields").append(gdecl).append(" = ").append(fields).append('\n');
        out.append("type ").append(name).append("_Meta").append(gdecl).append(" = ").append(table(metaLines)).append('\n');
        out.append("export type ").append(name).append(gdecl).append(" = typeof(setmetatable(")
            .append("{} :: ").append(name).append("_Fields").append(guse)
            .append(", {} :: ").append(name).append("_Meta").append(guse).append("))\n");
    }

    /// Render a UNION_ALIAS as `type __NameMembers = {...}` (private) + `export type Name =
    /// V1 | V2`. The synthetic shape carries the parent's declared properties and methods;
    /// variants intersect with it instead of the alias to avoid `Name` referencing itself.
    private void emitUnionAlias(StringBuilder out, Model.Export ex, RenderContext ctx) {
        String aliasName = ex.luaName();
        String shape = commonShapeName(aliasName);

        var members = new ArrayList<String>();
        for (var p : ex.properties()) {
            if (p.getter() != null)
                members.add("read " + p.luaName() + ": " + LuauTypeRenderer.render(p.getter().type(), ctx));
            if (p.setter() != null)
                members.add("write " + p.luaName() + ": " + LuauTypeRenderer.render(p.setter().type(), ctx));
        }
        for (var m : ex.methods())
            members.add("read " + m.luaName() + ": "
                        + LuauTypeRenderer.render(methodFn(ex, m.params(), m.returns()), ctx));

        out.append("type ").append(shape).append(" = ").append(table(members)).append('\n');

        var sj = new java.util.StringJoiner(" | ");
        for (var v : ex.unionVariants()) {
            String fqcn = v.toString();
            sj.add(fqcn.substring(fqcn.lastIndexOf('.') + 1));
        }
        out.append("export type ").append(aliasName).append(" = ").append(sj).append('\n');
    }

    /// `self` type for instance members: a declared `Self` generic if present, else the export
    /// applied to its own generic parameters.
    private LuauType selfType(Model.Export ex) {
        for (var g : ex.generics())
            if (g.name().equals("Self")) return new LuauType.GenericRef("Self");
        return new LuauType.Named(null, ex.luaName(), genericArgs(ex.generics()));
    }

    private LuauType.Function methodFn(Model.Export ex, List<Model.Param> params, List<Model.Return> returns) {
        var ps = new ArrayList<LuauType.Param>();
        ps.add(new LuauType.Param("self", selfType(ex)));
        for (var p : params) ps.add(new LuauType.Param(p.name(), paramType(p)));
        var rs = new ArrayList<LuauType>();
        for (var r : returns) rs.add(r.type());
        return new LuauType.Function(ps, null, rs);
    }

    private @Nullable LuauType superType(Model.Export ex,
                                         Map<String, Model.Export> exportsBySimpleType) {
        if (ex.superExport() == null) return null;
        // If the immediate parent is a UNION_ALIAS in the same library, the variant's "super"
        // is really the synthetic common shape, not the union alias (which by construction is
        // the union OVER us). Substitute the local synthetic name.
        var localParent = exportsBySimpleType.get(ex.superExport().toString());
        if (localParent != null && localParent.kind() == Model.Export.Kind.UNION_ALIAS)
            return new LuauType.Named(null, commonShapeName(localParent.luaName()), List.of());

        var ref = exportsByJavaType.get(ex.superExport().toString());
        if (ref == null) {
            // Fall back to the Java simple name; resolver already validated existence.
            String fqcn = ex.superExport().toString();
            String simple = fqcn.substring(fqcn.lastIndexOf('.') + 1);
            return new LuauType.Named(null, simple, List.of());
        }
        return new LuauType.Named(ref.moduleName(), ref.luaName(), List.of());
    }

    /// Overload used by the pre-pass module collector. Falls back to no local map so it cannot
    /// rewrite union variant supers — that's fine because the rewritten name is local-only and
    /// can't introduce any new cross-library require.
    private @Nullable LuauType superType(Model.Export ex) {
        return superType(ex, Map.of());
    }

    // ===================== Module value =====================

    private void emitModuleValue(StringBuilder out, Model.Library lib, RenderContext ctx) {
        var props = lib.staticProperties();
        var methods = lib.staticMethods();

        if (methods.isEmpty()) {
            if (props.isEmpty()) {
                out.append("return {}\n");
                return;
            }
            var lines = new ArrayList<String>();
            for (var p : props) {
                var acc = p.getter() != null ? p.getter() : p.setter();
                lines.add("read " + p.luaName() + ": " + LuauTypeRenderer.render(acc.type(), ctx));
            }
            out.append("return (nil :: any) :: ").append(table(lines)).append('\n');
            return;
        }

        String m = moduleLocal(lib.moduleName());
        out.append("local ").append(m).append(" = {}\n");
        for (var p : props) {
            var acc = p.getter() != null ? p.getter() : p.setter();
            out.append(m).append('.').append(p.luaName())
                .append(" = (nil :: any) :: ").append(LuauTypeRenderer.render(acc.type(), ctx)).append('\n');
        }
        for (var sm : lib.staticMethods()) {
            out.append('\n').append("function ").append(m).append('.').append(sm.luaName())
                .append(genericDecl(sm.generics())).append('(')
                .append(valueParams(sm.params(), ctx)).append("): ")
                .append(LuauTypeRenderer.renderReturns(returnTypes(sm.returns()), ctx))
                .append("\n\treturn nil :: any\nend\n");
        }
        out.append("\nreturn ").append(m).append('\n');
    }

    /// Value-declaration parameter list. A trailing generic-pack-typed param becomes the typed
    /// vararg `...: T...` (a bare pack-typed positional param is invalid Luau).
    private String valueParams(List<Model.Param> params, RenderContext ctx) {
        var sj = new StringBuilder();
        for (int i = 0; i < params.size(); i++) {
            var p = params.get(i);
            if (i > 0) sj.append(", ");
            if (p.type() instanceof LuauType.GenericPack)
                sj.append("...: ").append(LuauTypeRenderer.render(p.type(), ctx));
            else
                sj.append(p.name()).append(": ").append(LuauTypeRenderer.render(paramType(p), ctx));
        }
        return sj.toString();
    }

    // ===================== Shared helpers =====================

    private static LuauType paramType(Model.Param p) {
        return p.optional() ? new LuauType.Optional(p.type()) : p.type();
    }

    private static List<LuauType> returnTypes(List<Model.Return> returns) {
        var rs = new ArrayList<LuauType>();
        for (var r : returns) rs.add(r.type());
        return rs;
    }

    /// Generic declaration `<A, B...>` — Luau requires generic type packs after scalars.
    private static String genericDecl(List<Model.GenericParam> generics) {
        if (generics.isEmpty()) return "";
        var sj = new StringBuilder("<");
        boolean first = true;
        for (var g : ordered(generics)) {
            if (!first) sj.append(", ");
            sj.append(g.name());
            if (g.pack()) sj.append("...");
            first = false;
        }
        return sj.append('>').toString();
    }

    private static String genericUse(List<Model.GenericParam> generics) {
        return genericDecl(generics); // identical spelling for our forms (`<A, B...>`)
    }

    private static List<LuauType.TypeArg> genericArgs(List<Model.GenericParam> generics) {
        var args = new ArrayList<LuauType.TypeArg>();
        for (var g : ordered(generics)) {
            args.add(g.pack()
                ? new LuauType.TypeArg.Pack(List.of(), new LuauType.Variadic(new LuauType.GenericPack(g.name())))
                : new LuauType.TypeArg.Single(new LuauType.GenericRef(g.name())));
        }
        return args;
    }

    private static List<Model.GenericParam> ordered(List<Model.GenericParam> generics) {
        var out = new ArrayList<Model.GenericParam>(generics.size());
        for (var g : generics) if (!g.pack()) out.add(g);
        for (var g : generics) if (g.pack()) out.add(g);
        return out;
    }

    private static String table(List<String> members) {
        if (members.isEmpty()) return "{}";
        var sb = new StringBuilder("{\n");
        for (var mLine : members) sb.append('\t').append(mLine).append(",\n");
        return sb.append('}').toString();
    }

    private static String moduleLocal(String moduleName) {
        var parts = moduleName.split("/");
        String last = parts[parts.length - 1];
        var sb = new StringBuilder();
        for (int i = 0; i < last.length(); i++) {
            char c = last.charAt(i);
            if (Character.isLetterOrDigit(c) || c == '_') sb.append(c);
        }
        if (sb.isEmpty() || Character.isDigit(sb.charAt(0))) sb.insert(0, 'm');
        return sb.toString();
    }

    private static Map<String, String> assignBindings(Set<String> modules) {
        var used = new LinkedHashSet<String>();
        var map = new TreeMap<String, String>();
        for (var m : modules) {
            String base = ModuleLayout.localBinding(m);
            String b = base;
            int n = 2;
            while (!used.add(b)) b = base + (n++);
            map.put(m, b);
        }
        return map;
    }

    // ===================== Module collection pre-pass =====================

    private List<LuauType> allRootTypes(Model.Library lib) {
        var roots = new ArrayList<LuauType>();
        for (var ex : lib.exports()) {
            var st = superType(ex);
            if (st != null) roots.add(st);
            for (var p : ex.properties()) {
                if (p.getter() != null) roots.add(p.getter().type());
                if (p.setter() != null) roots.add(p.setter().type());
            }
            for (var m : ex.methods()) roots.add(methodFn(ex, m.params(), m.returns()));
            for (var mm : ex.metaMethods()) roots.add(methodFn(ex, mm.params(), mm.returns()));
        }
        for (var p : lib.staticProperties()) {
            if (p.getter() != null) roots.add(p.getter().type());
            if (p.setter() != null) roots.add(p.setter().type());
        }
        for (var sm : lib.staticMethods()) {
            for (var p : sm.params()) roots.add(paramType(p));
            for (var r : sm.returns()) roots.add(r.type());
        }
        return roots;
    }

    private static void collectModules(LuauType t, String self, Set<String> out) {
        switch (t) {
            case LuauType.Named n -> {
                if (n.module() != null && n.module().startsWith("@") && !n.module().equals(self))
                    out.add(n.module());
                for (var a : n.args()) {
                    switch (a) {
                        case LuauType.TypeArg.Single s -> collectModules(s.type(), self, out);
                        case LuauType.TypeArg.Pack p -> {
                            for (var x : p.types()) collectModules(x, self, out);
                            if (p.tail() != null) collectModules(p.tail().element(), self, out);
                        }
                    }
                }
            }
            case LuauType.Optional o -> collectModules(o.inner(), self, out);
            case LuauType.Union u -> u.alternatives().forEach(x -> collectModules(x, self, out));
            case LuauType.Intersection i -> i.conjuncts().forEach(x -> collectModules(x, self, out));
            case LuauType.Table tb -> {
                for (var f : tb.fields()) collectModules(f.type(), self, out);
                if (tb.arrayElement() != null) collectModules(tb.arrayElement(), self, out);
                if (tb.indexerKey() != null) collectModules(tb.indexerKey(), self, out);
                if (tb.indexerValue() != null) collectModules(tb.indexerValue(), self, out);
            }
            case LuauType.Function f -> {
                for (var p : f.params()) collectModules(p.type(), self, out);
                if (f.varargs() != null) collectModules(f.varargs().element(), self, out);
                for (var r : f.returns()) collectModules(r, self, out);
            }
            case LuauType.Variadic v -> collectModules(v.element(), self, out);
            case LuauType.GenericRef ignored -> {
            }
            case LuauType.GenericPack ignored -> {
            }
            case LuauType.TypeOf ignored -> {
            }
            case LuauType.StringLiteral ignored -> {
            }
            case LuauType.BoolLiteral ignored -> {
            }
        }
    }
}
