// Generated by Lua Slopgen. DO NOT EDIT!
package fixtures;

import java.lang.String;
import java.lang.foreign.Arena;
import net.hollowcube.luau.LuaFunc;
import net.hollowcube.luau.LuaState;
import org.jetbrains.annotations.NotNull;

public final class LibTree$luau {
    private static final String LIB_NAME = "@t/tree";

    private static final LuaFunc INDEX = LuaFunc.wrap(LibTree$luau::index$meta, "__index", Arena.global());

    private static final LuaFunc NEWINDEX = LuaFunc.wrap(LibTree$luau::newindex$meta, "__newindex", Arena.global());

    private static final LuaFunc NAMECALL = LuaFunc.wrap(LibTree$luau::namecall$meta, "__namecall", Arena.global());

    private static final int A_TAG = 1;

    private static final LuaFunc A_INDEX = LuaFunc.wrap(LibTree$luau::a$index$meta, "__index", Arena.global());

    private static final LuaFunc A_NEWINDEX = LuaFunc.wrap(LibTree$luau::a$newindex$meta, "__newindex", Arena.global());

    private static final LuaFunc A_NAMECALL = LuaFunc.wrap(LibTree$luau::a$namecall$meta, "__namecall", Arena.global());

    public static void pushA(@NotNull LuaState state, LibTree.A obj) {
        state.newUserDataTaggedWithMetatable(obj, A_TAG);
    }

    public static LibTree. @NotNull A checkAArg(@NotNull LuaState state, int argIndex) {
        Object obj = state.toUserDataTagged(argIndex, A_TAG);
        if (obj instanceof LibTree.A actual) {
            return actual;
        }
        state.typeError(argIndex, "A");
        return null;
    }

    private static int a$namecall$dispatch(LuaState state, LibTree.A self, int atom) {
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to call nonexistent method");
        };
    }

    private static int a$newindex$dispatch(LuaState state, LibTree.A self, int atom) {
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to update nonexistent property");
        };
    }

    private static int a$index$dispatch(LuaState state, LibTree.A self, int atom) {
        return switch (atom) {
            case 1/*x*/ -> self.getX(state);
            case LuaState.NO_ATOM -> 0;
            default -> 0;
        };
    }

    private static int b$namecall$dispatch(LuaState state, LibTree.B self, int atom) {
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> a$namecall$dispatch(state, self, atom);
        };
    }

    private static int b$newindex$dispatch(LuaState state, LibTree.B self, int atom) {
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> a$newindex$dispatch(state, self, atom);
        };
    }

    private static int b$index$dispatch(LuaState state, LibTree.B self, int atom) {
        return switch (atom) {
            case LuaState.NO_ATOM -> 0;
            default -> a$index$dispatch(state, self, atom);
        };
    }

    private static int c$namecall$dispatch(LuaState state, LibTree.C self, int atom) {
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> b$namecall$dispatch(state, self, atom);
        };
    }

    private static int c$newindex$dispatch(LuaState state, LibTree.C self, int atom) {
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> b$newindex$dispatch(state, self, atom);
        };
    }

    private static int c$index$dispatch(LuaState state, LibTree.C self, int atom) {
        return switch (atom) {
            case LuaState.NO_ATOM -> 0;
            default -> b$index$dispatch(state, self, atom);
        };
    }

    private static int a$index$meta(LuaState state) {
        LibTree.A self = checkAArg(state, 1);
        short atom = state.toStringAtomRaw(2);
        return switch (self) {
            case LibTree.C self1 -> c$index$dispatch(state, self1, atom);
            case LibTree.B self1 -> b$index$dispatch(state, self1, atom);
            default -> a$index$dispatch(state, self, atom);
        };
    }

    private static int a$newindex$meta(LuaState state) {
        LibTree.A self = checkAArg(state, 1);
        state.remove(1);
        short atom = state.toStringAtomRaw(1);
        state.remove(1);
        return switch (self) {
            case LibTree.C self1 -> c$newindex$dispatch(state, self1, atom);
            case LibTree.B self1 -> b$newindex$dispatch(state, self1, atom);
            default -> a$newindex$dispatch(state, self, atom);
        };
    }

    private static int a$namecall$meta(LuaState state) {
        LibTree.A self = checkAArg(state, 1);
        short atom = state.nameCallAtomRaw();
        return switch (self) {
            case LibTree.C self1 -> c$namecall$dispatch(state, self1, atom);
            case LibTree.B self1 -> b$namecall$dispatch(state, self1, atom);
            default -> a$namecall$dispatch(state, self, atom);
        };
    }

    public static void register(LuaState state) {
        state.newUserData(new Object());
        state.newMetaTable(LIB_NAME);
        state.pushString(LIB_NAME);
        state.setField(-2, "__type");
        state.pushFunction(INDEX);
        state.setField(-2, "__index");
        state.pushFunction(NEWINDEX);
        state.setField(-2, "__newindex");
        state.pushFunction(NAMECALL);
        state.setField(-2, "__namecall");
        state.setReadOnly(-1, true);
        state.setMetaTable(-2);
        state.requireRegisterModule(LIB_NAME);

        // Type setup for A
        state.newMetaTable(LIB_NAME + ".A");
        state.pushString("A");
        state.setField(-2, "__type");
        state.pushFunction(A_INDEX);
        state.setField(-2, "__index");
        state.pushFunction(A_NEWINDEX);
        state.setField(-2, "__newindex");
        state.pushFunction(A_NAMECALL);
        state.setField(-2, "__namecall");
        state.setReadOnly(-1, true);
        state.setUserDataMetaTable(A_TAG);
    }

    private static int index$meta(LuaState state) {
        short atom = state.toStringAtomRaw(2);
        return switch (atom) {
            case LuaState.NO_ATOM -> 0;
            default -> 0;
        };
    }

    private static int newindex$meta(LuaState state) {
        state.remove(1);
        short atom = state.toStringAtomRaw(1);
        state.remove(1);
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to update nonexistent property");
        };
    }

    private static int namecall$meta(LuaState state) {
        short atom = state.nameCallAtomRaw();
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to call nonexistent method");
        };
    }
}
