// Generated by Lua Slopgen. DO NOT EDIT!
package fixtures;

import java.lang.String;
import java.lang.foreign.Arena;
import net.hollowcube.luau.LuaFunc;
import net.hollowcube.luau.LuaState;
import org.jetbrains.annotations.NotNull;

public final class LibMeta$luau {
    private static final String LIB_NAME = "@t/meta";

    private static final LuaFunc INDEX = LuaFunc.wrap(LibMeta$luau::index$meta, "__index", Arena.global());

    private static final LuaFunc NEWINDEX = LuaFunc.wrap(LibMeta$luau::newindex$meta, "__newindex", Arena.global());

    private static final LuaFunc NAMECALL = LuaFunc.wrap(LibMeta$luau::namecall$meta, "__namecall", Arena.global());

    private static final LuaFunc VEC_INDEX = LuaFunc.wrap(LibMeta$luau::vec$index$meta, "__index", Arena.global());

    private static final LuaFunc VEC_NEWINDEX = LuaFunc.wrap(LibMeta$luau::vec$newindex$meta, "__newindex", Arena.global());

    private static final LuaFunc VEC_NAMECALL = LuaFunc.wrap(LibMeta$luau::vec$namecall$meta, "__namecall", Arena.global());

    private static final int VEC_TAG = 1;

    private static final LuaFunc VEC_PLUS = LuaFunc.wrap(LibMeta$luau::vec$plus, "__add", Arena.global());

    public static void pushVec(@NotNull LuaState state, LibMeta.Vec obj) {
        state.newUserDataTaggedWithMetatable(obj, VEC_TAG);
    }

    public static LibMeta. @NotNull Vec checkVecArg(@NotNull LuaState state, int argIndex) {
        Object obj = state.toUserDataTagged(argIndex, VEC_TAG);
        if (obj instanceof LibMeta.Vec actual) {
            return actual;
        }
        state.typeError(argIndex, "Vec");
        return null;
    }

    private static int vec$plus(LuaState state) {
        LibMeta.Vec self = checkVecArg(state, 1);
        state.remove(1);
        return self.plus(state);
    }

    private static int vec$namecall$meta(LuaState state) {
        LibMeta.Vec self = checkVecArg(state, 1);
        short atom = state.nameCallAtomRaw();
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to call nonexistent method");
        };
    }

    private static int vec$newindex$meta(LuaState state) {
        LibMeta.Vec self = checkVecArg(state, 1);
        state.remove(1);
        short atom = state.toStringAtomRaw(1);
        state.remove(1);
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to update nonexistent property");
        };
    }

    private static int vec$index$meta(LuaState state) {
        LibMeta.Vec self = checkVecArg(state, 1);
        short atom = state.toStringAtomRaw(2);
        return switch (atom) {
            case LuaState.NO_ATOM -> 0;
            default -> 0;
        };
    }

    public static void register(LuaState state) {
        state.newUserData(new Object());
        state.newMetaTable(LIB_NAME);
        state.pushString(LIB_NAME);
        state.setField(-2, "__type");
        state.pushFunction(INDEX);
        state.setField(-2, "__index");
        state.pushFunction(NEWINDEX);
        state.setField(-2, "__newindex");
        state.pushFunction(NAMECALL);
        state.setField(-2, "__namecall");
        state.setReadOnly(-1, true);
        state.setMetaTable(-2);
        state.requireRegisterModule(LIB_NAME);

        // Type setup for Vec
        state.newMetaTable(LIB_NAME + ".Vec");
        state.pushString("Vec");
        state.setField(-2, "__type");
        state.pushFunction(VEC_INDEX);
        state.setField(-2, "__index");
        state.pushFunction(VEC_NEWINDEX);
        state.setField(-2, "__newindex");
        state.pushFunction(VEC_NAMECALL);
        state.setField(-2, "__namecall");
        state.pushFunction(VEC_PLUS);
        state.setField(-2, "__add");
        state.setReadOnly(-1, true);
        state.setUserDataMetaTable(VEC_TAG);
    }

    private static int index$meta(LuaState state) {
        short atom = state.toStringAtomRaw(2);
        return switch (atom) {
            case LuaState.NO_ATOM -> 0;
            default -> 0;
        };
    }

    private static int newindex$meta(LuaState state) {
        state.remove(1);
        short atom = state.toStringAtomRaw(1);
        state.remove(1);
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to update nonexistent property");
        };
    }

    private static int namecall$meta(LuaState state) {
        short atom = state.nameCallAtomRaw();
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to call nonexistent method");
        };
    }
}
