// Generated by Lua Slopgen. DO NOT EDIT!
package fixtures;

import java.lang.String;
import java.lang.foreign.Arena;
import net.hollowcube.luau.LuaFunc;
import net.hollowcube.luau.LuaState;
import org.jetbrains.annotations.NotNull;

public final class LibSetter$luau {
    private static final String LIB_NAME = "@t/set";

    private static final LuaFunc INDEX = LuaFunc.wrap(LibSetter$luau::index$meta, "__index", Arena.global());

    private static final LuaFunc NEWINDEX = LuaFunc.wrap(LibSetter$luau::newindex$meta, "__newindex", Arena.global());

    private static final LuaFunc NAMECALL = LuaFunc.wrap(LibSetter$luau::namecall$meta, "__namecall", Arena.global());

    private static final LuaFunc THING_INDEX = LuaFunc.wrap(LibSetter$luau::thing$index$meta, "__index", Arena.global());

    private static final LuaFunc THING_NEWINDEX = LuaFunc.wrap(LibSetter$luau::thing$newindex$meta, "__newindex", Arena.global());

    private static final LuaFunc THING_NAMECALL = LuaFunc.wrap(LibSetter$luau::thing$namecall$meta, "__namecall", Arena.global());

    private static final int THING_TAG = 1;

    public static void pushThing(@NotNull LuaState state, LibSetter.Thing obj) {
        state.newUserDataTaggedWithMetatable(obj, THING_TAG);
    }

    public static LibSetter. @NotNull Thing checkThingArg(@NotNull LuaState state, int argIndex) {
        Object obj = state.toUserDataTagged(argIndex, THING_TAG);
        if (obj instanceof LibSetter.Thing actual) {
            return actual;
        }
        state.typeError(argIndex, "Thing");
        return null;
    }

    private static int thing$namecall$meta(LuaState state) {
        LibSetter.Thing self = checkThingArg(state, 1);
        short atom = state.nameCallAtomRaw();
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to call nonexistent method");
        };
    }

    private static int thing$newindex$meta(LuaState state) {
        LibSetter.Thing self = checkThingArg(state, 1);
        state.remove(1);
        short atom = state.toStringAtomRaw(1);
        state.remove(1);
        return switch (atom) {
            case 1/*color*/ ->  {
                self.setColor(state);
                yield 0;
            }
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to update nonexistent property");
        };
    }

    private static int thing$index$meta(LuaState state) {
        LibSetter.Thing self = checkThingArg(state, 1);
        short atom = state.toStringAtomRaw(2);
        return switch (atom) {
            case LuaState.NO_ATOM -> 0;
            default -> 0;
        };
    }

    public static void register(LuaState state) {
        state.newUserData(new Object());
        state.newMetaTable(LIB_NAME);
        state.pushString(LIB_NAME);
        state.setField(-2, "__type");
        state.pushFunction(INDEX);
        state.setField(-2, "__index");
        state.pushFunction(NEWINDEX);
        state.setField(-2, "__newindex");
        state.pushFunction(NAMECALL);
        state.setField(-2, "__namecall");
        state.setReadOnly(-1, true);
        state.setMetaTable(-2);
        state.requireRegisterModule(LIB_NAME);

        // Type setup for Thing
        state.newMetaTable(LIB_NAME + ".Thing");
        state.pushString("Thing");
        state.setField(-2, "__type");
        state.pushFunction(THING_INDEX);
        state.setField(-2, "__index");
        state.pushFunction(THING_NEWINDEX);
        state.setField(-2, "__newindex");
        state.pushFunction(THING_NAMECALL);
        state.setField(-2, "__namecall");
        state.setReadOnly(-1, true);
        state.setUserDataMetaTable(THING_TAG);
    }

    private static int index$meta(LuaState state) {
        short atom = state.toStringAtomRaw(2);
        return switch (atom) {
            case LuaState.NO_ATOM -> 0;
            default -> 0;
        };
    }

    private static int newindex$meta(LuaState state) {
        state.remove(1);
        short atom = state.toStringAtomRaw(1);
        state.remove(1);
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to update nonexistent property");
        };
    }

    private static int namecall$meta(LuaState state) {
        short atom = state.nameCallAtomRaw();
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to call nonexistent method");
        };
    }
}
