// Generated by Lua Slopgen. DO NOT EDIT!
package fixtures;

import java.lang.String;
import java.lang.foreign.Arena;
import net.hollowcube.luau.LuaFunc;
import net.hollowcube.luau.LuaState;

public final class LibStaticMethod$luau {
    private static final String LIB_NAME = "@t/sm";

    private static final LuaFunc INDEX = LuaFunc.wrap(LibStaticMethod$luau::index$meta, "__index", Arena.global());

    private static final LuaFunc NEWINDEX = LuaFunc.wrap(LibStaticMethod$luau::newindex$meta, "__newindex", Arena.global());

    private static final LuaFunc NAMECALL = LuaFunc.wrap(LibStaticMethod$luau::namecall$meta, "__namecall", Arena.global());

    private static final LuaFunc BUILD = LuaFunc.wrap(LibStaticMethod::build, "build");

    public static void register(LuaState state) {
        state.newUserData(new Object());
        state.newMetaTable(LIB_NAME);
        state.pushString(LIB_NAME);
        state.setField(-2, "__type");
        state.pushFunction(INDEX);
        state.setField(-2, "__index");
        state.pushFunction(NEWINDEX);
        state.setField(-2, "__newindex");
        state.pushFunction(NAMECALL);
        state.setField(-2, "__namecall");
        state.setReadOnly(-1, true);
        state.setMetaTable(-2);
        state.requireRegisterModule(LIB_NAME);
    }

    private static int index$meta(LuaState state) {
        short atom = state.toStringAtomRaw(2);
        return switch (atom) {
            case 1/*build*/ ->  {
                state.pushFunction(BUILD);
                yield 1;
            }
            case LuaState.NO_ATOM -> 0;
            default -> 0;
        };
    }

    private static int newindex$meta(LuaState state) {
        state.remove(1);
        short atom = state.toStringAtomRaw(1);
        state.remove(1);
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to update nonexistent property");
        };
    }

    private static int namecall$meta(LuaState state) {
        short atom = state.nameCallAtomRaw();
        return switch (atom) {
            case Short.MIN_VALUE -> 0;
            default -> throw state.error("Attempt to call nonexistent method");
        };
    }
}
