name: Staging Build & Deploy
concurrency: Staging

on:
  push:
    branches: [ main ]



jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.2.0
        with:
          url: https://secrets.hollowcube.dev
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            global/data/docker user | DOCKER_USER ;
            global/data/docker pass | DOCKER_PASS
      - name: Import Secrets 2
        uses: hollow-cube/actions/secrets@main
        with:
          token: ${{ secrets.VAULT_TOKEN }}
          path: global/resourcepackr2

      - uses: actions/checkout@v3
      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      #      - name: Set up JDK 19
      #        uses: actions/setup-java@v2
      #        with:
      #          java-version: 19
      #          distribution: 'temurin'
      #          cache: 'gradle'
      #      - name: Validate Gradle wrapper
      #        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      #      - name: Setup gradle
      #        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      #      - name: Package resources
      #        run: ./gradlew :bin:packer:run
      #      - name: Zip resource pack
      #        working-directory: build/packer
      #        run: |
      #          mkdir -p out
      #          cd client && zip -r ../out/mapmaker-${{ github.sha }}.zip .
      #          echo "RESOURCE_PACK_SHA=$(sha1sum out/mapmaker-${{ github.sha }}.zip | cut -d ' ' -f1)" >> $GITHUB_ENV
      #          echo "Resource pack sha-1: $(sha1sum out/mapmaker-${{ github.sha }}.zip | cut -d ' ' -f1)" >> $GITHUB_STEP_SUMMARY

      # Build & Upload Resource Pack (todo this could be a separate step probably)
      - name: Build resource pack
        run: |
          bazel build //:packer_development_client
          echo "RESOURCE_PACK_SHA=$(sha1sum bazel-bin/client.zip | cut -d ' ' -f1)" >> $GITHUB_ENV
          
          mkdir -p out
          cp bazel-bin/client.zip out/mapmaker-${{ github.sha }}.zip
      - name: Upload resource pack
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: resource-pack
          AWS_ACCESS_KEY_ID: ${{ env.RP_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ env.RP_SECRET_KEY }}
          AWS_S3_ENDPOINT: "https://bdb9cb2904188b760591dc1589a1ccf3.r2.cloudflarestorage.com"
          SOURCE_DIR: out

      # Build server
      - name: Prep runtime info
        run: |
          echo "commit_sha=${{ github.sha }}\nresource_pack_sha=${{ env.RESOURCE_PACK_SHA }}" >> bin/development/src/main/resources/runtime.properties
      - name: Build standalone binary
        run: bazel build //:development_deploy.jar

      # Build and push docker image
      - run: cp bazel-bin/development_deploy.jar development-all.jar
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.hollowcube.dev
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "bin/development/deploy/Dockerfile"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.hollowcube.dev/mapmaker-dev:${{ github.sha }}
  helm-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.2.0
        with:
          url: https://secrets.hollowcube.dev
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            global/data/docker user | DOCKER_USER ;
            global/data/docker pass | DOCKER_PASS
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.2
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Helm Chart
        run: |
          helm registry login registry.hollowcube.dev --username ${{ env.DOCKER_USER }} --password ${{ env.DOCKER_PASS }}
          helm package ./bin/development/deploy/mapmaker-dev --version "3.0.0-${{ github.sha }}" --app-version ${{ github.sha }}
          helm push mapmaker-dev-3.0.0-${{ github.sha }}.tgz oci://registry.hollowcube.dev/helm-charts
  helm-deploy:
    runs-on: 'ubuntu-latest'
    needs:
      - docker-build
      - helm-build
    steps:
      - name: Import Secrets
        uses: hollow-cube/actions/secrets@main
        with:
          token: ${{ secrets.VAULT_TOKEN }}
          path: global/github
      - name: Tailscale
        uses: tailscale/github-action@main
        with:
          authkey: ${{ env.TAILSCALE_AUTH_KEY }}
      - name: Import Secrets 2
        uses: hollow-cube/actions/secrets@main
        with:
          token: ${{ secrets.VAULT_TOKEN }}
          path: staging/mapmaker
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.2
      - uses: actions/checkout@v3
      - name: Upgrade/install helm chart
        run: |
          echo ${{ env.KUBECONFIG }} | base64 -d > ./kubeconfig
          helm registry login registry.hollowcube.dev --username hollowcube --password ${{ env.DOCKER_PASS }}
          helm pull oci://registry.hollowcube.dev/helm-charts/mapmaker-dev --version "3.0.0-${{ github.sha }}"
          cat bin/development/deploy/mapmaker-dev/values-staging.yaml | envsubst > ./values-override.yaml
          helm upgrade --install mapmaker-dev mapmaker-dev-3.0.0-${{ github.sha }}.tgz -n mapmaker --reset-values -f ./values-override.yaml --kubeconfig ./kubeconfig
