apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mapmaker-proxy.fullname" . }}
  labels:
    {{- include "mapmaker-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  forwarding.secret: {{ required "forwardingSecret is required" .Values.forwardingSecret | quote }}
